let movies = [
  {
    position: 1,
    name: "Babylon",
    year: 2022,
    url: "https://boxd.it/mM02",
    director: "Damien Chazelle",
    actors: [
      "Brad Pitt",
      "Margot Robbie",
      "Diego Calva",
      "Jean Smart",
      "Flea",
      "Jovan Adepo",
      "J.C. Currais",
      "Jimmy Ortega",
      "Hansford Prince",
      "Telvin Griffin",
      "Olivia Wilde",
      "Circus-Szalewski",
      "Lukas Haas",
      "Li Jun Li",
      "Kaia Gerber",
      "Patrick Fugit",
      "Eric Roberts",
      "Cici Lau",
      "Tyler Seiple",
      "Zack Newick",
      "Rory Scovel",
      "Olivia Hamilton",
      "P.J. Byrne",
      "Alexandre Chen",
      "Bob Clendenin",
      "Miraj Grbić",
      "Johnny Hoops",
      "James Wellington",
      "Carlos Nunez",
      "Laura Steinel",
      "Danny Jolles",
      "James Vincent",
      "Richard Clarke Larsen",
      "Max Minghella",
      "Samara Weaving",
      "Jeff Garlin",
      "Anthony Burkhalter",
      "Terry Walters",
      "Trisha Simmons",
      "Ariel Flores",
      "Karolina Szymczak",
      "Sean O'Bryan",
      "David Ury",
      "Katia Gomez",
      "Vanessa Bednar",
      "Carson Higgins",
      "Armando Cosio",
      "Frederick Koehler",
      "Spencer Morgan",
      "Ric Sarabia",
      "Jim Allen Jackson",
      "Katherine Waterston",
      "Yissendy Trinidad",
      "Cyrus Hobbi",
      "Anton Hedayat",
      "Hayley Huntley",
      "John Mariano",
      "Christopher Allen",
      "Arely Vianet",
      "Jeremy Roberts",
      "Alex Reznik",
      "Chloe Fineman",
      "Pat Skipper",
      "John Kerry",
      "Sarah Ramos",
      "Jennifer Grant",
      "Julian Lefevre",
      "Taylor Nichols",
      "Bryan Scott Johnson",
      "Kelly Meyer",
      "Brenna Power",
      "David Abed",
      "Kevin Symons",
      "Jonathan Thomson",
      "Jim O'Brien",
      "Chris Doubek",
      "Dorian Martin",
      "Todd Giebenhain",
      "Mather Zickel",
      "Ireland Sexton",
      "Andrew Hawtrey",
      "Mike Fletcher",
      "Jonathan Ohye",
      "James Crittenden",
      "Pete Ploszek",
      "Robert Beitzel",
      "Ethan Suplee",
      "Walker Hare",
      "Douglas Fruchey",
      "Taylor Hill",
      "Marc Platt",
      "Stephen Thomas",
      "Sophia Magaña",
      "Karen Bethzabe",
      "Oscar Balderrama",
      "Aurielle Simmons",
      "Eamon Hunt",
      "Kenajuan Bentley",
      "John Macey",
      "Noah Reilly",
      "Marcos A. Ferraez",
      "Phoebe Tonkin",
      "Troy Metcalf",
      "Albert Hammond Jr.",
      "Cutty Cuthbert",
      "Bregje Heinen",
      "Dana Marcolina",
      "Tal Seder",
      "Robert Morgan",
      "Nana Ghana",
      "Joe Dallesandro",
      "E.E. Bell",
      "Sol Landerman",
      "Karina Fontes",
      "Spike Jonze",
      "Freya Parker",
      "Tobey Maguire",
      "Lewis Tan",
      "Manny Liotta",
      "Anna Chazelle",
    ],
  },
  {
    position: 2,
    name: "Brawl in Cell Block 99",
    year: 2017,
    url: "https://boxd.it/dWOo",
    director: "",
    actors: [
      "Vince Vaughn",
      "Jennifer Carpenter",
      "Don Johnson",
      "Udo Kier",
      "Dion Mucciacito",
      "Geno Segers",
      "Mustafa Shakir",
      "Marc Blucas",
      "Tom Guiry",
      "Fred Melamed",
      "Clark Johnson",
      "Devon Windsor",
      "Pooja Kumar",
      "Jay Hieron",
      "Michael Medeiros",
      "Rob Morgan",
      "Victor Almanzar",
      "Willie C. Carpenter",
      "Gabriel Sloyer",
      "Jonathan Lee",
      "Tobee Paik",
      "Dan Amboyer",
      "Calvin Dutton",
      "Brandon Alan Smith",
      "Mike Hodge",
      "Larry Mitchell",
      "Keren Dukes",
      "Phil McGlaston",
      "Tuffy Questell",
      "Peter Jay Fernandez",
      "Adam Mucci",
      "Philip Ettinger",
      "Gilbert Soto",
      "Charles Dumas",
      "Franco Gonzalez",
      "Ernesto Rosas",
      "Brian Wiles",
      "Adrian Matilla",
      "Louis Scarano",
      "Bill Anagnos",
      "Corey Pierno",
      "Ohene Cornelius",
      "Vladimir Troitsky",
    ],
  },
  {
    position: 3,
    name: "Cha Cha Real Smooth",
    year: 2022,
    url: "https://boxd.it/uF8E",
    director: "Cooper Raiff",
    actors: [
      [
        "Cooper Raiff",
        "Dakota Johnson",
        "Vanessa Burghardt",
        "Evan Assante",
        "Leslie Mann",
        "Brad Garrett",
        "Raúl Castillo",
        "Amara Pedroso Saquel",
        "Odeya Rush",
        "Brooklyn Ramirez",
        "Kelly O'Sullivan",
        "Javien Mercado",
        "Chris Newman",
        "John Paul Hurley",
        "Davina Reid",
        "Lisa Velten Smith",
        "Corrie Danieley",
        "Eamonn McElfresh",
        "Mike Dennis",
        "Alison Weisgall",
        "Jonathan Visser",
        "Tommy Lafitte",
        "Jonathan Berry",
        "Colton Osorio",
      ],
    ],
  },
  {
    position: 4,
    name: "The Method",
    year: 2005,
    url: "https://boxd.it/1CuE",
    director: "",
    actors: [
      [
        "Eduardo Noriega",
        "Najwa Nimri",
        "Eduard Fernández",
        "Pablo Echarri",
        "Ernesto Alterio",
        "Natalia Verbeke",
        "Adriana Ozores",
        "Carmelo Gómez",
      ],
    ],
  },
  {
    position: 5,
    name: "The Good Nurse",
    year: 2022,
    url: "https://boxd.it/jIXI",
    director: "",
    actors: [
      "Jessica Chastain",
      "Eddie Redmayne",
      "Nnamdi Asomugha",
      "Kim Dickens",
      "Malik Yoba",
      "Alix West Lefler",
      "Noah Emmerich",
      "Gabe Fazio",
      "Ajay Naidu",
      "Maurice J. Irvin",
      "Maria Dizzia",
      "Shaun O'Hagan",
      "Marcia Jean Kurtz",
      "Myra Lucretia Taylor",
      "Denise Pillott",
      "Dartel McRae",
      "Joseph Fugelo",
      "Judith Delgado",
      "Jesus-Papoleto Melendez",
      "Devyn McDowell",
      "Jennean Farmer",
      "Navya La Shay",
      "David Lavine",
      "Bruce MacVittie",
      "Brooke Stacy Mills",
      "Charlotte Cohn-Williams",
      "Christine Healy",
      "Maria Farrow",
      "Alex Bartner",
      "Anjelica Bosboom",
      "Rebecca Watson",
      "Jennifer Regan",
      "Beth Dixon",
      "Brian Sayers",
      "Steve Antonucci",
      "Evan Bass",
      "Andrew James Bleidner",
      "David Boston",
      "Marko Caka",
      "Chris Henry Coffey",
      "Victor Cruz",
      "Sheetal Deo",
      "Marcia M Francis",
      "Gina Jun",
      "Becca Marks",
      "Lauren Yaffe",
    ],
  },
  {
    position: 6,
    name: "White Men Can't Jump",
    year: 1992,
    url: "https://boxd.it/1WWy",
    director: "",
    actors: [
      "Wesley Snipes",
      "Woody Harrelson",
      "Rosie Perez",
      "Tyra Ferrell",
      "Cylk Cozart",
      "Kadeem Hardison",
      "Ernest Harden Jr.",
      "John Marshall Jones",
      "Marques Johnson",
      "David Roberson",
      "Kevin Benton",
      "Nigel Miguel",
      "Duane Martin",
      "Bill Henderson",
      "Sonny Craver",
      "Jon Hendricks",
      "Eloy Casados",
      "Frank Rossi",
      "Freeman Williams",
      "Louis Price",
      "Alex Trebek",
      "Reggie Leon",
      "Sarah Stavrou",
      "Reynaldo Rey",
      "Lanei Chapman",
      "Irene Nettles",
      "Torri Whitehead",
      "Lisa McDowell",
      "Dion B. Vines",
      "David Maxwell",
      "Bill Caplan",
      "Richard James Baker",
      "Amy Golden",
      "Jeanette Srubar",
      "Zandra Hill",
      "Fred P. Gregory",
      "Carl E. Hodge",
      "Ruben Martinez",
      "Gary Lazar",
      "Donna Howell",
      "Don Fullilove",
      "Johnny Gilbert",
      "Leonard A. Oakland",
      "Allan Malamud",
      "Jeanne McCarthy",
      "John Charles Sheehan",
      "Gregg Daniel",
      "Carl A. McGee",
      "Chick Hearn",
      "Stu Lantz",
      "Ronald Beals",
      "Joe Metcalf",
      "Mahcoe Moore",
      "Mark Hill",
      "Eric Kizzie",
      "Chalmer Maddox",
      "Leroy Michaux",
      "Joseph Duffy",
      "Pete Duffy",
      "Gary Moeller",
      "Daniel Porto",
      "Lester Hawkins",
      "Jeffrey Todd",
    ],
  },
  {
    position: 7,
    name: "Puss in Boots: The Last Wish",
    year: 2022,
    url: "https://boxd.it/aaie",
    director: "",
    actors: [
      "Antonio Banderas",
      "Salma Hayek",
      "Harvey Guillén",
      "Wagner Moura",
      "Florence Pugh",
      "Olivia Colman",
      "Ray Winstone",
      "Samson Kayo",
      "John Mulaney",
      "Da'Vine Joy Randolph",
      "Anthony Mendez",
      "Kevin McCann",
      "Bernardo de Paula",
      "Betsy Sodaro",
      "Artemis Pebdani",
      "Conrad Vernon",
      "Cody Cameron",
      "Kailey Crawford",
      "Al Rodrigo",
      "Bob Persichetti",
      "Miguel Matrai",
      "Pilar Uribe",
      "Heidi Gardner",
      "Joel Crawford",
      "Januel Mercado",
      "James Ryan",
      "Natalia Cronembold",
      "Paul Fisher",
      "Aydrea Walden",
    ],
  },
  {
    position: 8,
    name: "The Substitute",
    year: 2022,
    url: "https://boxd.it/xsT4",
    director: "",
    actors: [
      "Juan Minujín",
      "Bárbara Lennie",
      "Alfredo Castro",
      "Rita Cortese",
      "María Merlino",
      "Lucas Arrúa",
      "Renata Lerman",
      "Martín Kohan",
    ],
  },
  {
    position: 9,
    name: "Operation Mincemeat",
    year: 2021,
    url: "https://boxd.it/oAY4",
    director: "",
    actors: [
      "Colin Firth",
      "Matthew Macfadyen",
      "Kelly Macdonald",
      "Penelope Wilton",
      "Johnny Flynn",
      "Jason Isaacs",
      "Mark Gatiss",
      "Hattie Morahan",
      "Paul Ritter",
      "Simon Russell Beale",
      "Lorne MacFadyen",
      "Markus von Lingen",
      "Ruby Bentall",
      "Alex Jennings",
      "Ellie Haddington",
      "Nicholas Rowe",
      "Will Keen",
      "Mark Bonnar",
      "James Fleet",
      "Alexander Beyer",
      "Nico Birnbaum",
      "Pep Tosar",
      "Alba Brunet",
      "Pedro Casablanc",
      "Óscar Zafra",
      "Javier Godino",
      "Jonjo O'Neill",
      "Amy Marston",
      "Gabrielle Creevy",
      "Simon Rouse",
      "Paul Lancaster",
      "Michael Bott",
      "Charlotte Hamblin",
      "Rufus Wright",
    ],
  },
  {
    position: 10,
    name: "Puss in Boots",
    year: 2011,
    url: "https://boxd.it/eL34",
    director: "",
    actors: [
      "Antonio Banderas",
      "Salma Hayek",
      "Zach Galifianakis",
      "Billy Bob Thornton",
      "Amy Sedaris",
      "Constance Marie",
      "Mike Mitchell",
      "Guillermo del Toro",
      "Conrad Vernon",
      "Chris Miller",
      "Rich Dietl",
      "Ryan Crego",
      "Tom Wheeler",
      "Tom McGrath",
      "Bob Joles",
      "Latifa Ouaou",
      "Bob Persichetti",
      "Jessica Schulte",
      "Nina Barry",
      "Sergio Bruna",
      "Rebecca Davis",
      "Roberto Donati",
      "Jossara Jinaro",
      "Lara Jill Miller",
      "Joshua Rush",
      "Julie Wittner",
    ],
  },
  {
    position: 11,
    name: "Aftersun",
    year: 2022,
    url: "https://boxd.it/Arw0",
    director: "",
    actors: [
      "Frankie Corio",
      "Paul Mescal",
      "Celia Rowlson-Hall",
      "Sally Messham",
      "Ayşe Parlak",
      "Sophia Lamanova",
      "Brooklyn Toulson",
      "Spike Fearn",
      "Harry Perdios",
      "Frank Corio",
      "Ruby Thompson",
      "Ethan James Smith",
      "Onur Ekşioğlu",
      "Cafer Karahan",
      "Kayleigh Coleman",
      "John Stuifzand",
      "Tyler Mutlu",
      "Kieran Burton",
      "Nijat Gachayev",
      "Sarah Makharine",
      "Erol Cengizalp",
    ],
  },
  {
    position: 12,
    name: "Let's Go to Prison",
    year: 2006,
    url: "https://boxd.it/1XL2",
    director: "",
    actors: [
      "Dax Shepard",
      "Will Arnett",
      "Chi McBride",
      "David Koechner",
      "Dylan Baker",
      "Michael Shannon",
      "Jay Whittaker",
      "Amy Hill",
      "David Darlow",
      "Bob Odenkirk",
      "Jerry Minor",
      "Joseph Marcus",
      "Nick Phalen",
      "A.J. Balance",
      "Mary Seibel",
      "Susan Messing",
      "Jim Zulevic",
      "Bill McGough",
      "Bert Matias",
      "Miguel Nino",
      "Scott Philyaw",
      "Tim Heidecker",
      "Eric Wareheim",
    ],
  },
  {
    position: 13,
    name: "Along Came a Spider",
    year: 2001,
    url: "https://boxd.it/27yW",
    director: "",
    actors: [
      "Morgan Freeman",
      "Monica Potter",
      "Michael Wincott",
      "Dylan Baker",
      "Mika Boorem",
      "Anton Yelchin",
      "Kim Hawthorne",
      "Jay O. Sanders",
      "Billy Burke",
      "Michael Moriarty",
      "Penelope Ann Miller",
      "Anna Maria Horsford",
      "Scott Heindl",
      "Christopher Shyer",
      "Jill Teed",
      "Ian Marsh",
      "Raoul Ganeev",
      "Samantha Ferris",
      "Ocean Hellman",
      "Tom McBeath",
      "Tamara Taggart",
      "Suzette Meyers",
      "Brian Arnold",
      "Chris Robson",
      "Jonathan Walker",
      "Debra Donohue",
      "Mila Dobrozdravich",
      "Aaron Joseph",
      "Ravil Isyanov",
      "Ronin Wong",
      "Campbell Lane",
      "Charles Andre",
      "Claire Riley",
      "Paul Carson",
      "Donna Lysell",
      "Kevin Hayes",
      "Steve Makaj",
      "Nathaniel DeVeaux",
      "Wynn Hall",
      "Charles Andison",
      "Tarie Tennessey",
      "Darryl Scheelar",
      "Craig March",
      "Darryl Dillard",
      "Carter Jahncke",
      "Jim Hild",
    ],
  },
  {
    position: 14,
    name: "The Bone Collector",
    year: 1999,
    url: "https://boxd.it/1Yzw",
    director: "",
    actors: [
      "Denzel Washington",
      "Angelina Jolie",
      "Queen Latifah",
      "Michael Rooker",
      "Michael McGlone",
      "Luis Guzmán",
      "Leland Orser",
      "John Benjamin Hickey",
      "Bobby Cannavale",
      "Ed O'Neill",
      "Richard Zeman",
      "Olivia Birkelund",
      "Gary Swanson",
      "James Bulleit",
      "Frank Fontaine",
      "Zena Grey",
      "Desmond Campbell",
      "Peter Michael Dillon",
      "Ted Whittall",
      "Andy Bradshaw",
      "Steve Adams",
      "Christian Veliz",
      "Mercedes Gómez",
      "Mary C. Hammett",
      "Amanda Gay",
      "Larry Day",
      "Burke Lawrence",
      "Terry Simpson",
      "Eric Davis",
      "Arthur Holden",
      "Yahsmin Daviault",
      "Keenan MacWilliam",
      "David Warshofsky",
      "Mateo Gómez",
      "Jonathan Stark",
      "Fulvio Cecere",
      "Hal Sherman",
      "Russell Yuen",
      "Jean-Marc Bisson",
      "Christopher Bregman",
      "Sonya Biddle",
    ],
  },
  {
    position: 15,
    name: "The Menu",
    year: 2022,
    url: "https://boxd.it/lScm",
    director: "",
    actors: [
      "Ralph Fiennes",
      "Anya Taylor-Joy",
      "Nicholas Hoult",
      "Hong Chau",
      "Janet McTeer",
      "Paul Adelstein",
      "John Leguizamo",
      "Aimee Carrero",
      "Reed Birney",
      "Judith Light",
      "Rebecca Koon",
      "Rob Yang",
      "Arturo Castro",
      "Mark St. Cyr",
      "Peter Grosz",
      "Christina Brucato",
      "Adam Aalderks",
      "Jon Paul Allyn",
      "Mel Fair",
      "Cristian Gonzalez",
      "Matthew Cornwell",
      "John Wilkins III",
      "John Cola",
      "Michael A. Dean",
      "Marcus Aveons Duncan",
      "Alexander Goldstein",
      "Grant Henley",
      "Brandon Herron",
      "Elbert Kim",
      "Melisa Lopez",
      "A. Jae Michele",
      "Jay Shadix",
      "Rachel Trautmann",
      "Victor Zheng",
    ],
  },
  {
    position: 16,
    name: "X",
    year: 2022,
    url: "https://boxd.it/sxVa",
    director: "",
    actors: [
      "Mia Goth",
      "Jenna Ortega",
      "Brittany Snow",
      "Kid Cudi",
      "Martin Henderson",
      "Owen Campbell",
      "Stephen Ure",
      "James Gaylyn",
      "Simon Prast",
      "Geoff Dolan",
      "Matthew J. Saville",
      "Bryony Skillington",
    ],
  },
  {
    position: 17,
    name: "Ready or Not",
    year: 2019,
    url: "https://boxd.it/kOf0",
    director: "",
    actors: [
      "Samara Weaving",
      "Adam Brody",
      "Mark O'Brien",
      "Henry Czerny",
      "Andie MacDowell",
      "Melanie Scrofano",
      "Kristian Bruun",
      "Elyse Levesque",
      "Nicky Guadagni",
      "John Ralston",
      "Liam MacDonald",
      "Ethan Tavares",
      "Hanneke Talbot",
      "Celine Tsai",
      "Daniela Barbosa",
      "Chase Churchill",
      "Etienne Kellici",
      "Andrew Anthony",
      "Elana Dunkelman",
      "Kate Ziegler",
      "James Eddy",
      "Adam Winlove-Smith",
      "Alicia Richardson",
      "Nat Faxon",
      "Guy Busick",
      "R. Christopher Murphy",
      "James Vanderbilt",
      "Emma Jonnz",
    ],
  },
  {
    position: 18,
    name: "The Marriage App",
    year: 2022,
    url: "https://boxd.it/zLxK",
    director: "",
    actors: [
      "Luisana Lopilato",
      "Juan Minujín",
      "Betiana Blum",
      "Andrea Rincón",
      "Cristina Castaño",
      "Santiago Gobernori",
      "Julián Lucero",
      "Aylen Malisani",
      "Vicente Archain",
      "Carla Pandolfi",
      "Javier Pedersoli",
      "Hernán Montenegro",
      "Paloma Contreras",
      "Laura Paredes",
      "Victoria García Garabal",
      "Jorge Takashima",
      "Miranda Johansen",
      "Juan Tupac Soler",
      "Betty Cossoy",
    ],
  },
  {
    position: 19,
    name: "Instant Family",
    year: 2018,
    url: "https://boxd.it/hHpQ",
    director: "",
    actors: [
      "Mark Wahlberg",
      "Rose Byrne",
      "Allyn Rachel",
      "Isabela Merced",
      "Julie Hagerty",
      "Tig Notaro",
      "Octavia Spencer",
      "Gustavo Escobar",
      "Margo Martindale",
      "Julianna Gamiz",
      "Tom Segura",
      "Michael O'Keefe",
      "Britt Rentschler",
      "Jody Thompson",
      "Iliza Shlesinger",
      "Gary Weeks",
      "Joy Jacobson",
      "Hampton Fluker",
      "Randy Havens",
      "Andrea Anders",
      "Kenneth Israel",
      "Joan Cusack",
      "Valente Rodriguez",
      "Carson Holmes",
      "Jaiden Byrd",
      "Connor Jones",
      "James Arthur Sims",
      "Rosemary Dominguez",
      "Javier Ronceros",
      "Eve Harlow",
      "Nicholas Logan",
      "Charlie McDermott",
      "Joselin Reyes",
      "Erika Bierman",
      "Sarah Kirkpatrick",
      "John McConnell",
      "Maureen Brennan",
      "Kelly Tippens",
      "Layla Felder",
      "Allen Zwolle",
      "Stella Doyle",
      "Andrene Ward-Hammond",
      "Denitra Isler",
      "Remy Ortiz",
      "William J. Simmons",
      "Anthony 'Ace' Thomas",
      "Candice Daniels",
      "Alexis Lord",
      "Perry Westberry",
      "Maegan McCarthy",
      "Jerry T. Richerson",
      "Caleb Pratt",
      "Cruze Lynnox Keith",
      "Billie Wilemon",
      "Jonathan Kobs",
      "Maria Wilson",
    ],
  },
  {
    position: 20,
    name: "Enola Holmes 2",
    year: 2022,
    url: "https://boxd.it/vfDe",
    director: "",
    actors: [
      "Millie Bobby Brown",
      "Henry Cavill",
      "Louis Partridge",
      "Helena Bonham Carter",
      "David Thewlis",
      "Susan Wokoma",
      "Adeel Akhtar",
      "Sharon Duncan-Brewster",
      "Hannah Dodd",
      "Abbie Hern",
      "Gabriel Tierney",
      "Serrana Su-Ling Bliss",
      "Róisín Monaghan",
      "David Westhead",
      "Sofia Stavrinou",
      "Himesh Patel",
      "Catriona Chandler",
      "Lee Boardman",
      "Tim McMullan",
      "Tony Lucken",
    ],
  },
  {
    position: 21,
    name: "Closer",
    year: 2004,
    url: "https://boxd.it/270K",
    director: "",
    actors: [
      "Julia Roberts",
      "Jude Law",
      "Natalie Portman",
      "Clive Owen",
      "Colin Stinton",
      "Nick Hobbs",
      "Steve Benham",
      "Elizabeth Bower",
      "Ray Donn",
      "Daniel Dresner",
      "Rrenford Junior Fagan",
      "Antony Gabriel",
      "Michael Haley",
      "Selena Mars",
      "Steve Morphew",
      "Peter Rnic",
      "Robert Stone",
      "Jacqui-Lee Pryce",
    ],
  },
  {
    position: 22,
    name: "Alive",
    year: 1993,
    url: "https://boxd.it/210u",
    director: "",
    actors: [
      "Ethan Hawke",
      "Vincent Spano",
      "Josh Hamilton",
      "Bruce Ramsay",
      "John Newton",
      "David Kriegel",
      "Kevin Breznahan",
      "Sam Behrens",
      "Illeana Douglas",
      "Jack Noseworthy",
      "Christian J. Meoli",
      "Jake Carpenter",
      "Michael DeLorenzo",
      "José Zúñiga",
      "Danny Nucci",
      "David Cubitt",
      "Gian DiDonna",
      "John Cassini",
      "Michael Woolson",
      "Chad Willett",
      "Richard Ian Cox",
      "Gordon Currie",
      "Ele Keats",
      "Josh Lucas",
      "Silvio Pollio",
      "Nuno Antunes",
      "Michael Tayles",
      "Steven Shayler",
      "Jason Gaffney",
      "Jerry Wasserman",
      "Michael Sicoly",
      "Diana Barrington",
      "Jan D'Arcy",
      "Frank Pellegrino",
      "Seth Arnett",
      "Aurelio Dinunzio",
      "Fiona Roeske",
      "Tony Morelli",
      "Pat Romano",
      "John Malkovich",
    ],
  },
  {
    position: 23,
    name: "The Pale Blue Eye",
    year: 2022,
    url: "https://boxd.it/u8tk",
    director: "",
    actors: [
      "Christian Bale",
      "Harry Melling",
      "Lucy Boynton",
      "Toby Jones",
      "Simon McBurney",
      "Timothy Spall",
      "Robert Duvall",
      "Harry Lawtey",
      "Gillian Anderson",
      "Charlotte Gainsbourg",
      "Hadley Robinson",
      "Fred Hechinger",
      "Joseph Brooks",
      "Steven Maier",
      "Brennan Keel Cook",
      "Orlagh Cassidy",
      "Scott G. Anderson",
      "Gideon Glick",
      "Jack Irving",
      "Matt Helm",
      "Mathias Goldstein",
      "Charlie Tahan",
      "Bill Cwikowski",
      "Agnes Herrmann",
      "Nicholas Bellavia",
    ],
  },
  {
    position: 24,
    name: "The Silence of the Sky",
    year: 2016,
    url: "https://boxd.it/ezJC",
    director: "",
    actors: [
      "Leonardo Sbaraglia",
      "Carolina Dieckmann",
      "Chino Darín",
      "Álvaro Armand Ugón",
      "Mirella Pascual",
      "Roberto Suárez",
      "Paula Cohen",
      "Dylan Cortes",
      "Priscila Bellora",
      "Gabriela Freire",
      "María Mendive",
      "Walter Rey",
      "Susana Groisman",
    ],
  },
  {
    position: 25,
    name: "RRR",
    year: 2022,
    url: "https://boxd.it/ljDs",
    director: "",
    actors: [
      "N. T. Rama Rao Jr.",
      "Ram Charan",
      "Olivia Morris",
      "Ray Stevenson",
      "Alison Doody",
      "Alia Bhatt",
      "Ajay Devgn",
      "Shriya Saran",
      "Edward Sonnenblick",
      "Makrand Deshpande",
      "Samuthirakani",
      "Chatrapathi Sekhar",
      "Rajiv Kanakala",
      "Rahul Ramakrishna",
      "Ahmareen Anjum",
      "Twinkle Sharma",
      "Varun Buddhadev",
      "Spandan Chaturvedi",
      "R. Bhakti Klein",
      "Mark Bennington",
      "Gaurav Pareek",
      "Alexx O'Nell",
      "S. S. Rajamouli",
      "Kirron Arya",
      "Akash Boro",
      "Eduard Buhac",
      "Narendra Singh Dhami",
      "Oleg Karpenko",
      "Ivan Kostadinov",
      "Jason Yeboa",
    ],
  },
  {
    position: 26,
    name: "Tales of an Immoral Couple",
    year: 2016,
    url: "https://boxd.it/duNW",
    director: "",
    actors: [
      "Cecilia Suárez",
      "Ximena Romo",
      "Manuel Garcia-Rulfo",
      "Mariana Treviño",
      "Paz Vega",
      "Sebastián Aguirre",
      "Juan Pablo Medina",
      "Andrés Almeida",
      "Natasha Dupeyrón",
      "Nina Rubín Legarreta",
      "Eréndira Ibarra",
      "Javier Jattin",
      "Nayeli Barajas",
      "Juan Pablo Castaneda",
      "Anilu Estevez",
      "Mayte Gil",
      "Francesco Roder",
      "Sofía Sisniega",
      "Valeria Vera",
    ],
  },
  {
    position: 27,
    name: "West Side Story",
    year: 2021,
    url: "https://boxd.it/iwt0",
    director: "",
    actors: [
      "Ansel Elgort",
      "Rachel Zegler",
      "Ariana DeBose",
      "David Alvarez",
      "Mike Faist",
      "Brian d'Arcy James",
      "Corey Stoll",
      "Rita Moreno",
      "Josh Andrés Rivera",
      "Ana Isabelle",
      "Ilda Mason",
      "iris menas",
      "Julius Anthony Rubio",
      "Tanairi Sade Vazquez",
      "David Aviles Morales",
      "Sebastian Serra",
      "Ricardo Zayas",
      "Ricky Ubeda",
      "Andrei Chagas",
      "Adriel Flete",
      "Jacob Guzman",
      "Kelvin Delgado",
      "Carlos Sánchez Falú",
      "Yurel Echezarreta",
      "David Guzman",
      "Sean Harrison Jones",
      "Jess LeProtto",
      "Patrick Higgins",
      "Kyle Allen",
      "John Michael Fiumara",
      "Kevin Csolak",
      "Kyle Coffman",
      "Ben Cook",
      "Harrison Coll",
      "Garett Hawe",
      "Myles Erlick",
      "Julian Elia",
      "Carlos E. Gonzalez",
      "Daniel Patrick Russell",
      "Yesenia Ayala",
      "Gabriela M. Soto",
      "Juliette Feliciano Ortiz",
      "Jeanette Delgado",
      "Maria Alexis Rodriguez",
      "Edriz E. Rosa Pérez",
      "Jennifer Florentino",
      "Melody Martí",
      "Gaby Diaz",
      "Isabella Ward",
      "Eloise Kropp",
      "Paloma Garcia-Lee",
      "Leigh-Ann Esty",
      "Lauren Leach",
      "Brittany Pollack",
      "Kellie Drobnick",
      "Skye Mattox",
      "Adriana Pierce",
      "Jonalyn Saxer",
      "Brianna Abruzzo",
      "Halli Toland",
      "Sara Esty",
      "Talia Ryder",
      "Maddie Ziegler",
      "Andrea Burns",
      "Mike Iveson",
      "Jamila Velazquez",
      "Annelise Cepero",
      "Yassmin Alers",
      "Jamie Harris",
      "Curtiss Cook",
      "Nadia Quinn",
      "Arianna Rosario",
      "Natalie Toro",
      "María Alejandra Castillo",
      "Mannelly Gonzalez Abreu",
      "Maya Haghighi Guliani",
      "Tyler Myers",
      "Jesseudi Marcelino",
      "German M. Castillo",
      "Ciara Calderon",
      "Aubrey Mills",
      "Leonardo Ro",
      "Adrian Castillo",
      "Luke Joseph Fuentes Duculan",
      "Abigail R. Valdez",
      "Navio Lopez",
      "Victor Cruz",
      "Erik Charlston",
      "Clint de Ganon",
      "Dave Phillips",
      "Silvano Monasterios",
      "Ric Molina",
      "Dan Pearson",
      "Hommy Ramos",
      "Jose Ruiz",
      "Jumaane Smith",
      "Dave Noland",
      "Roland Morales",
      "Javier Diaz",
      "Chryssie Whitehead",
      "Ron Stroman",
      "Rene Ojeda",
      "Feiga Martinez",
      "Mike Massimino",
      "Ryan Woodle",
      "David Bean",
      "Bert Michaels",
      "Joe Lanza",
      "Savannah Renée Rodriguez",
      "Denia Brache",
      "Lesley Bilingslea",
      "Andy Powers",
      "Reginald L. Barnes",
      "Patrick Noonan",
      "Jeff Ward",
      "Pablo Thomas",
      "Paul Niebanck",
      "Ixchel Cuellar",
      "Ricky Garcia",
      "Oscar Antonio Rodriguez",
      "José Ramón Rosario",
      "Doreen Montalvo",
      "Shade Rupe",
    ],
  },
  {
    position: 28,
    name: "Death on the Nile",
    year: 2022,
    url: "https://boxd.it/ifpg",
    director: "",
    actors: [
      "Kenneth Branagh",
      "Gal Gadot",
      "Armie Hammer",
      "Emma Mackey",
      "Tom Bateman",
      "Letitia Wright",
      "Sophie Okonedo",
      "Annette Bening",
      "Russell Brand",
      "Rose Leslie",
      "Jennifer Saunders",
      "Dawn French",
      "Ali Fazal",
      "Michael Rouse",
      "Alaa Safi",
      "Orlando Seale",
      "Charlie Anson",
      "Danny Hughes",
      "Sam James Page",
      "James Schofield",
      "George Jaques",
      "Jonah Rzeskiewicz",
      "Eleanor de Rohan",
      "Susannah Fielding",
      "Adam Garcia",
      "Noel White",
      "Niamh Lynch",
      "Rosie Dwyer",
      "Nari Blair-Mangat",
      "Sid Sagar",
      "Brenda-Jane Newhouse",
      "Rhiannon Clements",
      "Daniel Cook",
      "Heider Ali",
      "Hayat Kamille",
      "Crispin Letts",
      "Victor Alli",
      "Rachel Feeney",
      "Sarah Eve",
      "Aron Julius",
      "Francis Lovehall",
      "Stacy Abalogun",
      "Naveed Khan",
      "Katie Smale",
      "Kemi Awoderu",
      "Lauren Alexandra",
      "Nikkita Chadha",
      "Nadine Leon Gobet",
      "Rick Warden",
    ],
  },
  {
    position: 29,
    name: "Death Proof",
    year: 2007,
    url: "https://boxd.it/27GG",
    director: "",
    actors: [
      "Kurt Russell",
      "Zoë Bell",
      "Rosario Dawson",
      "Vanessa Ferlito",
      "Sydney Tamiia Poitier",
      "Tracie Thoms",
      "Rose McGowan",
      "Jordan Ladd",
      "Mary Elizabeth Winstead",
      "Quentin Tarantino",
      "Marcy Harriell",
      "Eli Roth",
      "Omar Doom",
      "Michael Bacall",
      "Monica Staggs",
      "Jonathan Loughran",
      "Michael Parks",
      "James Parks",
      "Marley Shelton",
      "Helen Kim",
      "Tina Rodriguez",
      "Nicky Katt",
      "Marta Mendoza",
      "Tim Murphy",
      "Melissa Arcaro",
      "Electra Avellan",
      "Elise Avellan",
      "Eurlyne Epper",
      "Jamie L. Dunno",
      "Chris King",
      "April March",
      "Julitta Pourciau",
      "Amanda Rivas",
      "Kelley Robins Hicks",
      "Gary Teague",
      "Tommy Nix",
    ],
  },
  {
    position: 30,
    name: "Trial by Fire",
    year: 2018,
    url: "https://boxd.it/hjMw",
    director: "",
    actors: [
      "Jack O'Connell",
      "Laura Dern",
      "Emily Meade",
      "Jade Pettyjohn",
      "Rhoda Griffis",
      "Blair Bomar",
      "McKinley Belcher III",
      "Catherine Carlen",
      "Noah Lomax",
      "Whitney Goin",
      "Anthony Reynolds",
      "Blake Lewis",
      "Jeff Perry",
      "Chris Coy",
      "Wayne Pére",
      "Carlos Gómez",
      "Carrie Walrond Hood",
      "Elle Graham",
      "Jason Douglas",
      "Katie McClellan",
      "Cara Reid",
      "Andy Stahl",
      "Sonny Carl Davis",
      "David Wilson Barnes",
      "Darren Pettie",
      "Lena Levings",
      "Mary Rachel Dudley",
      "Josh Breslow",
      "Russ Tiller",
      "Chris Shurley",
      "Lindsay Ayliffe",
    ],
  },
  {
    position: 31,
    name: "Talk to Her",
    year: 2002,
    url: "https://boxd.it/2beG",
    director: "",
    actors: [
      "Leonor Watling",
      "Rosario Flores",
      "Javier Cámara",
      "Darío Grandinetti",
      "Mariola Fuentes",
      "Geraldine Chaplin",
      "Pina Bausch",
      "Malou Airaudo",
      "Caetano Veloso",
      "Roberto Álvarez",
      "Elena Anaya",
      "Lola Dueñas",
      "Adolfo Fernández",
      "Ana Fernández",
      "Chus Lampreave",
      "Helio Pedregal",
      "Paz Vega",
      "Fele Martínez",
      "Carmen Machi",
      "Agustín Almodóvar",
      "Carlos García Cambero",
      "Esther García",
      "Lola García",
      "Fernando Iglesias",
    ],
  },
  {
    position: 32,
    name: "Planet Terror",
    year: 2007,
    url: "https://boxd.it/27Gw",
    director: "",
    actors: [
      "Rose McGowan",
      "Freddy Rodríguez",
      "Josh Brolin",
      "Marley Shelton",
      "Jeff Fahey",
      "Michael Biehn",
      "Bruce Willis",
      "Naveen Andrews",
      "Rebel Rodriguez",
      "Julio Oscar Mechoso",
      "Fergie",
      "Nicky Katt",
      "Tom Savini",
      "Carlos Gallardo",
      "Tommy Nix",
      "Michael Parks",
      "Quentin Tarantino",
      "Electra Avellan",
      "Elise Avellan",
      "Felix Sabates",
      "Jason Douglas",
      "Troy Robinson",
      "Zoë Bell",
      "Danny Trejo",
      "Cheech Marin",
      "Corey Burton",
      "Emmy Robbin",
      "Derek Southers",
      "Robert Rodriguez",
    ],
  },
  {
    position: 33,
    name: "Triangle of Sadness",
    year: 2022,
    url: "https://boxd.it/hXlq",
    director: "",
    actors: [
      "Harris Dickinson",
      "Charlbi Dean",
      "Dolly de Leon",
      "Zlatko Burić",
      "Iris Berben",
      "Vicki Berlin",
      "Henrik Dorsin",
      "Woody Harrelson",
      "Jean-Christophe Folly",
      "Amanda Walker",
      "Oliver Ford Davies",
      "Sunnyi Melles",
      "Thobias Thorwid",
      "Jiannis Moustos",
      "Timoleon Gketsos",
      "Alicia Eriksson",
      "Carolina Gynning",
      "Ralph Schicha",
      "Arvin Kananian",
      "Mia Benson",
      "Stefan Gödicke",
      "Nana Manu",
      "Fredrik Quinones",
      "Filip Roséen",
      "Chidiegwu Chidi",
      "Charlie Westerberg",
      "Erik Andersson",
      "Hamlet Talje Willoughby",
      "Victor Köhler",
      "Daniel Estehghari",
      "Alfons Miari",
      "Isak Barrow",
      "Alexander Virenhem",
      "Malte Gårdinger",
      "Alfred Lindström",
      "Augustine Kajue",
      "William-Patrik Molvén",
      "Florand Kaufeldt",
      "Theodor Öhrn",
      "Jin Zou",
      "David Alexanderson",
      "Olof Källström",
      "Julian Redaelli",
      "Egil Ahlenius",
      "Carl Jood",
      "Chand Smith",
      "Malick Afocozi",
      "Ludvig Fast",
      "Victor Norlander",
      "Anton Isaksson",
      "Brian Kamara",
      "Eric Svirins",
      "Hugo Palm",
      "Simon Bredenberg",
      "Noa Del Castillo Hallberg",
      "Ann-Sofi Back",
      "Robert Rydberg",
      "Robert Nordberg",
      "Charlotte Brattin",
      "Mira Uszkureit",
      "Alex Schulman",
      "Amanda Schulman",
      "Emma Warg",
      "Camilla Läckberg",
      "Christina Saliba",
      "Karin Myrenberg Faber",
      "Linnea Olsson",
      "Asta Stensson",
      "Elsa Sjökvist",
      "Johanna Ovelius",
      "Shaniaz Hama Ali",
      "Catrin Nilsson",
      "Jacob Papinniemi",
      "Mimmi Brundin",
      "Melodie Von Sass",
      "Ellen Dixdotter",
      "Sofia Lücke",
      "Ronja Kruus",
      "Chris Westerstrom",
      "Hedda Rehnberg",
      "Robert Martufi",
      "Hanna Oldenburg",
      "Arnella Zetterström",
      "Sepideh Mazloom",
      "Eric Dernsjö",
      "Nikolas Drosopoulos",
      "Chrysanthi Theodosi",
      "Maria Alexiou",
      "Marilena Lampropoulou",
      "Christos Ntoulas",
      "Nikolas Chalkiadakis",
      "Grace Milaszewski",
      "Melina Marksaitis",
      "Theresa Johannesson",
      "Leocilyn Capanas",
      "Nanette Lipponen",
      "Maria Danica Herrera",
      "Maria Grace Concepcion",
      "Kristin Delfinado",
      "Shanilou Del Mundo",
      "John Michael Yadao",
      "Freedom Ziad Ahmed",
      "Robert Jomar",
      "Garry Villador Deveratturda",
      "Christopher Janiola",
      "Mario Rowen Bugtai",
      "Mohamed Lachras",
      "Taye Nathanail",
      "Athanasios Papaioannou",
      "Alexandros Sargologos",
      "Allen Bandiola",
      "Nicolas Refin",
      "Lontoc Rolyn",
      "John Paul Paugio",
      "John Paulo",
      "Anne Brocklin Bergman",
      "Johnny Bergman",
      "Fredrik Wikingsson",
      "Henrik Thott",
      "Thomas Peteus",
      "Magnus Jeansson",
      "Stefan Martikainen",
      "Britt-Marie Svensson",
      "Arash Raoufi",
      "Nafiseh Hadizadeh",
      "Inga Hahn",
      "Lennart Hahn",
      "Linda Anborg",
      "Karina Baldock Wiking",
      "Olof Myhrman",
      "Rebecca Fager",
      "Hilde Fager",
      "Emmylou Saguindel-Holmé",
      "Ann-Marie Eriksson",
      "Pål Svensson",
      "Giorgos Kyriakopoulos",
      "Pavlos Laoutaris",
      "Eva Koroli",
      "Alexia Mpogdanou",
      "Giannis Papathymios",
      "Achilles Vatrikas",
      "Gianna Andritsaki",
      "Dauda Coneth",
      "Beh Solo Kone",
      "Yussif Zakaria",
      "Papa Cheik Jade",
    ],
  },
  {
    position: 34,
    name: "A Beautiful Day in the Neighborhood",
    year: 2019,
    url: "https://boxd.it/i7vA",
    director: "",
    actors: [
      "Matthew Rhys",
      "Tom Hanks",
      "Chris Cooper",
      "Susan Kelechi Watson",
      "Maryann Plunkett",
      "Enrico Colantoni",
      "Wendy Makkena",
      "Tammy Blanchard",
      "Noah Harpster",
      "Carmen Cusack",
      "Kelley Davis",
      "Christine Lahti",
      "Maddie Corman",
      "Daniel Krell",
      "Jon L Peacock",
      "Gretchen Koerner",
      "Gavin Borders",
      "Mark August",
      "Tressa Glover",
      "Jessica Hecht",
      "Di Zhu",
      "Diane Monroe",
      "Maxine Roach",
      "Lesa Terry",
      "Tahirah Whittington",
      "Nigel Swinson",
      "Kayla Fan",
      "Alexander Ment",
      "Madeline Ment",
      "Olivia Irene Ruiz",
      "Kiesse Yengo-Passy",
      "Marcel Kottmann",
      "John Castagliola",
      "Preston Lopez",
      "Reginald Bannerman",
      "Spencer Lott",
      "Haley Jenkins",
      "Marc Petrosino",
      "Kathleen Kim",
      "Kathleen Antonia",
      "Saira Awan",
      "Krizia Bajos",
      "Tom Bonello",
      "Gregory Bromfield",
      "Francesca Calo",
      "Kitty Crystal",
      "Amy Lyn Elliott",
      "Joe Fishel",
      "Nate Heller",
      "Bill Isler",
      "Kevin L. Johnson",
      "Rosie Koster",
      "Michael Masini",
      "Kirsten McCain",
      "Patrick McDade",
      "David Newell",
      "Trevor Stevie Ray Ontiveros",
      "Keith Otto",
      "Khary Payton",
      "Alex Perez",
      "Katrina E. Perkins",
      "Jivan Xander Ramesh",
      "Scott Rapp",
      "Fred Rogers",
      "Joanne Rogers",
      "Edlyn Sabrina",
      "Erika Shrout",
      "Laura Faye Smith",
      "Rebecca Watson",
      "Stephen West-Rogers",
      "Ted Williams",
    ],
  },
  {
    position: 35,
    name: "BARDO, False Chronicle of a Handful of Truths",
    year: 2022,
    url: "https://boxd.it/pAgy",
    director: "",
    actors: [
      "Daniel Giménez Cacho",
      "Griselda Siciliani",
      "Íker Sánchez Solano",
      "Ximena Lamadrid",
      "Luz Jiménez",
      "Luis Couturier",
      "Francisco Rubio",
      "Andrés Almeida",
      "Clementina Guadarrama",
      "Jay O. Sanders",
      "Noé Hernández",
      "Fabiola Guajardo",
      "Mar Carrera",
      "Rubén Zamora",
      "Omar Leyva",
      "Grace Shen",
      "Edison Ruiz",
      "Daniel Damuzi",
      "Alex Guevara",
      "Misha Arias De La Cantolla",
      "Jorge Gidi",
      "Jeronimo Guerra",
      "Hugo Albores",
      "Grantham Coleman",
      "Luis Gnecco",
      "Alejandro Belmonte",
    ],
  },
  {
    position: 36,
    name: "Guillermo del Toro's Pinocchio",
    year: 2022,
    url: "https://boxd.it/kjMW",
    director: "",
    actors: [
      "Gregory Mann",
      "Ewan McGregor",
      "David Bradley",
      "Christoph Waltz",
      "Tilda Swinton",
      "Ron Perlman",
      "Finn Wolfhard",
      "Cate Blanchett",
      "Tim Blake Nelson",
      "John Turturro",
      "Burn Gorman",
      "Tom Kenny",
      "Alfie Tempest",
      "Anthea Greco",
      "Francesca Fanti",
      "Sandro Carotti",
      "Rio Mangini",
      "Benjamin Valic",
      "Sky Alexis",
      "Ariana Molkara",
      "Roy Halo",
      "Luciano Palmeri",
      "Peter Arpesella",
    ],
  },
  {
    position: 37,
    name: "Marcel the Shell with Shoes On",
    year: 2021,
    url: "https://boxd.it/wMAk",
    director: "",
    actors: [
      "Jenny Slate",
      "Dean Fleischer Camp",
      "Isabella Rossellini",
      "Thomas Mann",
      "Rosa Salazar",
      "Lesley Stahl",
      "Nathan Fielder",
      "Andy Richter",
      "Sarah Thyre",
      "Jessi Klein",
      "Peter Bonerz",
      "Conan O'Brien",
      "Shari Finkelstein",
      "Brian Williams",
    ],
  },
  {
    position: 38,
    name: "Van Helsing",
    year: 2004,
    url: "https://boxd.it/21aa",
    director: "",
    actors: [
      "Hugh Jackman",
      "Kate Beckinsale",
      "Richard Roxburgh",
      "David Wenham",
      "Shuler Hensley",
      "Elena Anaya",
      "Will Kemp",
      "Kevin J. O'Connor",
      "Alun Armstrong",
      "Silvia Colloca",
      "Josie Maran",
      "Tom Fisher",
      "Samuel West",
      "Robbie Coltrane",
      "Stephen Fisher",
      "Dana Morávková",
      "Zuzana Ďurdinová",
      "Jaroslav Vízner",
      "Marek Vašut",
      "Samantha Sommers",
      "Dorel Mois",
      "Marianna Mois",
      "Laurence Racine",
      "Patrice Wojciechowski",
      "Kacie Borrowman",
      "Martin Klebba",
      "Ryan James",
    ],
  },
  {
    position: 39,
    name: "You People",
    year: 2023,
    url: "https://boxd.it/wJYe",
    director: "",
    actors: [
      "Jonah Hill",
      "Lauren London",
      "Eddie Murphy",
      "Julia Louis-Dreyfus",
      "Sam Jay",
      "Nia Long",
      "Travis Bennett",
      "David Duchovny",
      "Molly Gordon",
      "Deon Cole",
      "Andrea Savage",
      "Elliott Gould",
      "Rhea Perlman",
      "Mike Epps",
      "La La Anthony",
      "Yung Miami",
      "Khadijah Haqq McCray",
      "Bryan Greenberg",
      "Jordan Firstman",
      "Andrew Schulz",
      "Matt Walsh",
      "Emily Arlook",
      "Hal Linden",
      "Winnie Holzman",
      "Richard Benjamin",
      "Doug Hall",
      "Anthony Anderson",
      "Malik S.",
      "Ian Sargent Phillips",
      "Ahmad Dugas",
      "Nelson Franklin",
      "Rob Huebel",
      "Murray Gray",
      "Felipe Esparza",
      "Kym Whitley",
      "Doris Hancox",
      "Romy Reiner",
      "Marla Garlin",
      "Marcus Mullins",
      "Kash Abdulmalik",
      "Emily G. Miller",
      "Reese Levine",
      "Alana Jackson",
      "Amy Bernstein",
      "Todd Shotz",
      "Chayim Frenkel",
      "DJ Drama",
      "Kenya Barris",
      "Robert Diago DoQui",
      "Chinyere Dobson",
      "Pason",
    ],
  },
  {
    position: 40,
    name: "Porco Rosso",
    year: 1992,
    url: "https://boxd.it/1Tp2",
    director: "",
    actors: [
      "Shûichirô Moriyama",
      "Tokiko Katô",
      "Bunshi Katsura",
      "Tsunehiko Kamijô",
      "Akemi Okamura",
      "Akio Otsuka",
      "Hiroko Seki",
      "Reizō Nomoto",
      "Osamu Saka",
      "Yû Shimaka",
      "Mahito Tsujimura",
      "Minoru Yada",
      "Yoko Soumi",
    ],
  },
  {
    position: 41,
    name: "42",
    year: 2013,
    url: "https://boxd.it/3GBo",
    director: "",
    actors: [
      "Chadwick Boseman",
      "Harrison Ford",
      "Nicole Beharie",
      "Christopher Meloni",
      "Ryan Merriman",
      "Lucas Black",
      "André Holland",
      "Alan Tudyk",
      "Hamish Linklater",
      "T.R. Knight",
      "John C. McGinley",
      "Toby Huss",
      "Max Gail",
      "Brad Beyer",
      "James Pickens Jr.",
      "Gino Anthony Pesi",
      "Brett Cullen",
      "Jesse Luken",
      "Jamey Holliday",
      "Derek Phillips",
      "Jamie Ruehling",
      "Blake Sanders",
      "Johnny Knight",
      "Clint O'Brien",
      "Dusan Brown",
      "Cherise Boothe",
      "Friedel Pinkston",
      "Linc Hand",
      "Thomas Helgeland",
      "Matt Clark",
      "Peter MacKenzie",
      "Joe Inscoe",
      "Monnae Michaell",
      "Karole Foreman",
      "C.J. Nitkowski",
      "Scott Callaway",
      "James Rackley",
      "Aaron Farb",
      "Anthony S. Goolsby",
      "Lou Criscuolo",
      "Ross Hughes",
      "Joe Knezevich",
      "Mark Harelik",
      "Kenny Cook",
      "David Sweeney",
      "Rhoda Griffis",
      "Daniel Fenlon",
      "Maury Covington",
      "Henry Friedman",
      "Holden Hansen",
      "Dan Mengini",
      "Jon Kohler",
      "Marc Gowan",
      "Jackson Walker",
      "Danny Vinson",
      "Ari Blinder",
      "William Flaman",
      "Denise Moyé",
      "Peter Jurasik",
      "Michael H. Cole",
      "Janet Metzger",
      "Dax Griffin",
      "Jayson Warner Smith",
      "Jeremy Ray Taylor",
      "Christopher Harvey",
      "Kelley Jakle",
      "Jud Tylor",
      "Tobias Michael Finn",
      "Ercell A. Grimes Jr.",
      "Dwight Houser",
      "Barry Suttle",
      "Andrew B. Roberts",
      "Jimmie L. Coleman",
      "Steve Hicks",
      "Wayne Hickey",
      "Andrew C. Mullins",
      "Dennis A. Spears",
      "Gary Miller",
      "Todd Wilson",
      "David Thoms",
      "Richard Tavernaro",
      "Hunter Clowdus",
    ],
  },
  {
    position: 42,
    name: "Spiderhead",
    year: 2022,
    url: "https://boxd.it/mLsO",
    director: "",
    actors: [
      "Chris Hemsworth",
      "Miles Teller",
      "Jurnee Smollett",
      "Mark Paguio",
      "Tess Haubrich",
      "BeBe Bettencourt",
      "Nathan Jones",
      "Angie Miliken",
      "Ron Smyck",
      "Joey Vieira",
      "Sam Delich",
      "Daniel Reader",
      "Stephen Tongun",
    ],
  },
  {
    position: 43,
    name: "Emma.",
    year: 2020,
    url: "https://boxd.it/kmg0",
    director: "",
    actors: [
      "Anya Taylor-Joy",
      "Johnny Flynn",
      "Josh O'Connor",
      "Callum Turner",
      "Mia Goth",
      "Miranda Hart",
      "Bill Nighy",
      "Rupert Graves",
      "Gemma Whelan",
      "Amber Anderson",
      "Tanya Reynolds",
      "Connor Swindells",
      "Angus Imrie",
      "Letty Thomas",
      "Aidan White",
      "Edward Davis",
      "Chris White",
      "Myra McFadyen",
      "Esther Coles",
      "Suzy Bloom",
      "Suzie Toase",
      "Nicholas Burns",
      "Connor Dalton",
      "Lucy Briers",
      "Anna Francolini",
      "Christopher Godwin",
      "Vanessa Owen",
      "Isis Hainsworth",
      "Hannah Stokely",
      "Charlotte Weston",
      "Max Toovey",
      "Cecelia Jacob",
      "Cody Gipson",
      "Tabitha Coop",
      "Juno Coop",
      "Chloe Pirrie",
      "Oliver Chris",
      "Rose Shalloo",
      "Janine Craig",
      "Cris Penfold",
      "Nike Van Shie",
      "Leigh Daniels",
      "Alastair Postlethwaite",
      "Shaun Walters",
      "Zachary Trevitt",
      "Philippe Barnes",
      "Alexis Bennett",
      "Giles Lewin",
      "Edmund George Taylor",
      "Joe Zeitlin",
    ],
  },
  {
    position: 44,
    name: "Legion of Super-Heroes",
    year: 2023,
    url: "https://boxd.it/BW1O",
    director: "",
    actors: [
      "Meg Donnelly",
      "Harry Shum Jr.",
      "Darren Criss",
      "Jensen Ackles",
      "Matt Bomer",
      "Cynthia Hamidi",
      "Yuri Lowenthal",
      "Gideon Adlon",
      "Ely Henry",
      "Darin De Paul",
      "Robbie Daymond",
      "Eric Lopez",
      "Ben Diskin",
      "Victoria Grace",
      "Jennifer Hale",
      "Daisy Lightfoot",
      "Zeno Robinson",
    ],
  },
  {
    position: 45,
    name: "Robin Hood",
    year: 2010,
    url: "https://boxd.it/1D6o",
    director: "",
    actors: [
      "Russell Crowe",
      "Cate Blanchett",
      "Max von Sydow",
      "William Hurt",
      "Mark Strong",
      "Oscar Isaac",
      "Danny Huston",
      "Eileen Atkins",
      "Mark Addy",
      "Matthew Macfadyen",
      "Kevin Durand",
      "Scott Grimes",
      "Alan Doyle",
      "Douglas Hodge",
      "Léa Seydoux",
      "Jonathan Zaccaï",
      "Robert Pugh",
      "Gerard McSorley",
      "Velibor Topic",
      "Ciaran Flynn",
      "Simon McBurney",
      "Denise Gough",
      "John Nicholas",
      "Thomas Arnold",
      "Pip Carter",
      "Mark Lewis Jones",
      "Bronson Webb",
      "Denis Ménochet",
      "Jamie Beamish",
      "John Atterbury",
      "Luke Evans",
      "Roy Holder",
      "Mark Ryder",
      "Ruby Bentall",
      "Ned Dennehy",
      "Nicolas Simon",
      "Lisa Millett",
      "Stuart Martin",
      "Jessica Raine",
      "Steve Evets",
      "Eric Rulliat",
      "Abraham Belaga",
      "Jack Downham",
      "Richard Riddell",
      "David Bertrand",
      "Arthur Darvill",
      "Giannina Facio",
      "Hannah Barrie",
      "Lee Battle",
      "Nicky Bell",
      "Andrea Ware",
      "John O'Toole",
      "Ralph Ineson",
      "Zuriel de Peslouan",
      "Jake Curran",
      "Samuel Dupuy",
      "Nick Lucas",
      "Alan Charlesworth",
      "Lothaire Gerard",
      "Mat Laroche",
      "Chris Jared",
      "Joseph Hamilton",
      "James Hamilton",
      "James Burrows",
      "Danny Clarke",
      "Tom Blyth",
      "Lee Nicholas Harris",
      "Michael Koltes",
      "Umit Ulgen",
      "Robert J. Fraser",
      "Ryan Stuart",
      "Harvey Walsh",
      "Will Richardson",
    ],
  },
  {
    position: 46,
    name: "The Sea Beast",
    year: 2022,
    url: "https://boxd.it/kv3a",
    director: "",
    actors: [
      "Karl Urban",
      "Zaris-Angel Hator",
      "Jared Harris",
      "Marianne Jean-Baptiste",
      "Benjamin Plessala",
      "Somali Rose",
      "Kaya McLean",
      "Davis Pak",
      "Helen Sadler",
      "Xana Tang",
      "Alex Wyndham",
      "Brian T. Delaney",
      "Ian Mercer",
      "Shannon Chan-Kent",
      "Max Mittelman",
      "Paul Chowdhry",
      "Jim Carter",
      "Doon Mackichan",
      "Dan Stevens",
      "Rajia Baroudi",
      "Kathy Burke",
      "Emily O'Brien",
      "David S. Lee",
    ],
  },
  {
    position: 47,
    name: "Green Lantern: Beware My Power",
    year: 2022,
    url: "https://boxd.it/xvNy",
    director: "",
    actors: [
      "Aldis Hodge",
      "Jimmi Simpson",
      "Ike Amadi",
      "Brian Bloom",
      "Jamie Gray Hyder",
      "Mara Junot",
      "Jason J. Lewis",
      "Sunil Malhotra",
      "Nolan North",
      "Keesha Sharp",
      "Simon Templeman",
      "Rick D. Wasserman",
    ],
  },
  {
    position: 48,
    name: "The Gift",
    year: 2000,
    url: "https://boxd.it/27ys",
    director: "",
    actors: [
      "Cate Blanchett",
      "Giovanni Ribisi",
      "Keanu Reeves",
      "Katie Holmes",
      "Greg Kinnear",
      "Hilary Swank",
      "Michael Jeter",
      "Kim Dickens",
      "Gary Cole",
      "Rosemary Harris",
      "J.K. Simmons",
      "Chelcie Ross",
      "John Beasley",
      "Lynnsee Provence",
      "Hunter McGilvray",
      "Nathan Lee Lewis",
      "Benjamin Peacock",
      "Alex Lee",
      "Clay James",
      "David Brannen",
      "Russell Durham Comegys",
      "Janell McLeod",
      "Robby Preddy",
      "Lucky Lawrence",
      "Mo",
      "Boots Kutz",
      "Buck Edwards",
      "D.J. Pawlak",
      "Kipp Chambers",
      "Dallas Johnson",
      "Stuart Greer",
      "Jeff Bragg",
      "Danny Elfman",
      "S.D. Stephens",
      "Samuel E. Parlin Jr.",
      "Ed Reddick",
      "Rebecca Koon",
      "Erik Cord",
      "Yvetta Young",
      "Sam Edens",
      "Earl Maddox",
      "Shawn McBride",
      "Ray Wineteer",
    ],
  },
  {
    position: 49,
    name: "The Hunt",
    year: 2012,
    url: "https://boxd.it/3wEC",
    director: "",
    actors: [
      "Mads Mikkelsen",
      "Thomas Bo Larsen",
      "Annika Wedderkopp",
      "Lasse Fogelstrøm",
      "Susse Wold",
      "Anne Louise Hassing",
      "Lars Ranthe",
      "Alexandra Rapaport",
      "Sebastian Bull Sarning",
      "Steen Ordell Guldbrandsen",
      "Daniel Engstrup",
      "Troels Thorsen",
      "Søren Rønholt",
      "Hana Shuan",
      "Jytte Kvinesdal",
      "Josefine Gråbøl",
      "Bjarne Henriksen",
      "Nicolai Dahl Hamilton",
      "Øyvind Hagen-Traberg",
      "Allan Wibor Christensen",
      "Rikke Bergmann",
      "Rasmus Lind Rubin",
      "Frank Rubæk",
      "Jacob Højlev Jørgensen",
      "Nina Christrup",
      "Birgit Petersen",
      "Karina Fogh Holmkjær",
      "Heidi Gross",
      "Marie Aktor",
      "Mona C. Soliman",
      "Mie Ravn Nielsen",
      "Kim Westi Rasmussen",
      "Thomas Ravn",
      "Katrine Brygmann",
      "Ole Dupont",
    ],
  },
  {
    position: 50,
    name: "The Widows of Thursdays",
    year: 2009,
    url: "https://boxd.it/16sm",
    director: "",
    actors: [
      "Ernesto Alterio",
      "Juan Diego Botto",
      "Gloria Carrá",
      "Ana Celentano",
      "Camilo Cuello Vitale",
      "Pablo Echarri",
      "Adrián Navarro",
      "Leonardo Sbaraglia",
      "Vera Spinetta",
      "Gabriela Toscano",
      "Juana Viale",
      "Elena Gowland",
    ],
  },
  {
    position: 51,
    name: "Ant-Man and the Wasp: Quantumania",
    year: 2023,
    url: "https://boxd.it/nL2y",
    director: "",
    actors: [
      "Paul Rudd",
      "Evangeline Lilly",
      "Jonathan Majors",
      "Kathryn Newton",
      "Michelle Pfeiffer",
      "Michael Douglas",
      "Corey Stoll",
      "Bill Murray",
      "William Jackson Harper",
      "David Dastmalchian",
      "Jamie Andrew Cutler",
      "Katy O'Brian",
      "Mark Weinman",
      "Randall Park",
      "Ross Mullan",
      "Tom Clark",
      "Leon Cooke",
      "Nathan Blees",
      "Durassie Kiangangu",
      "Liran Nathan",
      "Sam Symons",
      "Grahame Fox",
      "Nicola Peluso",
      "Harrison Daniels",
      "Brahmdeo Shannon Ramana",
      "Russell Balogh",
      "Leonardo Taiwo",
      "Osian Roberts",
      "Lucas Gerstel",
      "Mia Gerstel",
      "Tracy Jeffrey",
      "Dinah Jeffrey",
      "Judy Jeffrey",
      "John Nayagam",
      "Greta Nayagam",
      "Cathy Chan",
      "Adam Sai",
      "Jamie Sai",
      "Jakari Fraser",
      "Patricia Belcher",
      "Mark Oliver Everett",
      "Ruben Rabasa",
      "Melanie Garcia",
      "Gregg Turkington",
      "Sierra Katow",
      "Ryan Bergara",
      "Marielle Scott",
      "Jake Millgard",
      "Dey Young",
      "Briza Covarrubias",
      "Tess Aubert",
      "David J. Castillo",
      "Sir Cornwell",
      "Alan Heitz",
      "Esther McAuley",
      "Aisling Maria Andreica",
      "Milton Lopes",
      "Roger Craig Smith",
      "Matthew Wood",
      "Loveday Smith",
      "John Townsend",
      "Tom Scharpling",
      "Tom Hiddleston",
      "Owen Wilson",
      "Abby Ryder Fortson",
    ],
  },
  {
    position: 52,
    name: "The Sum of All Fears",
    year: 2002,
    url: "https://boxd.it/242I",
    director: "",
    actors: [
      "Ben Affleck",
      "Morgan Freeman",
      "James Cromwell",
      "Liev Schreiber",
      "Bridget Moynahan",
      "Alan Bates",
      "Ciarán Hinds",
      "Philip Baker Hall",
      "Ron Rifkin",
      "Bruce McGill",
      "Colm Feore",
      "Josef Sommer",
      "Ken Jenkins",
      "Michael Byrne",
      "John Beasley",
      "Jamie Harrold",
      "Ian Mongrain",
      "Russell Bobbitt",
      "Al Vandecruys",
      "Richard Cohee",
      "Philip Pretten",
      "Alison Darcy",
      "Richard Marner",
      "Ostap Soroka",
      "Robert Martin Robinson",
      "Dale Godboldo",
      "Lee Garlington",
      "Stefan Kalipha",
      "Nabil Elouahabi",
      "Maria Monakhova",
      "Francois Bryon",
      "Pragna Desai",
      "Michel 'Gish' Abou-Samah",
      "Edward Zinoviev",
      "Sheena Larkin",
      "Frank Fontaine",
      "Andre Cornellier",
      "Maxime Opadtchii",
      "Mariusz Sibiga",
      "Norm Berketa",
      "Lev Prygunov",
      "Mace Neufeld",
      "Jennifer Seguin",
      "Josh Kimmel",
      "Evgeniy Lazarev",
      "Sven-Ole Thorsen",
      "Heinar Piller",
      "Arthur Holden",
      "Marcel Sabourin",
      "Vie Nystrom",
      "Joel Bissonnette",
      "Kwasi Songui",
      "Marina Lapina",
      "Victoria Reuter",
      "France Arbour",
      "Lubomir Mykytiuk",
      "Vladimir Radian",
      "Hryhoriy Hlady",
      "Valeri Koudriavtsev",
      "Victor Pedtrchenko",
      "Willie Gault",
      "Gary Gelfand",
      "Arnold McCuller",
      "Craig Hosking",
      "Jerry Markbreit",
      "John Eaves",
      "J.J. Carle",
      "David Vazquez",
      "David Schaap",
      "LisaGay Hamilton",
      "Kirk Taylor",
      "Jason Antoon",
      "Lisa Bronwyn Moore",
      "Aleksandr Belyavskiy",
      "Jason Winer",
      "Antonio David Lyons",
      "Lennie Loftin",
      "Mike McDougal",
      "Matt Holland",
      "Roger Tonry",
      "Oleg Belkin",
      "Constantine Gregory",
      "Griffith Brewer",
      "Jacklyn St. Pierre",
      "Mariah Inger",
      "Mark Antony Krupa",
      "Joseph Antaki",
      "Marcel Jeannin",
      "Gerry Wood",
      "Conrad Pla",
      "Philip Akin",
      "Henri Pardo",
      "Irwin Dillion",
      "Real Auger",
      "Gilles Marsolais",
      "Eric Steibi",
      "Marie-Josée Colburn",
      "Marie Matiko",
      "Laraine Newman",
    ],
  },
  {
    position: 53,
    name: "13 Going on 30",
    year: 2004,
    url: "https://boxd.it/1X6e",
    director: "",
    actors: [
      "Jennifer Garner",
      "Mark Ruffalo",
      "Judy Greer",
      "Andy Serkis",
      "Christa B. Allen",
      "Sean Marquette",
      "Alexandra Kyle",
      "Kathy Baker",
      "Phil Reeves",
      "Lynn Collins",
      "Sam Ball",
      "Susan Egan",
      "Marcia DeBonis",
      "Kiersten Warren",
      "Scout Taylor-Compton",
      "Jim Gaffigan",
      "Alex Black",
      "Ashley Benson",
      "Brie Larson",
      "Brittany Curran",
      "Renee Olstead",
      "Kayla Hickson",
      "Nick Olig",
      "Steven Strozza",
      "Maz Jobrani",
      "Joe Grifasi",
      "Mary Pat Gleason",
      "Megan Lusk",
      "Julia Roth",
      "Sarah Loew",
      "Philip Pavel",
      "Robinne Lee",
      "Benita Krista Nall",
      "Catherine Combs",
      "Gia Mantegna",
      "Sydni Beaudoin",
      "George Hine",
      "Irena Violette",
      "Ian Barford",
      "Sara Swain",
      "Corena Chase",
      "Crystal Michelle",
      "Nadine Ellis",
      "Adrian Armas",
      "Carmit Bachar",
      "Tyce Diorio",
      "Stacey Harper",
      "Brandon Henschel",
      "Kadee Sweeney",
      "Kimberly Wyatt",
      "Nancy O'Meara",
      "Tara Battani",
      "Nicole Abisinio",
    ],
  },
  {
    position: 54,
    name: "Shithouse",
    year: 2020,
    url: "https://boxd.it/nCFc",
    director: "Cooper Raiff",
    actors: [
      "Cooper Raiff",
      "Dylan Gelula",
      "Amy Landecker",
      "Logan Miller",
      "Olivia Scott Welch",
      "Abby Quinn",
      "Joy Sunday",
      "Ashley Padilla",
      "Tre Hall",
      "Alina Patra",
      "Chinedu Unaka",
      "Nick Saso",
      "Wyatt Whipple",
      "Juan Wood",
      "Andrew Hales",
      "Mallory Low",
      "Adan Rocha",
      "Natalie Rousseau",
      "Teddy Padilla",
      "Adam Foster Ballard",
      "Tessa Hope Slovis",
      "Mike Raiff",
      "Jay Duplass",
    ],
  },
  {
    position: 55,
    name: "Knock at the Cabin",
    year: 2023,
    url: "https://boxd.it/npL2",
    director: "",
    actors: [
      "Dave Bautista",
      "Jonathan Groff",
      "Ben Aldridge",
      "Kristen Cui",
      "Nikki Amuka-Bird",
      "Rupert Grint",
      "Abby Quinn",
      "Clare Louise Frost",
      "McKenna Kerrigan",
      "Odera Adimorah",
      "M. Night Shyamalan",
      "Ian Merrill Peakes",
      "Denise Nakano",
      "Rose Luardo",
      "Billy Vargus",
      "Satomi Hofmann",
      "Kelvin Leung",
      "Lee Avant",
      "Katy Murphy",
      "Kittson O'Neill",
      "Lya Yanne",
      "Hanna Gaffney",
      "Monica Fleurette",
      "Saria Chen",
    ],
  },
  {
    position: 56,
    name: "Bombshell",
    year: 2019,
    url: "https://boxd.it/j5YC",
    director: "",
    actors: [
      "Charlize Theron",
      "Nicole Kidman",
      "Margot Robbie",
      "John Lithgow",
      "Kate McKinnon",
      "Allison Janney",
      "Malcolm McDowell",
      "Connie Britton",
      "Liv Hewson",
      "Brigette Lundy-Paine",
      "Rob Delaney",
      "Mark Duplass",
      "Stephen Root",
      "Robin Weigert",
      "Amy Landecker",
      "Mark Moses",
      "Nazanin Boniadi",
      "Ben Lawson",
      "Josh Lawson",
      "Alanna Ubach",
      "Andy Buckley",
      "Brooke Smith",
      "Bree Condon",
      "D'Arcy Carden",
      "London Fuller",
      "Sedona Fuller",
      "Kevin Dorff",
      "Richard Kind",
      "Michael Buie",
      "Marc Evan Jackson",
      "Anne Ramsay",
      "Jennifer Morrison",
      "Ashley Greene",
      "Ahna O'Reilly",
      "Lisa Canning",
      "Elisabeth Röhm",
      "Alice Eve",
      "Rachael Drummond",
      "Katie Aselton",
      "P.J. Byrne",
      "Spencer Garrett",
      "Mandy Fabian",
      "Tony Plana",
      "John Rothman",
      "John Hartmann",
      "Deb Hiett",
      "Tricia Helfer",
      "Bonnie Dennison",
      "Madeline Zima",
      "Marla Garlin",
      "Eric Zuckerman",
      "Lennon Parham",
      "Trevor Guttmann",
      "Eric Winzenried",
      "Scott C. Roe",
      "Brad Morris",
      "Ross Mackenzie",
      "Scott Beehner",
      "Ben Harris",
      "Megan Grano",
      "Todd Aaron Brotze",
      "B.J. Bales",
      "Stephanie Styles",
      "Jon Gabrus",
      "Allan Havey",
      "Allan Graf",
      "Faryn Einhorn",
      "Lawrence Dodson",
      "John Atkins",
      "Daniel Prok",
      "Savannah Judy",
      "Luke Judy",
      "Brianna Barnes",
      "Adam Bhukk",
      "Rocky Bonifield",
      "Laura Linda Bradley",
      "Jonathan Bray",
      "Ben Cain",
      "Lara Clear",
      "Wayne Cole",
      "Andrew Constantini",
      "Sabrina Cooke",
      "Stephen Corliss",
      "Brian d'Arcy James",
      "Diane Dehn",
      "Troy Dillinger",
      "Cambell Dodson",
      "Katelynn Dubow",
      "Doc Farrow",
      "Erin Flannery",
      "Roslyn Gentle",
      "Matthew Gold",
      "Greg Haines",
      "Henry Miller Hansen",
      "Leland Heflin",
      "Philip Hersh",
      "Kimberly L. Jackson",
      "Karina Junker",
      "Anita Kalathara",
      "Robert Keller",
      "Bryan King",
      "Punnavith Koy",
      "Matt Laydon",
      "April Lind",
      "Victoria Marie",
      "April Martucci",
      "Jenelle McKee",
      "Angela Ann Palermo",
      "Rickie Peete",
      "Geoff Pilkington",
      "Victoria Profeta",
      "Ronald Reagan",
      "Christian Roberts",
      "Az Rudman",
      "Brent Schneiders",
      "Elizabeth Anne Stocks",
      "Holland Taylor",
      "Melissa Taylor",
      "Gina Tleel",
      "Donald Trump",
      "Kalina Vanska",
      "Tiffany Villalobos",
      "Rowena Whitson",
      "Ben Woodall",
    ],
  },
  {
    position: 57,
    name: "We Have a Ghost",
    year: 2023,
    url: "https://boxd.it/wa4K",
    director: "",
    actors: [
      "David Harbour",
      "Jahi Di'Allo Winston",
      "Anthony Mackie",
      "Erica Ash",
      "Niles Fitch",
      "Isabella Russo",
      "Tig Notaro",
      "Tom Bower",
      "Sean Boyd",
      "Nicholas X. Parsons",
      "Steve Coulter",
      "Scott A. Martin",
      "Jennifer Coolidge",
      "Peggy Walton-Walker",
      "Sherri Eakin",
      "Faith Ford",
      "Yoshio Maki",
      "Sarah Voigt",
      "Jophielle Love",
      "Merah Benoit",
      "April McCullough",
      "Gabriel Sky",
      "Taylor Shurte",
      "Sarah Durn",
      "Ariel Yasmine",
      "Bob the Drag Queen",
      "Major Dodge Jr.",
    ],
  },
  {
    position: 58,
    name: "Pitch Perfect 2",
    year: 2015,
    url: "https://boxd.it/7tNa",
    director: "",
    actors: [
      "Anna Kendrick",
      "Brittany Snow",
      "Rebel Wilson",
      "Hailee Steinfeld",
      "Skylar Astin",
      "Ben Platt",
      "Ester Dean",
      "Hana Mae Lee",
      "Alexis Knapp",
      "Chrissie Fit",
      "Adam DeVine",
      "Birgitte Hjort Sørensen",
      "Flula Borg",
      "Anna Camp",
      "Katey Sagal",
      "Kelley Jakle",
      "Shelley Regner",
      "John Hodgman",
      "Jason Jones",
      "Joe Lo Truglio",
      "Reggie Watts",
      "John Michael Higgins",
      "Elizabeth Banks",
      "Snoop Dogg",
      "David Cross",
      "Keegan-Michael Key",
      "Shawn Carter Peterson",
      "Clay Matthews",
      "David Bakhtiari",
      "Donny Barclay",
      "Josh Sitton",
      "Thomas J. Lang",
      "Jordan Rodgers",
      "Gralen Bryant Banks",
      "Sharon Garrison",
      "Brea Grant",
      "Austin Lyon",
      "Kay Cannon",
      "Natalie Morales",
      "Jake Tapper",
      "Sylvia Weatherspoon",
      "Robert W. Krieger III",
      "Joe Scarborough",
      "Mika Brzezinski",
      "Jimmy Kimmel",
      "Rosie O'Donnell",
      "Nicolle Wallace",
      "Rosie Perez",
      "Adam Levine",
      "Christina Aguilera",
      "Pharrell Williams",
      "Blake Shelton",
      "Codie L. Wiggins",
      "Blake Burt",
      "Ted Moock",
      "Jerry Clark",
      "Phi Vu",
      "Jacinto Rodriguez",
      "Ryan Leeper",
      "Andrew Fitzpatrick",
      "Allie Feder",
      "Steven Ban",
      "Brandon Lara",
      "Daniel Piglavento",
      "Brent L. Boxberger",
      "Dylan Cheek",
      "Dakota Scott Smith",
      "Jeremy Williams",
      "Samantha Smith",
      "Alexis Lawson",
      "Jordyn McDempsey",
      "Monica Malone",
      "Kimberly Madsen-Thomas",
      "Frances Manzo",
      "Cali Blake",
      "Mitch Grassi",
      "Kevin Olusola",
      "Avi Kaplan",
      "Scott Hoying",
      "Kirstin Maldonado",
      "Trace Gaynor",
      "Dominic Tibayan",
      "Barry Fortgang",
      "Julian Cruz",
      "Virgil Rosales",
      "Joseph Caigoy",
      "Pranay Sharma",
      "Kashish Hora",
      "Hariharan Ravi",
      "Prashant Ramesh",
      "Aneesh Kanakamedala",
      "Chetan Khanna",
      "Akiff Premjee",
      "Varshil Patel",
      "Rohan Murthy",
      "Dilip Rajan",
      "Praveen Rajaguru",
      "Gigi Zumbado",
      "Marisela Zumbado",
      "Alison Sahonic",
      "Jasmine Paul-Olivier",
      "Natalie Legendre",
      "Samantha Yonack",
      "Windy Diaz",
      "Amaris Flores",
      "Aakomon Jones",
      "Kyndra Reevey",
      "Naomi James",
      "Britney Chelene Thomas",
      "Michael Odokara-Okigbo",
      "Brian Watson",
      "Shanna Marie Burris",
      "Brianna O'Rourke",
      "Lindsey Legros",
      "Brandon Addison",
      "Robin Roberts",
      "Kether Donohue",
      "C.J. Perry",
      "Sope Aluko",
      "Leticia Jimenez",
      "Anton Narinskiy",
      "Deke Sharon",
    ],
  },
  {
    position: 59,
    name: "Kicking and Screaming",
    year: 1995,
    url: "https://boxd.it/1pHK",
    director: "",
    actors: [
      "Josh Hamilton",
      "Olivia d'Abo",
      "Chris Eigeman",
      "Parker Posey",
      "Jason Wiles",
      "Cara Buono",
      "Carlos Jacott",
      "Elliott Gould",
      "Eric Stoltz",
      "Samuel Gould",
      "Catherine Kellner",
      "Jonathan Baumbach",
      "John Lehr",
      "Peter Czernin",
      "Eliza Roberts",
      "Christopher Reed",
      "Noah Baumbach",
      "Jason S. Kassin",
      "David DeLuise",
      "Thea Goodman",
      "Lauren Katz",
      "Alexia Landeau",
      "Perrey Reeves",
      "Tony Giglio",
      "Richard Tacchino",
      "Nico Baumbach",
      "José Ignacio Álvarez",
      "Solier Fagundez",
      "Ian Davids",
      "Matthew Kaplan",
      "Dean Cameron",
      "Marissa Ribisi",
      "Kaela Dobkin",
      "Sal Viscuso",
      "Jessica Hecht",
      "Nora Perricone",
      "Melanie Holmes",
      "Paul Speaks",
    ],
  },
  {
    position: 60,
    name: "Gridiron Gang",
    year: 2006,
    url: "https://boxd.it/1XRu",
    director: "",
    actors: [
      "Dwayne Johnson",
      "Xzibit",
      "L. Scott Caldwell",
      "Leon Rippy",
      "Kevin Dunn",
      "Jade Yorker",
      "David V. Thomas",
      "Setu Taase",
      "Mo McRae",
      "James Earl",
      "Trever O'Brien",
      "Brandon Mychal Smith",
      "Jurnee Smollett",
      "Michael J. Pagan",
      "Jamal Mixon",
      "Danny Martinez",
      "Artie Baxter",
      "Joe Seo",
      "Joseph Raymond Lucero",
      "Robert Zepeda",
      "Omari Hardwick",
      "Six Reasons",
      "Omari Hughes",
      "Adam Clark",
      "Dan Martin",
      "Michael Jace",
      "Brett Cullen",
      "Mary Mara",
      "Garrett M. Brown",
      "Nafeesa Monroe",
      "Marcia Jeffries",
      "Charles Walker",
      "Emil Pinnock",
      "Kelli Dawn Hancock",
      "Anna Maria Horsford",
      "Steven Wash Jr.",
      "Scott Thomas Cameron",
      "Bruce Katzman",
      "Asenati Satele",
      "Shane Woolaston",
      "Sonya Eddy",
      "Gregory Farr",
      "Melissa-Anne Davenport",
      "Ambrit Millhouse",
      "Phil Reeves",
      "Danny Mora",
      "Walter A. Saunders III",
      "Robert C. Cawley",
      "Michael C. Mahon",
      "Brian Oblak",
      "Jamie McShane",
      "Allan Graf",
      "Daniel Murphy",
      "Roberto Montesinos",
      "Lamont Holmes",
      "Catherine McCord",
      "Barry Tolli",
      "Jay Bingham",
      "Daniel Abikasis",
      "John P. Husky",
    ],
  },
  {
    position: 61,
    name: "Mr. Brooks",
    year: 2007,
    url: "https://boxd.it/25nW",
    director: "",
    actors: [
      "Kevin Costner",
      "Demi Moore",
      "Dane Cook",
      "William Hurt",
      "Marg Helgenberger",
      "Danielle Panabaker",
      "Ruben Santiago-Hudson",
      "Reiko Aylesworth",
      "Matt Schulze",
      "Yasmine Delawari",
      "Jason Lewis",
      "Lindsay Crouse",
      "Megan Brown",
      "Michael Cole",
      "Ross Francis",
      "Kit Gwin",
      "Marcus Hester",
      "Jamie McShane",
      "Laura Bailey",
      "Jon Paul Burkhart",
      "Matthew Posey",
      "Brandon Ray Olive",
      "Ben Glass",
      "Kanin Howell",
      "Steve Coulter",
      "Stephen Michael Ayers",
      "Mark Scarboro",
      "Bradley Evans",
      "Rommel Sulit",
      "Phillip DeVona",
      "Dodie Brown",
      "Ted Ferguson",
      "Deborah R. Jones",
      "Gio March",
      "Colvin Roberson",
      "Michael Sieve",
      "Aisha Hinds",
      "Traci Dinwiddie",
      "Jim Farnum",
      "Rosie Cafarelli",
      "David Gibbons",
      "Jasa Abreo",
    ],
  },
  {
    position: 62,
    name: "The Whale",
    year: 2022,
    url: "https://boxd.it/tw4c",
    director: "",
    actors: [
      "Brendan Fraser",
      "Sadie Sink",
      "Hong Chau",
      "Ty Simpkins",
      "Samantha Morton",
      "Sathya Sridharan",
      "Jacey Sink",
    ],
  },
  {
    position: 63,
    name: "The Boy in the Striped Pyjamas",
    year: 2008,
    url: "https://boxd.it/1NOK",
    director: "",
    actors: [
      "Asa Butterfield",
      "Jack Scanlon",
      "Vera Farmiga",
      "David Thewlis",
      "Rupert Friend",
      "David Hayman",
      "Sheila Hancock",
      "Cara Horgan",
      "Richard Johnson",
      "Amber Beattie",
      "Zac Mattoon O'Brien",
      "Charlie Baker",
      "Jim Norton",
      "Domonkos Németh",
      "Henry Kingsmill",
      "Zsuzsa Holl",
      "László Áron",
      "Iván Verebély",
      "Béla Fesztbaum",
      "Mihály Szabados",
      "Zsolt Sáfár Kovács",
      "Gábor Harsai",
      "Julia Papp",
      "László Nádasi",
      "László Quitt",
    ],
  },
  {
    position: "64",
    name: "The Salvation",
    year: "2014",
    url: "https://boxd.it/7X0M",
    director: "",
    actors: [
      "Mads Mikkelsen",
      "Eva Green",
      "Jeffrey Dean Morgan",
      "Eric Cantona",
      "Mikael Persbrandt",
      "Douglas Henshall",
      "Michael Raymond-James",
      "Jonathan Pryce",
      "Nanna Øland Fabricius",
      "Toke Lars Bjarke",
      "Sean Cameron Michael",
      "Carl Nel",
      "Kobus Swanepool",
      "Jose Domingos",
      "Sivan Raphaely",
      "Vanessa Cooke",
      "Grant Swanby",
      "Theo Geldenhuys",
      "Susan Danford",
      "Matthew Thompson",
      "Kelly Lambe",
      "Danny Keogh",
      "Adam Neill",
      "David James",
      "Anthony Oseyemi",
      "Nick Boraine",
      "Robert Hobbs",
      "Anthony Bishop",
      "St John Alexander",
      "Langley Kirkwood",
      "Aidan Lithgow",
      "Dan Robbertse",
      "Andre Odendaal",
      "Ian Edmondstone",
      "Willem Huyzers",
      "Jacques Gombault",
      "Daniel Janks",
      "Koos Dippenaar",
      "Chad Sapire",
      "Juan Dippenaar",
      "Tjaka Erasmus",
      "Hannes Vosloo",
      "Chris Oberem",
      "Jimmy Fell",
      "Gavin Mey",
      "Alexander Arnold",
    ],
  },
];

export default movies;
