let movies = [
  {
    position: 1,
    name: "Babylon",
    year: 2022,
    url: "https://boxd.it/mM02",
    director: "Damien Chazelle",
    actors: [],
  },
  {
    position: 2,
    name: "Brawl in Cell Block 99",
    year: 2017,
    url: "https://boxd.it/dWOo",
    director: "",
    actors: [],
  },
  {
    position: 3,
    name: "Cha Cha Real Smooth",
    year: 2022,
    url: "https://boxd.it/uF8E",
    director: "Cooper Raiff",
    actors: [],
  },
  {
    position: 4,
    name: "The Method",
    year: 2005,
    url: "https://boxd.it/1CuE",
    director: "",
    actors: [],
  },
  {
    position: 5,
    name: "The Good Nurse",
    year: 2022,
    url: "https://boxd.it/jIXI",
    director: "",
    actors: [],
  },
  {
    position: 6,
    name: "White Men Can't Jump",
    year: 1992,
    url: "https://boxd.it/1WWy",
    director: "",
    actors: [],
  },
  {
    position: 7,
    name: "Puss in Boots: The Last Wish",
    year: 2022,
    url: "https://boxd.it/aaie",
    director: "",
    actors: [],
  },
  {
    position: 8,
    name: "The Substitute",
    year: 2022,
    url: "https://boxd.it/xsT4",
    director: "",
    actors: [],
  },
  {
    position: 9,
    name: "Operation Mincemeat",
    year: 2021,
    url: "https://boxd.it/oAY4",
    director: "",
    actors: [],
  },
  {
    position: 10,
    name: "Puss in Boots",
    year: 2011,
    url: "https://boxd.it/eL34",
    director: "",
    actors: [],
  },
  {
    position: 11,
    name: "Aftersun",
    year: 2022,
    url: "https://boxd.it/Arw0",
    director: "",
    actors: [],
  },
  {
    position: 12,
    name: "Let's Go to Prison",
    year: 2006,
    url: "https://boxd.it/1XL2",
    director: "",
    actors: [],
  },
  {
    position: 13,
    name: "Along Came a Spider",
    year: 2001,
    url: "https://boxd.it/27yW",
    director: "",
    actors: [],
  },
  {
    position: 14,
    name: "The Bone Collector",
    year: 1999,
    url: "https://boxd.it/1Yzw",
    director: "",
    actors: [],
  },
  {
    position: 15,
    name: "The Menu",
    year: 2022,
    url: "https://boxd.it/lScm",
    director: "",
    actors: [],
  },
  {
    position: 16,
    name: "X",
    year: 2022,
    url: "https://boxd.it/sxVa",
    director: "",
    actors: [],
  },
  {
    position: 17,
    name: "Ready or Not",
    year: 2019,
    url: "https://boxd.it/kOf0",
    director: "",
    actors: [],
  },
  {
    position: 18,
    name: "The Marriage App",
    year: 2022,
    url: "https://boxd.it/zLxK",
    director: "",
    actors: [],
  },
  {
    position: 19,
    name: "Instant Family",
    year: 2018,
    url: "https://boxd.it/hHpQ",
    director: "",
    actors: [],
  },
  {
    position: 20,
    name: "Enola Holmes 2",
    year: 2022,
    url: "https://boxd.it/vfDe",
    director: "",
    actors: [],
  },
  {
    position: 21,
    name: "Closer",
    year: 2004,
    url: "https://boxd.it/270K",
    director: "",
    actors: [],
  },
  {
    position: 22,
    name: "Alive",
    year: 1993,
    url: "https://boxd.it/210u",
    director: "",
    actors: [],
  },
  {
    position: 23,
    name: "The Pale Blue Eye",
    year: 2022,
    url: "https://boxd.it/u8tk",
    director: "",
    actors: [],
  },
  {
    position: 24,
    name: "The Silence of the Sky",
    year: 2016,
    url: "https://boxd.it/ezJC",
    director: "",
    actors: [],
  },
  {
    position: 25,
    name: "RRR",
    year: 2022,
    url: "https://boxd.it/ljDs",
    director: "",
    actors: [],
  },
  {
    position: 26,
    name: "Tales of an Immoral Couple",
    year: 2016,
    url: "https://boxd.it/duNW",
    director: "",
    actors: [],
  },
  {
    position: 27,
    name: "West Side Story",
    year: 2021,
    url: "https://boxd.it/iwt0",
    director: "",
    actors: [],
  },
  {
    position: 28,
    name: "Death on the Nile",
    year: 2022,
    url: "https://boxd.it/ifpg",
    director: "",
    actors: [],
  },
  {
    position: 29,
    name: "Death Proof",
    year: 2007,
    url: "https://boxd.it/27GG",
    director: "",
    actors: [],
  },
  {
    position: 30,
    name: "Trial by Fire",
    year: 2018,
    url: "https://boxd.it/hjMw",
    director: "",
    actors: [],
  },
  {
    position: 31,
    name: "Talk to Her",
    year: 2002,
    url: "https://boxd.it/2beG",
    director: "",
    actors: [],
  },
  {
    position: 32,
    name: "Planet Terror",
    year: 2007,
    url: "https://boxd.it/27Gw",
    director: "",
    actors: [],
  },
  {
    position: 33,
    name: "Triangle of Sadness",
    year: 2022,
    url: "https://boxd.it/hXlq",
    director: "",
    actors: [],
  },
  {
    position: 34,
    name: "A Beautiful Day in the Neighborhood",
    year: 2019,
    url: "https://boxd.it/i7vA",
    director: "",
    actors: [],
  },
  {
    position: 35,
    name: "BARDO, False Chronicle of a Handful of Truths",
    year: 2022,
    url: "https://boxd.it/pAgy",
    director: "",
    actors: [],
  },
  {
    position: 36,
    name: "Guillermo del Toro's Pinocchio",
    year: 2022,
    url: "https://boxd.it/kjMW",
    director: "",
    actors: [],
  },
  {
    position: 37,
    name: "Marcel the Shell with Shoes On",
    year: 2021,
    url: "https://boxd.it/wMAk",
    director: "",
    actors: [],
  },
  {
    position: 38,
    name: "Van Helsing",
    year: 2004,
    url: "https://boxd.it/21aa",
    director: "",
    actors: [],
  },
  {
    position: 39,
    name: "You People",
    year: 2023,
    url: "https://boxd.it/wJYe",
    director: "",
    actors: [],
  },
  {
    position: 40,
    name: "Porco Rosso",
    year: 1992,
    url: "https://boxd.it/1Tp2",
    director: "",
    actors: [],
  },
  {
    position: 41,
    name: "42",
    year: 2013,
    url: "https://boxd.it/3GBo",
    director: "",
    actors: [],
  },
  {
    position: 42,
    name: "Spiderhead",
    year: 2022,
    url: "https://boxd.it/mLsO",
    director: "",
    actors: [],
  },
  {
    position: 43,
    name: "Emma.",
    year: 2020,
    url: "https://boxd.it/kmg0",
    director: "",
    actors: [],
  },
  {
    position: 44,
    name: "Legion of Super-Heroes",
    year: 2023,
    url: "https://boxd.it/BW1O",
    director: "",
    actors: [],
  },
  {
    position: 45,
    name: "Robin Hood",
    year: 2010,
    url: "https://boxd.it/1D6o",
    director: "",
    actors: [],
  },
  {
    position: 46,
    name: "The Sea Beast",
    year: 2022,
    url: "https://boxd.it/kv3a",
    director: "",
    actors: [],
  },
  {
    position: 47,
    name: "Green Lantern: Beware My Power",
    year: 2022,
    url: "https://boxd.it/xvNy",
    director: "",
    actors: [],
  },
  {
    position: 48,
    name: "The Gift",
    year: 2000,
    url: "https://boxd.it/27ys",
    director: "",
    actors: [],
  },
  {
    position: 49,
    name: "The Hunt",
    year: 2012,
    url: "https://boxd.it/3wEC",
    director: "",
    actors: [],
  },
  {
    position: 50,
    name: "The Widows of Thursdays",
    year: 2009,
    url: "https://boxd.it/16sm",
    director: "",
    actors: [],
  },
  {
    position: 51,
    name: "Ant-Man and the Wasp: Quantumania",
    year: 2023,
    url: "https://boxd.it/nL2y",
    director: "",
    actors: [],
  },
  {
    position: 52,
    name: "The Sum of All Fears",
    year: 2002,
    url: "https://boxd.it/242I",
    director: "",
    actors: [],
  },
  {
    position: 53,
    name: "13 Going on 30",
    year: 2004,
    url: "https://boxd.it/1X6e",
    director: "",
    actors: [],
  },
  {
    position: 54,
    name: "Shithouse",
    year: 2020,
    url: "https://boxd.it/nCFc",
    director: "Cooper Raiff",
    actors: [],
  },
  {
    position: 55,
    name: "Knock at the Cabin",
    year: 2023,
    url: "https://boxd.it/npL2",
    director: "",
    actors: [],
  },
  {
    position: 56,
    name: "Bombshell",
    year: 2019,
    url: "https://boxd.it/j5YC",
    director: "",
    actors: [],
  },
  {
    position: 57,
    name: "We Have a Ghost",
    year: 2023,
    url: "https://boxd.it/wa4K",
    director: "",
    actors: [],
  },
  {
    position: 58,
    name: "Pitch Perfect 2",
    year: 2015,
    url: "https://boxd.it/7tNa",
    director: "",
    actors: [],
  },
  {
    position: 59,
    name: "Kicking and Screaming",
    year: 1995,
    url: "https://boxd.it/1pHK",
    director: "",
    actors: [],
  },
  {
    position: 60,
    name: "Gridiron Gang",
    year: 2006,
    url: "https://boxd.it/1XRu",
    director: "",
    actors: [],
  },
  {
    position: 61,
    name: "Mr. Brooks",
    year: 2007,
    url: "https://boxd.it/25nW",
    director: "",
    actors: [],
  },
  {
    position: 62,
    name: "The Whale",
    year: 2022,
    url: "https://boxd.it/tw4c",
    director: "",
    actors: [],
  },
  {
    position: 63,
    name: "The Boy in the Striped Pyjamas",
    year: 2008,
    url: "https://boxd.it/1NOK",
    director: "",
    actors: [],
  },
  {
    position: "64",
    name: "The Salvation",
    year: "2014",
    url: "https://boxd.it/7X0M",
    director: "",
    actors: [],
  },
];

export default movies;
