let Vol8 = [
  {
    name: "BlackBerry",
    year: "2023",
    directors: ["Matt Johnson"],
    writers: ["Matt Johnson", "Matthew Miller"],
    actors: [
      "Jay Baruchel",
      "Glenn Howerton",
      "Matt Johnson",
      "Rich Sommer",
      "Michael Ironside",
      "Cary Elwes",
      "Martin Donovan",
      "Michelle Giroux",
      "Saul Rubinek",
      "SungWon Cho",
      "Mark Critch",
      "Kelly Van der Burg",
      "Gregory Ambrose Calderone",
      "Laura Cilevitz",
      "James Elliot Miniou",
      "Fuad Musayev",
      "Ethan Eng",
      "Michael Scott",
      "Steve Hamelin",
      "Pranay Noel",
      "Ben Petrie",
      "Jinny Wong",
      "Lauren Howe",
      "Stephanie Moran",
      "Maher El Hares",
      "Conor Casey",
      "Lyndon Casey",
      "Dillon Casey",
      "Eric Osborne",
      "Derek Groulx",
      "Rodrigo Fernandez-Stoll",
      "Elena Juatco",
      "Al Bernstein",
      "Malakai Fox",
      "David Christo",
      "Sean Jones",
      "Evan Buliung",
      "Gwynne Phillips",
    ],
  },
  {
    name: "The Adventures of Tintin",
    year: "2011",
    directors: ["Steven Spielberg"],
    writers: ["Joe Cornish", "Edgar Wright", "Steven Moffat"],
    actors: [
      "Jamie Bell",
      "Andy Serkis",
      "Daniel Craig",
      "Nick Frost",
      "Simon Pegg",
      "Daniel Mays",
      "Gad Elmaleh",
      "Toby Jones",
      "Enn Reitel",
      "Mackenzie Crook",
      "Tony Curran",
      "Sonje Fortag",
      "Cary Elwes",
      "Phillip Rhys",
      "Ron Bottitta",
      "Mark Ivanir",
      "Sebastian Roché",
      "Kim Stengel",
      "Abraham Justice",
      "Sana Etoile",
    ],
  },
  {
    name: "Charlie Bartlett",
    year: "2007",
    directors: ["Jon Poll"],
    writers: ["Gustin Nash"],
    actors: [
      "Anton Yelchin",
      "Robert Downey Jr.",
      "Hope Davis",
      "Kat Dennings",
      "Tyler Hilton",
      "Mark Rendall",
      "Dylan Taylor",
      "Megan Park",
      "Jonathan Malen",
      "Stephen Young",
      "Ishan Davé",
      "Dave Brown",
      "Eric Fink",
      "Noam Jenkins",
      "Lauren Collins",
      "Annick Obonsawin",
      "Sarah Gadon",
      "Drake",
      "Michael D'Ascenzo",
      "Dwayne McLean",
      "Quancetia Hamilton",
      "Richard Alan Campbell",
      "Kim Roberts",
      "David Fraser",
      "Marvin Karon",
      "Abigail Bernardez",
      "Laura Jeanes",
      "Annamaria Janice McAndrew",
      "Amelia Tenttave",
      "Annabelle Singson",
      "Julia Cohen",
      "Abby Zotz",
      "Maddy Wilde",
      "Dorian Wolf",
      "Airick Woodhead",
      "Daniel Woodhead",
      "Jake Epstein",
      "Brendan Murray",
      "Derek McGrath",
    ],
  },
  {
    name: "Gone Baby Gone",
    year: "2007",
    directors: ["Ben Affleck"],
    writers: ["Aaron Stockard", "Ben Affleck"],
    actors: [
      "Casey Affleck",
      "Michelle Monaghan",
      "Morgan Freeman",
      "Ed Harris",
      "John Ashton",
      "Amy Ryan",
      "Amy Madigan",
      "Titus Welliver",
      "Michael Kenneth Williams",
      "Edi Gathegi",
      "Mark Margolis",
      "Madeline O'Brien",
      "Slaine",
      "Trudi Goodman",
      "Matthew Maher",
      "Jill Quigg",
      "Sean Malone",
      "Brian Scannell",
      "Jay Giannone",
      "William Lee",
      "William Marlowe",
      "Daniel DeMiller Jr.",
      "Kenneth Butler Jr.",
      "Stephen Curran",
      "Michael T. Blythe",
      "Bob J. Leary",
      "Mike Pusateri",
      "Paul Sullivan",
      "John McColgam",
      "Nicholas Donovan",
      "Joseph Thomas-O'Brien",
      "Jimmy LeBlanc",
      "Mary Bounphasaysonh",
      "Fanshen Cox",
      "Kippy Goldfarb",
      "Elizabeth Duff",
      "Cathie Callanan",
      "Cameron Henry",
      "Bobby Curcuro",
      "Kevin Molis",
      "Robert Wahlberg",
      "Tom Kemp",
      "Matt Podolske",
      "Joseph Flaherty",
      "Carla Antonino",
      "Peg Holzemer",
      "Chelsea Ladd",
      "Josh Marchette",
      "Tom McNeeley",
      "Paul Hornung",
      "Rena Maliszewski",
      "Suzanne Schemm",
      "Lonnie Farmer",
      "Richard Snee",
      "Dale Place",
      "Gary Tanguay",
      "Ted Reinstein",
      "Celeste Oliva",
      "Patrick Shea",
      "Lewis D. Wheeler",
      "Michele Proude",
      "Tim Estiloz",
      "Karen Scalia",
      "John Belche",
      "Raymond Alongi",
      "Joey Vacchio",
      "Eamon Brooks",
      "Vincent H. Carolan",
      "Frank G. Sullivan",
      "Karen Ahern",
      "Ellen Becker Gray",
      "Shana Carr",
      "Mark S. Cartier",
      "Frank Durant",
      "John Franchi",
      "Alex Milne",
      "Nicholas Purcell",
      "Alan Resnic",
    ],
  },
  {
    name: "Promising Young Woman",
    year: "2020",
    directors: ["Emerald Fennell"],
    writers: ["Emerald Fennell"],
    actors: [
      "Carey Mulligan",
      "Bo Burnham",
      "Alison Brie",
      "Clancy Brown",
      "Jennifer Coolidge",
      "Laverne Cox",
      "Christopher Lowell",
      "Molly Shannon",
      "Connie Britton",
      "Adam Brody",
      "Max Greenfield",
      "Christopher Mintz-Plasse",
      "Steve Monroe",
      "Sam Richardson",
      "Ray Nicholson",
      "Timothy E. Goodwin",
      "Alli Hart",
      "Loren Paul",
      "Scott Aschenbrenner",
      "Gabriel Oliva",
      "Bryan Lillis",
      "Francisca Estevez",
      "Lorna Scott",
      "Casey Adams",
      "Vince Lozano",
      "Mike Horton",
      "Angela Zhou",
      "Austin Talynn Carpenter",
      "Emerald Fennell",
      "Alfred Molina",
    ],
  },
  {
    name: "Cuando Acecha la Maldad",
    year: "2023",
    directors: ["Demian Rugna"],
    writers: ["Demian Rugna"],
    actors: [
      "Ezequiel Rodríguez",
      "Demián Salomón",
      "Silvina Sabater",
      "Virginia Garófalo",
      "Emilio Vodanovich",
      "Marcelo Michinaux",
      "Lucrecia Niron Talazac",
      "Luis Ziembrowski",
      "Paula Rubinsztein",
      "Isabel Quinteros",
      "Desirée Salgueiro",
      "Federico Liss",
      "Ricardo Velázquez",
      "Jorge Prado",
      "Diego Sampayo",
      "Pedro Larrabide",
      "Cleo Díaz",
      "Agostina Aguilera",
      "Julián César López",
      "Maria Celina Carbajal",
      "Pablo Galarza",
      "Gonzalo Galarza",
      "Sebastián Muñiz",
    ],
  },
  {
    name: "Munich",
    year: "2005",
    directors: ["Steven Spielberg"],
    writers: ["Tony Kushner", "Eric Roth"],
    actors: [
      "Eric Bana",
      "Daniel Craig",
      "Ciarán Hinds",
      "Mathieu Kassovitz",
      "Hanns Zischler",
      "Ayelet Zurer",
      "Geoffrey Rush",
      "Gila Almagor",
      "Michael Lonsdale",
      "Mathieu Amalric",
      "Moritz Bleibtreu",
      "Valeria Bruni Tedeschi",
      "Meret Becker",
      "Marie-Josée Croze",
      "Yvan Attal",
      "Ami Weinberg",
      "Lynn Cohen",
      "Amos Lavi",
      "Moshe Ivgy",
      "Raffi Tavor",
      "Sharon Alexander",
      "Samuel Calderon",
      "Oded Teomi",
      "Igal Naor",
      "Mostefa Djadjam",
      "Abdelhafid Metalsi",
      "Lisa Werlinder",
      "Hiam Abbass",
      "Sasha Spielberg",
      "Mouna Soualem",
      "Djemel Barek",
      "Dirar Suleiman",
      "Ziad Adwan",
      "Bijan Daneshmand",
      "Rim Turki",
      "Yonatan Rozen",
      "Jonathan Uziel",
      "Guy Zo-Aretz",
      "Yossi Sagi-Bizawi",
      "Liron Levo",
      "Ohad Knoller",
      "Charley Gilleran",
      "Lyes Salem",
      "Carim Messalti",
      "Hichem Yacoubi",
      "Omar Mostafa",
      "Mahmoud Zemmouri",
      "Souad Amidou",
      "Amrou Al-Kadhi",
      "Omar Metwally",
      "Nasser Memarzia",
      "Karim Quayouh",
      "Mihalis Giannatos",
      "Faruk Pruti",
      "Rad Lazar",
      "Laurence Février",
      "Habir Yahya",
      "Mehdi Nebbou",
      "Hicham Nazzal",
      "Lemir Guerfa",
      "Hisham Suliman",
      "Brian Goodman",
      "Richard Brake",
      "Robert John Burke",
      "Yehuda Levi",
      "Danny Zahavi",
      "Itay Barnea",
      "Elyse Klaits",
      "Nabil Yajjou",
      "Karim Saleh",
      "Merik Tadros",
      "Mousa Kraish",
      "Karim Saidi",
      "Moa Khouas",
      "David A. Hamade",
      "Ben Youcef",
      "Sami Samir",
      "Guri Weinberg",
      "Sam Feuer",
      "Sabi Dorr",
      "Wojciech Machnicki",
      "David Feldman",
      "Ori Pfeffer",
      "Shmuel Edelman",
      "Joseph Sokolsky",
      "Lior Perel",
      "Ossie Beck",
      "Guy Amir",
      "Haguy Wigdor",
      "Jonathan Avigdori",
      "Kevin Collins",
      "Daniel Bess",
      "Baya Belal",
      "Ula Tabari",
      "Saïda Bekkouche",
      "Fettouma Ousliha-Bouamari",
      "Alexander Beyer",
      "Amos Shoov",
      "Rana Werbin",
      "Jane Garioni",
      "Félicité Du Jeu",
      "Gil Soriano",
      "Mordechai Ben-Shachar",
      "Amani Zain",
      "Leda Mansour",
      "Renana Raz",
      "Hagit Dasberg",
      "Patrick Kennedy",
      "Stéphane Freiss",
      "Arturo Arribas",
      "Yaron Motola",
      "Jalil Naciri",
      "Martin Ontrop",
      "Joram Voelklein",
      "Michael Schenk",
      "Andreas Lust",
      "Tom Wlaschiha",
      "Lili Bordán",
      "María Casal",
      "Sonia Hell",
      "Amelia Jacob",
      "Sarah Mennell",
      "Dianne Zaremba",
      "Jim McKay",
    ],
  },
  {
    name: "La Sociedad de la Nieve",
    year: "2023",
    directors: ["J A Bayona"],
    writers: [
      "Bernat Vilaplana",
      "Jaime Marques",
      "J A Bayona",
      "Nicolas Casariego",
    ],
    actors: [
      "Enzo Vogrincic",
      "Agustín Pardella",
      "Matías Recalt",
      "Tomas Wolf",
      "Diego Vegezzi",
      "Esteban Kukuriczka",
      "Francisco Romero",
      "Rafael Federman",
      "Felipe González Otaño",
      "Agustín Della Corte",
      "Valentino Alonso",
      "Simon Hempe",
      "Fernando Contigiani García",
      "Benjamín Segura",
      "Luciano Chatton",
      "Agustín Berruti",
      "Juan Caruso",
      "Rocco Posca",
      "Andy Pruss",
      "Esteban Bigliardi",
      "Paula Baldini",
      "Blas Polidori",
      "Felipe Ramusio Mora",
      "Santiago Vaca Narvaja",
      "Emanuel Parga",
      "Federico Aznárez",
      "Alfonsina Carrocio",
      "Louta",
      "Juandi Eirea Young",
      "Jerónimo Bosia",
      "Giselle Douaret",
      "Agustín Lain",
      "Julian Bedino",
      "Lautaro Martín Bakir",
      "Tea Alberti",
      "Francisco Bereny",
      "Toto Rovito",
      "Lucas Mascarena",
      "Maximiliano de la Cruz",
      "Juan José Marco",
      "Mariano Rochman",
      "Esteban Pico",
      "Pablo Tate",
      "Virgínia Kauffmann",
      "Francisco Burghi",
      "Daniel Patricio Antivilio Acuña",
      "Ezequiel Fadel Hinojosa",
      "Gustavo F. Sasco",
      "Facundo Roure",
      "Carlos Miguel Páez Rodríguez",
      "Emanuel Sobré",
      "Roberto Suárez",
      "Constanza del Sol Giraudo",
      "Federico Formento",
      "Gustavo Zerbino Stajano",
      "Ramón Mario Sabella Barreiro",
    ],
  },
  {
    name: "Priscilla",
    year: "2023",
    directors: ["Sofia Coppola"],
    writers: ["Sofia Coppola"],
    actors: [
      "Cailee Spaeny",
      "Jacob Elordi",
      "Ari Cohen",
      "Dagmara Domińczyk",
      "Tim Post",
      "Lynne Griffin",
      "Dan Beirne",
      "Rodrigo Fernandez-Stoll",
      "Dan Abramovici",
      "Matthew Shaw",
      "Tim Dowler-Coltman",
      "R Austin Ball",
      "Olivia Barrett",
      "Stephanie Moore",
      "Luke Humphrey",
      "Deanna Jarvis",
      "Jorja Cadence",
      "Josette Halpert",
      "Evan Annisette",
      "Stephanie Moran",
      "Daniel Lipka",
      "Raine Monroe Boland",
      "Emily Mitchell",
      "Kamilla Kowal",
      "Gwynne Phillips",
      "Conni Miu",
      "Megan Dallan",
      "Tonia Venneri",
      "Erin Mackinnon",
      "Mary Kelly",
      "Paige LeBlanc",
      "Anna Mirodin",
      "Sarah Dodd",
      "Alanis Peart",
      "Kelaiah Guiel",
    ],
  },
  {
    name: "Incendies",
    year: "2010",
    directors: ["Denis Villeneuve"],
    writers: ["Valerie Beaugrand Champagne", "Denis Villeneuve"],
    actors: [
      "Lubna Azabal",
      "Mélissa Désormeaux-Poulin",
      "Maxim Gaudette",
      "Rémy Girard",
      "Allen Altman",
      "Abdelghafour Elaaziz",
      "Dominique Briand",
      "Frédéric Paquet",
      "Ahmad Massad",
      "John Dunn-Hill",
      "Jackie Sawiris",
      "Lara Atalla",
      "Baya Belal",
      "Yousef Shweihat",
      "Karim Babin",
      "Mohamed Majd",
      "Mustafa Kamel",
      "Hussein Sami",
      "Hamed Najem",
      "Bader Alami",
      "Majida Hussein",
      "Asriah Nijres",
      "Nadia Essadiqi",
    ],
  },
  {
    name: "La Uruguaya",
    year: "2022",
    directors: ["Ana Garcia Blaya"],
    writers: ["Christian Basilis"],
    actors: [
      "Sebastián Arzeno",
      "Fiorella Bottaioli",
      "Jazmín Stuart",
      "Gustavo Garzón",
      "Josefina Gali",
      "Eli Almic",
      "Emiliano García Blaya",
      "Joaquin Marques Borchex",
      "Luis Alberto Carballo",
      "Hugo Giachino",
      "Julia Guerriero",
      "Alejandra Machó",
      "Delfina Martinez",
      "Ignacio Merlo",
      "Carmela Pérez",
      'Carlos "Coli" Quijano',
    ],
  },
  {
    name: "Awareness",
    year: "2023",
    directors: ["Daniel Benmayor"],
    writers: ["Daniel Benmayor", "Ivan Ledesma"],
    actors: [
      "Carlos Scholz",
      "Pedro Alonso",
      "María Pedraza",
      "Óscar Jaenada",
      "Lela Loren",
      "Lucas Fuica",
      "Silvia Kal",
      "Karina Kolokolchykova",
      "María Mercado",
      "Ricardo Rocca",
      "Luis Zahera",
    ],
  },
  {
    name: "The Others",
    year: "2001",
    directors: ["Alejandro Amenabar"],
    writers: ["Alejandro Amenabar"],
    actors: [
      "Nicole Kidman",
      "Christopher Eccleston",
      "Alakina Mann",
      "James Bentley",
      "Fionnula Flanagan",
      "Eric Sykes",
      "Elaine Cassidy",
      "Renée Asherson",
      "Gordon Reid",
      "Keith Allen",
      "Michelle Fairley",
      "Alexander Vince",
      "Ricardo López",
      "Aldo Grilo",
    ],
  },
];

export default Vol8;
