let Vol8 = [
  {
    name: "BlackBerry",
    year: "2023",
    directors: ["Matt Johnson"],
    writers: ["Matt Johnson", "Matthew Miller"],
    actors: [
      "Jay Baruchel",
      "Glenn Howerton",
      "Matt Johnson",
      "Rich Sommer",
      "Michael Ironside",
      "Cary Elwes",
      "Martin Donovan",
      "Michelle Giroux",
      "Saul Rubinek",
      "SungWon Cho",
      "Mark Critch",
      "Kelly Van der Burg",
      "Gregory Ambrose Calderone",
      "Laura Cilevitz",
      "James Elliot Miniou",
      "Fuad Musayev",
      "Ethan Eng",
      "Michael Scott",
      "Steve Hamelin",
      "Pranay Noel",
      "Ben Petrie",
      "Jinny Wong",
      "Lauren Howe",
      "Stephanie Moran",
      "Maher El Hares",
      "Conor Casey",
      "Lyndon Casey",
      "Dillon Casey",
      "Eric Osborne",
      "Derek Groulx",
      "Rodrigo Fernandez-Stoll",
      "Elena Juatco",
      "Al Bernstein",
      "Malakai Fox",
      "David Christo",
      "Sean Jones",
      "Evan Buliung",
      "Gwynne Phillips",
    ],
  },
  {
    name: "The Adventures of Tintin",
    year: "2011",
    directors: ["Steven Spielberg"],
    writers: ["Joe Cornish", "Edgar Wright", "Steven Moffat"],
    actors: [
      "Jamie Bell",
      "Andy Serkis",
      "Daniel Craig",
      "Nick Frost",
      "Simon Pegg",
      "Daniel Mays",
      "Gad Elmaleh",
      "Toby Jones",
      "Enn Reitel",
      "Mackenzie Crook",
      "Tony Curran",
      "Sonje Fortag",
      "Cary Elwes",
      "Phillip Rhys",
      "Ron Bottitta",
      "Mark Ivanir",
      "Sebastian Roché",
      "Kim Stengel",
      "Abraham Justice",
      "Sana Etoile",
    ],
  },
  {
    name: "Charlie Bartlett",
    year: "2007",
    directors: ["Jon Poll"],
    writers: ["Gustin Nash"],
    actors: [
      "Anton Yelchin",
      "Robert Downey Jr.",
      "Hope Davis",
      "Kat Dennings",
      "Tyler Hilton",
      "Mark Rendall",
      "Dylan Taylor",
      "Megan Park",
      "Jonathan Malen",
      "Stephen Young",
      "Ishan Davé",
      "Dave Brown",
      "Eric Fink",
      "Noam Jenkins",
      "Lauren Collins",
      "Annick Obonsawin",
      "Sarah Gadon",
      "Drake",
      "Michael D'Ascenzo",
      "Dwayne McLean",
      "Quancetia Hamilton",
      "Richard Alan Campbell",
      "Kim Roberts",
      "David Fraser",
      "Marvin Karon",
      "Abigail Bernardez",
      "Laura Jeanes",
      "Annamaria Janice McAndrew",
      "Amelia Tenttave",
      "Annabelle Singson",
      "Julia Cohen",
      "Abby Zotz",
      "Maddy Wilde",
      "Dorian Wolf",
      "Airick Woodhead",
      "Daniel Woodhead",
      "Jake Epstein",
      "Brendan Murray",
      "Derek McGrath",
    ],
  },
];

export default Vol8;
