let Vol9 = [
  {
    name: "ヤクザと家族 The Family",
    year: "2020",
    directors: ["Michihito Fujii"],
    writers: ["Michihito Fujii"],
    actors: [
      "Go Ayano",
      "Hiroshi Tachi",
      "Machiko Ono",
      "Yukiya Kitamura",
      "Hayato Ichihara",
      "Hayato Isomura",
      "Shinobu Terajima",
      "Ryutaro Ninomiya",
      "Taro Suruga",
      "Ryo Iwamatsu",
      "Shun Sugata",
      "Suon Kan",
      "Kosuke Toyohara",
      "Rina Komiyama",
      "Goki Maeda",
      "Akito Fujii",
    ],
  },
  {
    name: "1408",
    year: "2007",
    directors: ["Mikael Hafstrom"],
    writers: ["Scott Alexander", "Matt Greenberg", "Larry Karaszewski"],
    actors: [
      "John Cusack",
      "Samuel L. Jackson",
      "Mary McCormack",
      "Jasmine Jessica Anthony",
      "Tony Shalhoub",
      "Alexandra Silber",
      "Noah Lee Margetts",
      "William Armstrong",
      "Paul Birchard",
      "Margot Leicester",
      "Angel Oquendo",
      "Walter Lewis",
      "Eric Meyers",
      "Holly Hayes",
      "Johann Urb",
      "Andrew-Lee Potts",
      "Kim Thomson",
      "Drew Powell",
      "Isiah Whitlock Jr.",
      "Benny Urquidez",
      "Len Cariou",
      "Ray Nicholas",
      "Paul Kasey",
      "George Cottle",
      "William Willoughby",
      "Thomas A. McMahon",
      "Kevin Dobson",
      "Peter Conboy",
      "Georgie Lee-Robinson",
      "Bernadette Lords",
      "Rob McGillivray",
      "Kate Walsh",
    ],
  },
  {
    name: "Museo",
    year: "2018",
    directors: ["Alonso Ruizpalacios"],
    writers: ["Manuel Alcala", "Alonso Ruizpalacios"],
    actors: [
      "Gael García Bernal",
      "Leonardo Ortizgris",
      "Alfredo Castro",
      "Bernardo Velasco",
      "Leticia Brédice",
      "Ilse Salas",
      "Lisa Owen",
      "Simon Russell Beale",
      "Maite Suárez Diez",
    ],
  },
  {
    name: "The Good, the Bad and the Ugly",
    year: "1966",
    directors: ["Sergio Leone"],
    writers: [
      "Luciano Vincenzoni",
      "Furio Scarpelli",
      "Mickey Knox",
      "Sergio Leone",
      "Agenore Incrocci",
    ],
    actors: [
      "Clint Eastwood",
      "Eli Wallach",
      "Lee Van Cleef",
      "Aldo Giuffrè",
      "Luigi Pistilli",
      "Rada Rassimov",
      "Enzo Petito",
      "Claudio Scarchilli",
      "Antonio Casale",
      "Livio Lorenzon",
      "Sandro Scarchilli",
      "Benito Stefanelli",
      "Angelo Novi",
      "Antonio Casas",
      "Aldo Sambrell",
      "Al Mulock",
      "Sergio Mendizábal",
      "Antonio Molino Rojo",
      "Lorenzo Robledo",
      "Mario Brega",
      "Chelo Alonso",
      "Fortunato Arena",
      "Román Ariznavarreta",
      "Silvana Bacci",
      "Joseph Bradley",
      "Frank Braña",
      "Amerigo Castrighella",
      "Saturno Cerra",
      "William Conroy",
      "Axel Darna",
      "Tony Di Mitri",
      "Gianni Di Segni",
      "Alberigo Donadeo",
      "Attilio Dottesio",
      "Luis Fernández de Eribe",
      "Veriano Ginesi",
      "Jesús Guzmán",
      "Víctor Israel",
      "Nazzareno Natale",
      "Ricardo Palacios",
      "Antonio Palombi",
      "Romano Puppo",
      "Antoñito Ruiz",
      "Aysanoa Runachagua",
      "Enrique Santiago",
      "José Terrón",
      "Franco Tocci",
      "Antonio Montoya",
    ],
  },
  {
    name: "The Last Suit",
    year: "2017",
    directors: ["Pablo Solarz"],
    writers: ["Pablo Solarz"],
    actors: [
      "Miguel Ángel Solá",
      "Ángela Molina",
      "Olga Bołądź",
      "Julia Beerhold",
      "Martín Piroyansky",
      "Jan Mayzel",
      "Maciej Grubich",
      "Michał Sikorski",
      "Mora Starosta",
      "Leticia Gurfinkiel",
      "José Luciano González",
      "Norma Argentina",
      "Cristóbal Pinto",
      "Natalia Verbeke",
      "Noemí Frenkel",
      "Nora Zinsky",
      "Nicolás Strok",
      "Pilar Alonso",
      "Yanina Frankel",
      "Miel Bargman",
      "Mariel Rosciano",
      "Arlén Germade López de las Hazas",
      "Max Berliner",
      "Richard García",
      "Julia Martinetto",
      "Natalie Pinot",
      "Pedro Vasallo",
      "Tobías Rasse",
      "Paula Lussi",
      "Mateo Flossdorf",
      "Luciano Varela",
      "Jacek Lenartowicz",
      "Karolina Porcari",
      "Markus Oberhauser",
      "Francisco de Palma",
      "Pablo Solarz",
      "Maarten Dannenberg",
      "Roksana Nievadis",
      "Blanca Rodríguez",
      "Blanca Rodríguez Rosciano",
      "Micaela Eppeilboim",
      "Valentín Sasson",
      "Iair Kemeny",
      "Ethan Kemeny",
      "Alejandro Goldberg",
      "Diego Vainer",
      "Enrique Franov",
      "Jorge Goldberg",
      "Andrés Hojman",
      "Marina Svartzman",
      "Melina Peregal",
      "Andrea Cohan",
      "Ana Ceruti",
      "Paula Etchebehere",
      "Matías Peccia",
      "Josi Jamui",
      "Javier Cerpavicius",
      "Ariel Blickstein",
      "Martín Godlberg",
    ],
  },
  {
    name: "Flow",
    year: "2023",
    directors: ["Gints Zilbalodis"],
    writers: ["Gints Zilbalodis", "Matiss Kaza"],
    actors: [],
  },
  {
    name: "Nosferatu",
    year: "2024",
    directors: ["Robert Eggers"],
    writers: ["Robert Eggers"],
    actors: [
      "Lily-Rose Depp",
      "Nicholas Hoult",
      "Bill Skarsgård",
      "Aaron Taylor-Johnson",
      "Willem Dafoe",
      "Emma Corrin",
      "Ralph Ineson",
      "Simon McBurney",
      "Adéla Hesová",
      "Milena Konstantinova",
      "Stacy Thunes",
      "Gregory Gudgeon",
      "Robert Russell",
      "Curtis Matthew",
      "Claudiu Trandafir",
      "Georgina Bereghianu",
      "Jordan Haj",
      "Kateřina Bílá",
      "Maria Ion",
      "Tereza Dušková",
      "Liana Navrot",
      "Mihai Verbintschi",
      "Karel Dobrý",
      "Andrei Sergeev",
      "Matěj Beneš",
      "Marek Pospíchal",
      "Jan Filipenský",
      "Alex East",
      "Christian Dunckley Clark",
      "Andrea Miltner",
      "Robin Finesilver",
      "Paul Maynard",
      "Charles Horne",
      "Ella Bernstein",
      "Meredith Digings",
    ],
  },
  {
    name: "Pusher",
    year: "1996",
    directors: ["Nicolas Winding Refn"],
    writers: ["Jens Dahl", "Nicolas Winding Refn"],
    actors: [
      "Kim Bodnia",
      "Mads Mikkelsen",
      "Laura Drasbæk",
      "Zlatko Burić",
      "Slavko Labović",
      "Peter Andersson",
      "Vanja Bajicic",
      "Lisbeth Rasmussen",
      "Levino Jensen",
      "Nicolas Winding Refn",
      "Thomas Bo Larsen",
      "Lars Bom",
      "Michael Hasselflug",
      "Jesper Lohmann",
      "Steen Fridberg",
      "Gordon Kennedy",
      "Gyda Hansen",
      "Kenneth Schultz",
      "Coco C.P. Dalbert",
      "Karsten Schrøder",
      "Keith C. Stanley",
      "Lisa Lach Nielsen",
      "Thomas Aagren",
      "Eva Nauman",
      "Thomas Herschel",
      "Kenneth Herschel",
      "Gunner Clemann",
      "Alex Nielsen",
      "Laust Balskov",
      "Kim Maali",
      "Morten Pay",
      "Liv Corfixen",
      "Per Leth",
      "John Kalmar",
      "Thor Nielsen",
      "Evald",
      "Jesper Staal",
    ],
  },
  {
    name: "Changing Lanes",
    year: "2002",
    directors: ["Roger Michell"],
    writers: ["Michael Tolkin", "Chap Taylor"],
    actors: [
      "Ben Affleck",
      "Samuel L. Jackson",
      "Toni Collette",
      "Sydney Pollack",
      "William Hurt",
      "Amanda Peet",
      "Richard Jenkins",
      "Dylan Baker",
      "Kim Staunton",
      "John Benjamin Hickey",
      "Michael McGrath",
      "Bruce Altman",
      "Jennifer Dundas",
      "Joe Grifasi",
      "Tina Sloan",
      "Akil Walker",
      "Matt Malloy",
      "Cole Hawkins",
      "Ileen Getz",
      "Myra Lucretia Taylor",
      "Lisa LeGuillou",
      "Angela Goethals",
      "Kevin Sussman",
      "Susan Varon",
      "Noel Wilson",
      "Angel Caban",
      "Jim Lovelett",
      "Julia Gibson",
      "Ray Bokhour",
      "Suzanne Hevner",
      "Caleb Archer",
      "Jordan Gelber",
      "Olga Merediz",
      "Jayne Houdyshell",
      "Shabazz Ray",
      "Raymond Anthony Thomas",
      "Michael Pitt",
      "Genevieve Elam",
      "Juan Lara",
      "Anastasia Rojas",
      "Nicole Wright",
      "Clive Oliver Greenberg",
      "Gilbert S. Williams",
      "Sophia Guaspari",
      "Ruben Jared Seraballs",
      "Father Bonneau",
      "Jewel Brimage",
      "Katarina Kianna",
      "Vanessa Quel",
      "Howard I. Laniado",
      "Tony Machine",
      "Carolyn Feldschuh",
      "Maria Alaina Mason",
      "Harvey Waldman",
      "Pamela Hart",
      "Neal Jones",
      "Susan Blackwell",
      "Alyson Renaldo",
      "James Soviero",
      "Mary A. Kelly",
      "Anthony DiGiacomo",
      "Richard Velasco",
      "Leonard L. Thomas",
      "Richard Kelly",
      "Selena Blake",
      "Harriet Rosenthal",
      "John Kohl",
      "Lisa Vogel",
      "Bob Heffernan",
      "Michael Arthur",
      "Myriam Blanckaert",
      "Lloyd Booker",
      "Salvatore Cavaliere",
      "Israel Chaplin",
      "Monet Cunningham",
      "Jason Diamond",
      "Philip M. Gardiner",
      "Sean T. Krishnan",
      "Michael Lanuto",
      "Pete Macnamara",
      "Joseph Oliveira",
      "David C. Roehm Sr.",
      "Sam Rovin",
      "John H. Tobin",
      "Jarred Treiber",
      "David Von Roehm",
      "Ray Wineteer",
      "Waneeki Yokomee-Fung",
    ],
  },
  {
    name: "Kraven the Hunter",
    year: "2024",
    directors: ["Jc Chandor"],
    writers: ["Richard Wenk", "Matt Holloway", "Art Marcum"],
    actors: [
      "Aaron Taylor-Johnson",
      "Ariana DeBose",
      "Fred Hechinger",
      "Alessandro Nivola",
      "Christopher Abbott",
      "Russell Crowe",
      "Yuri Kolokolnikov",
      "Levi Miller",
      "Tom Reed",
      "Billy Barratt",
      "Diaana Babnicova",
      "Murat Seven",
      "Greg Kolpakchi",
      "Mark Arden",
      "Jack Brady",
      "Alex Batareanu",
      "Will Bowden",
      "Damola Adelaja",
      "Guillaume Delaunay",
      "Duran Fulton Brown",
      "Tanaka Mandimika",
      "Robert Hladik",
      "Thor Kjartansson",
      "Christos Dante",
      "Adam Bowman",
      "Bradley Farmer",
      "Paul Bailey",
      "Dritan Kastrati",
      "Anita-Joy Uwajeh",
      "Alex Skarbek",
      "Ivan Ignatenko",
      "Susan Aderin",
      "Preslav Shipkaliev",
      "Al Nedjari",
      "Elizabeth Appleby",
      "Marie Hogle",
      "Jon Xue Zhang",
      "Elander Moore",
      "Bailey Patrick",
      "Christopher Whitlow",
      "Waleed Hammad",
      "Toto Bruin",
      "Maxine Whittaker",
      "Jonny James",
      "Rashid Phoenix",
      "George Surry",
      "Yusuf Chaudhri",
      "Andrei Nazarenko",
      "Doren John Farmer",
      "Douglas Robson",
      "Michael Shaeffer",
      "Roderick Hill",
      "Camilla Aiko",
      "Neil Bishop",
      "Rachel Handshaw",
      "Odimegwu Okoye",
    ],
  },
  {
    name: "Güeros",
    year: "2014",
    directors: ["Alonso Ruizpalacios"],
    writers: ["Alonso Ruizpalacios", "Gibran Portela"],
    actors: [
      "Sebastián Aguirre",
      "Tenoch Huerta Mejía",
      "Leonardo Ortizgris",
      "Ilse Salas",
      "Raúl Briones",
      "Sophie Alexander-Katz",
      "Laura Almela",
      "Camila Lora",
      "Marcelo Tobar",
      "Alfonso Charpener",
      "Adrián Ladrón",
      "Bernardo Velasco",
      "Alonso Ruizpalacios",
      "Yojath Okamoto",
    ],
  },

  {
    name: "Brick",
    year: "2005",
    directors: ["Rian Johnson"],
    writers: ["Rian Johnson"],
    actors: [
      "Joseph Gordon-Levitt",
      "Emilie de Ravin",
      "Nora Zehetner",
      "Lukas Haas",
      "Noah Fleiss",
      "Matt O'Leary",
      "Noah Segan",
      "Meagan Good",
      "Brian J. White",
      "Richard Roundtree",
      "Jonathan Cauff",
      "Reedy Gibbs",
      "Lucas Babin",
      "Ari Welkom",
      "Tracy Bitterolf",
      "Cody Lightning",
      "McJoel Hamilton",
      "Lauren Johnson",
      "Dylan Lujano",
    ],
  },
  {
    name: "Wolfs",
    year: "2024",
    directors: ["Jon Watts"],
    writers: ["Jon Watts"],
    actors: [
      "George Clooney",
      "Brad Pitt",
      "Austin Abrams",
      "Amy Ryan",
      "Poorna Jagannathan",
      "Zlatko Burić",
      "Richard Kind",
      "Frances McDormand",
      "Sergio Cota Jr.",
      "Alfred Chou",
      "Robert Timothy Smith",
      "Amanda Aday",
      "Kymbali Craig",
      "Linda Carola",
      "Vladimir Sizov",
      "Abby Mohaddes",
      "Sasha Biktagir",
      "Samuel Evan Horowitz",
      "Frank Trigg",
      "Duffy Gaver",
      "Edwin Taylor",
      "Anthony N.",
      "Irina Dubova",
    ],
  },
  {
    name: "The Outfit",
    year: "2022",
    directors: ["Graham Moore"],
    writers: ["Johnathan Mcclain", "Graham Moore"],
    actors: [
      "Mark Rylance",
      "Zoey Deutch",
      "Johnny Flynn",
      "Dylan O'Brien",
      "Simon Russell Beale",
      "Nikki Amuka-Bird",
      "Alan Mehdizadeh",
      "Johnathan McClain",
      "Scoop Wasserstein",
      "Chiedu Agborh",
      "Michael Addo",
      "Michal Forejtek",
      "Bmcabana Sf",
      "John Gumley-Mason",
      "Stephen Knox",
      "Lauris Karklins",
      "Steve Chatfield",
      "William Keetch",
      "Ryan Hall",
    ],
  },
  {
    name: "Caddo Lake",
    year: "2024",
    directors: ["Logan George", "Celine Held"],
    writers: ["Logan George", "Celine Held"],
    actors: [
      "Dylan O'Brien",
      "Eliza Scanlen",
      "Lauren Ambrose",
      "Sam Hennings",
      "Diana Hopper",
      "Eric Lange",
      "Lance E. Nichols",
      "Nina Leon",
      "David Maldonado",
      "Kim Baptiste",
      "Jules Hilillo Fernandez",
      "Jody Sellers",
      "Caroline Falk",
      "Greysen Conley",
      "Larry S. White",
      "Zedrick Tinsley",
      "A.C. Cooper",
      "Jennifer Sellers",
      "Jeff Hartgrove",
    ],
  },
  {
    name: "The Watchers",
    year: "2024",
    directors: ["Ishana Night Shyamalan"],
    writers: ["Ishana Night Shyamalan"],
    actors: [
      "Dakota Fanning",
      "Georgina Campbell",
      "Olwen Fouéré",
      "Oliver Finnegan",
      "Alistair Brammer",
      "John Lynch",
      "Siobhan Hewlett",
      "Hannah Dargan",
      "Emily Dargan",
      "Joel Figueroa",
      "Thabile Michelle Hlongwane",
      "Anthony Morris",
      "Shane O'Regan",
      "Jim Tighe",
      "Zarima McDermott",
      "Morgan Bailey-Rocks",
      "Christian Bailey-Rocks",
      "Éabha Connolly",
      "Hannah Howland",
      "Kya Brame",
      "Ffion Haf",
      "Shannon Antonia",
      "Kofi De Graft Jordan",
      "Charles Camrose",
      "Charlie Mann",
      "Jacob Greenway",
      "Andrea Bechis",
      "Cara Steele",
      "Seán T. Ó Meallaigh",
      "Diarmuid de Faoite",
      "Ann Marie Horan",
    ],
  },
  {
    name: "Sonic the Hedgehog 3",
    year: "2024",
    directors: ["Jeff Fowler"],
    writers: ["Patrick Casey", "Josh Miller", "John Whittington"],
    actors: [
      "Jim Carrey",
      "Ben Schwartz",
      "Keanu Reeves",
      "Idris Elba",
      "Colleen O'Shaughnessey",
      "James Marsden",
      "Tika Sumpter",
      "Lee Majdoub",
      "Krysten Ritter",
      "Adam Pally",
      "Natasha Rothwell",
      "Shemar Moore",
      "Alyla Browne",
      "Tom Butler",
      "Jorma Taccone",
      "Sofia Pernas",
      "Cristo Fernández",
      "James Wolk",
      "Brett Tutor",
      "Richard Sutton",
      "Will Austin",
      "Bola Okun",
      "Reggie Banigo",
      "Barry Calvert",
      "Brendan Murphy",
      "Toru Nakahara",
    ],
  },
  {
    name: "Only God Forgives",
    year: "2013",
    directors: ["Nicolas Winding Refn"],
    writers: ["Nicolas Winding Refn"],
    actors: [
      "Ryan Gosling",
      "Kristin Scott Thomas",
      "Vithaya Pansringarm",
      "Rhatha Phongam",
      "Gordon Brown",
      "Tom Burke",
      "Byron Gibson",
      "Sahajak Boonthanakit",
      "Charlie Ruedpokanon",
      "Wannisa Peungpa",
      "Narucha Chaimareung",
      "Danai Thiengdham",
      "Kowit Wattanakul",
      "Wittchuta Watjanarat",
      "Pitchawat Petchayahon",
      "Nophand Boonyai",
      "Teerawat Mulvilai",
      "Aratchaporn Sathet",
      "Dujdao Vadhanapakorn",
      "Matthew Ryder",
      "Oak Keerati",
      "Sasapin Siriwanij",
      "Nuntiya Thongnoo",
      "Saicheer Wongwirot",
      "Alisa Wongvisut",
      "Byron Bishop",
      "Joe Cummings",
      "Ron Smoorenburg",
    ],
  },
  {
    name: "Definitely, Maybe",
    year: "2008",
    directors: ["Adam Brooks"],
    writers: ["Adam Brooks"],
    actors: [
      "Ryan Reynolds",
      "Abigail Breslin",
      "Elizabeth Banks",
      "Isla Fisher",
      "Rachel Weisz",
      "Kevin Kline",
      "Derek Luke",
      "Liane Balaban",
      "Annie Parisse",
      "Nestor Serrano",
      "Kevin Corrigan",
      "An Nguyen",
      "Adam Brooks",
      "Emily Wickersham",
      "Daniel Eric Gold",
      "Adam Ferrara",
      "Matthew Mason",
      "Rick Derby",
      "Sakina Jaffrey",
      "Bob Wiltfong",
      "Ryder Chasin",
      "Fiona Lane",
      "Dana Eskelson",
      "Luis Arriaga",
      "Melisa McGregor",
      "Gerard Bianco Jr.",
      "Mel Rocco",
      "Stephen Richardson",
      "Josh Caras",
      "Orlagh Cassidy",
      "Max Pomeranc",
      "Robert Klein",
      "Matt Flanders",
      "Caryn Osofsky",
      "Kerri Kwinter",
      "Alexie Gilmore",
      "Marc Bonan",
      "Amy Šafránková",
      "Dale Leigh",
      "Lauren Norman",
      "Leif Riddell",
      "Blake Benitez",
      "Dylan Hartigan",
      "Paulina Gerzon",
      "Victoria Goldsmith",
    ],
  },
  {
    name: "We Are Marshall",
    year: "2006",
    directors: ["Mcg"],
    writers: ["Cory Helms", "Jamie Linden"],
    actors: [
      "Matthew McConaughey",
      "Matthew Fox",
      "Anthony Mackie",
      "David Strathairn",
      "Ian McShane",
      "Kate Mara",
      "January Jones",
      "Kate Kneeland",
      "Wes Brown",
      "L. Warren Young",
      "Andrew Wilson Williams",
      "Huntley Ritter",
      "Nina Jones",
      "Tommy Cresswell",
      "Brian Geraghty",
      "Arlen Escarpeta",
      "Kimberly Williams-Paisley",
      "Bobby Jordan",
      "Bill Crabb",
      "Amanda Best",
      "Robert Patrick",
    ],
  },
  {
    name: "La extorsión",
    year: "2023",
    directors: ["Martino Zaidelis"],
    writers: ["Emanuel Diez"],
    actors: [
      "Guillermo Francella",
      "Pablo Rago",
      "Andrea Frigerio",
      "Carlos Portaluppi",
      "Alberto Ajaka",
      "Guillermo Arengo",
      "Mónica Villa",
      "Ruben Cirocco",
      "Zulema Galperín",
      "Alejandro Botto",
      "Carla Pandolfi",
      "Juan Lo Sasso",
      "Osvaldo Djeredjian",
      "Julieta Vallina",
      "Romina Pinto",
      "Laura Faienza",
      "Daniel Juan di Cocco",
      "Gerardo Scherman",
    ],
  },
  {
    name: "Casi muerta",
    year: "2023",
    directors: ["Fernan Miras"],
    writers: ["Rodrigo H Vila", "Fernan Miras", "Beatriz Carbajales"],
    actors: [
      "Natalia Oreiro",
      "Diego Velázquez",
      "Paola Barrientos",
      "Ariel Staltari",
      "Violeta Urtizberea",
      "Alberto Ajaka",
      "Vivian El Jaber",
      "Fernán Mirás",
    ],
  },
  {
    name: "Are You There God? It's Me, Margaret.",
    year: "2023",
    directors: ["Kelly Fremon Craig"],
    writers: ["Kelly Fremon Craig"],
    actors: [
      "Abby Ryder Fortson",
      "Rachel McAdams",
      "Kathy Bates",
      "Elle Graham",
      "Benny Safdie",
      "Amari Alexis Price",
      "Katherine Mallen Kupferer",
      "Kate MacCluggage",
      "Aidan Wojtak-Hissong",
      "Landon S. Baxter",
      "Echo Kellum",
      "Mia Dillon",
      "Gary Houston",
      "Mackenzie Joy Potter",
      "Olivia Williams",
      "Mike Platarote Jr.",
      "Simms May",
      "Zack Brooks",
      "JeCobi Swain",
      "Wilbur Fitzgerald",
      "Ethan McDowell",
      "Sloane Warren",
      "Isol Young",
      "Eden Lee",
      "Naida Nelson",
      "Tahirah Harrison",
      "Zach Humphrey",
      "Karen Aruj",
      "Judy Blume",
      "George Cooper",
      "Joan Jackson",
      "Stephen Jackson",
      "Robert Haulbrook",
      "Johnny Land",
      "Jennifer Errington",
      "Evan Bergman",
      "Michael Wolk",
      "Karen Macarah",
      "Ariel DiDonato",
      "Claude Deuce",
      "Keya Hamilton",
      "Tanya J. McClellan",
      "Dennis Delamar",
      "Samantha LeBrocq",
      "Wally White",
      "Holli Saperstein",
      "Deborah Helms",
      "Cooper Herrett",
      "Gezell Fleming",
      "Jim France",
      "Rakeem Massingill",
    ],
  },
  {
    name: "Un crimen argentino",
    year: "2022",
    directors: ["Lucas Combina"],
    writers: ["Matias Bertilotti", "Sebastian Pivotto", "Jorge Bechara"],
    actors: [
      "Nicolás Francella",
      "Matías Mayer",
      "Malena Sánchez",
      "Darío Grandinetti",
      "Alberto Ajaka",
      "César Bordón",
      "Rita Cortese",
      "Luis Luque",
      "Pablo Tolosa",
      "Luis Rubio",
    ],
  },
  {
    name: "El peso de la ley",
    year: "2017",
    directors: ["Fernan Miras"],
    writers: ["Fernan Miras", "Roberto Gispert"],
    actors: [
      "Paola Barrientos",
      "María Onetto",
      "Darío Grandinetti",
      "Daniel Lambertini",
      "Fernán Mirás",
      "Darío Barassi",
      "Daniel La Rosa",
      "Pacha Rosso",
      "Julio Feld",
      "Jorgelina Aruzzi",
    ],
  },
  {
    name: "Before the Devil Knows You're Dead",
    year: "2007",
    directors: ["Sidney Lumet"],
    writers: ["Kelly Masterson"],
    actors: [
      "Philip Seymour Hoffman",
      "Ethan Hawke",
      "Albert Finney",
      "Marisa Tomei",
      "Aleksa Palladino",
      "Michael Shannon",
      "Amy Ryan",
      "Sarah Livingston",
      "Brían F. O'Byrne",
      "Rosemary Harris",
      "Blaine Horton",
      "Arija Bareikis",
      "Leonardo Cimino",
      "Lee Wilkof",
      "Damon Gupton",
      "Myra Lucretia Taylor",
      "Marcia Jean Kurtz",
      "Adrian Martinez",
      "Patrick G. Burns",
      "Alice Spivak",
      "Natalie Gold",
      "Keith Davis",
      "Mateo Gómez",
      "Chris Chalk",
      "Sakina Jaffrey",
      "John Knox",
      "James Lally",
      "Jordan Gelber",
      "Megan Byrne",
      "Guy A. Fortt",
      "Meredith Patterson",
      "Tom Zolandz",
      "Paul Butler",
      "Anita Sklar",
      "Josh Mowery",
      "Diane Bradley",
      "Richard Lublin",
      "Bob Colletti",
      "Mary DeBellis",
      "Alex Emanuel",
      "Zeke Hawkins",
      "Charles Kopelson",
      "Nicholas E. Pagani",
    ],
  },
  {
    name: "Vengeance",
    year: "2022",
    directors: ["B.J. Novak"],
    writers: ["B.J. Novak"],
    actors: [
      "B.J. Novak",
      "Boyd Holbrook",
      "J. Smith-Cameron",
      "Issa Rae",
      "Ashton Kutcher",
      "Lio Tipton",
      "Dove Cameron",
      "Isabella Amara",
      "Eli Bickel",
      "John Mayer",
      "Louanne Stephens",
      "Zach Villa",
      "Clint Obenchain",
      "Rio Alexander",
      "Ryan Hammond",
      "Ben Whitehair",
      "Grayson Berry",
      "Nathaniel Augustson",
      "Sean J. Dillingham",
      "Ivan Hernandez",
      "David Hight",
      "Tracy S. Lee",
      "Adrianne Lovato",
      "Micah McNeil",
      "Mike Miller",
      "Sarah Minnich",
      "Bronwen Murray",
      "Aaron Rogers",
      "Tony Sedillo",
      "J. Nathan Simmons",
      "Avalon Stone",
      "Dora Woodrum",
      "Darlene Kellum",
      "Gonzalo Robles",
      "Jeremy Warner",
      "Melissa Chambers",
    ],
  },
  {
    name: "Snack Shack",
    year: "2024",
    directors: ["Adam Rehmeier"],
    writers: ["Adam Rehmeier"],
    actors: [
      "Conor Sherry",
      "Gabriel LaBelle",
      "Mika Abdalla",
      "Nick Robinson",
      "David Costabile",
      "Gillian Vigman",
      "June Gentry",
      "April Clark",
      "Michael Bonini",
      "Christian James",
      "Steve Berg",
      "Kate Robertson Pryor",
      "J.D. Evermore",
      "Dominick Marrone",
      "Tracy Long",
      "Christian J. Velez",
      "Dawson Mullen",
      "Jason Boots",
      "Sidi Henderson",
      "Gregg Gilmore",
      "Brandon Siedlik",
      "Ariel Celeste",
      "Charles H. Cohen",
      "Ben Cornwell",
      "Piper Cornwell",
      "Scooter Edminsten",
      "Daniel Foley",
      "Omri Horowitz",
      "Frank Insolera Jr.",
      "Frankie Jordan",
      "Lou Leone",
      "David Michael Long",
      "Daniel McCoy",
      "Colin McMahon",
      "Shannon Mosley",
      "Shannon Muhs",
      "Erik Mutthersbough",
      "Trevor B. Nagle",
      "Charlotte Powell",
      "Mira Rahe",
      "Melissa Rakiro",
      "Mary Redelfs",
      "Bronson Rehmeier",
      "Hawkeye Rehmeier",
      "Maverick Rehmeier",
      "Jules Reid",
      "Lucille Sharp",
      "Dorothy Symonsbergen",
      "Janell Wolford",
      "Natalie McGovern",
      "Amber Paul",
    ],
  },
  {
    name: "Los guantes mágicos",
    year: "2003",
    directors: ["Martin Rejtman"],
    writers: ["Martin Rejtman"],
    actors: [
      "Vicentico",
      "Valeria Bertuccelli",
      "Fabián Arenillas",
      "Cecilia Biagini",
      "Susana Pampín",
      "Diego Olivera",
      "Leonardo Azamor",
      "Darío Levy",
      "Pietr Krysav",
      "Denys Lukin",
      "Yelena Goreyeva",
      "Gonzalo San Martín",
      "Víctor Hugo Carrizo",
      "Alicia Palmes",
      "Santiago Bontá",
      "Sol Suárez",
      "Lilian Lapadula",
    ],
  },
  {
    name: "Dazed and Confused",
    year: "1993",
    directors: ["Richard Linklater"],
    writers: ["Richard Linklater"],
    actors: [
      "Jason London",
      "Matthew McConaughey",
      "Joey Lauren Adams",
      "Rory Cochrane",
      "Wiley Wiggins",
      "Adam Goldberg",
      "Anthony Rapp",
      "Sasha Jenson",
      "Shawn Andrews",
      "Milla Jovovich",
      "Ben Affleck",
      "Marissa Ribisi",
      "Michelle Burke",
      "Deena Martin",
      "Cole Hauser",
      "Christine Harnos",
      "Mark Vandermeulen",
      "Esteban Powell",
      "Jeremy Fox",
      "Jason O. Smith",
      "Christin Hinojosa",
      "Parker Posey",
      "Catherine Morris",
      "Nicky Katt",
      "Parker Brooks",
      "Zach Taylor",
      "Jacob Jones",
      "Rick Moser",
      "Terry Mross",
      "Kim Krizan",
      "Zooey Greif",
      "Julius Tennon",
      "Priscilla Kinser",
      "Erika Geminder",
      "Heidi Van Horne",
      "Katherine Asher",
      "Kathleen Cunningham",
      "Richard Dillard",
      "John Swasey",
      "Zeke Mills",
      "Michael Gillespie",
      "Tom Hoeck",
      "Fred Lerner",
      "David Blackwell",
      "Autumn Barr",
      "Doug Taylor",
      "Bob Moser",
      "Mona Lee Fultz",
      "Chris M. Allport",
      "Rose Barrett",
      "Tara Battani",
      "Adam Boster",
      "Josh Caldwell",
      "Nicole Emmons",
      "Mike Enright",
      "Chris Green",
      "Karey Green",
      "KaiCarra",
      "Jessica Looney",
      "Renée Zellweger",
      "Anthony Pedone",
      "Ted Perez",
      "Damian Tamburro",
      "Chris Western",
      "James 'Kimo' Wills",
      "Heath Young",
    ],
  },
  {
    name: "Youth",
    year: "2015",
    directors: ["Paolo Sorrentino"],
    writers: ["Paolo Sorrentino"],
    actors: [
      "Michael Caine",
      "Harvey Keitel",
      "Rachel Weisz",
      "Paul Dano",
      "Jane Fonda",
      "Mark Kozelek",
      "Robert Seethaler",
      "Alex MacQueen",
      "Luna Mijović",
      "Tom Lipinski",
      "Chloe Pirrie",
      "Alex Beckett",
      "Nate Dern",
      "Mark Gessner",
      "Paloma Faith",
      "Ed Stoppard",
      "Sonia Gessner",
      "Mădălina Ghenea",
      "Gabriela Belisario",
      "Ian Attard",
      "Adam Jackson-Smith",
      "Dorji Wangchuk",
      "Loredana Cannata",
      "Vincent Wolterbeek",
      "Wolfgang Michael",
      "Cornelia Marxer",
      "Heidi Maria Glössner",
      "Helmut Förnbacher",
      "Emilia Jones",
      "Alessandro Soriano",
      "Maria Letizia Gorga",
      "Leo Artin",
      "Attilio Zampieri",
      "Aldo Ralli",
      "Alexander Seibt",
      "Kaspar Weiss",
      "Sarah Amitrano",
      "Portia Reiners",
      "Poppy Corby-Tuech",
      "Leoni Stäubli",
      "Alice Bauer",
      "Anabel Kutay",
      "Paulina Jürgens",
      "Beatrice Walker",
      "Veronika Dash",
      "Rebecca Calder",
      "Eugenia Caruso",
      "Elizabeth Kinnear",
      "Josie Taylor",
      "Melinda Bokor",
      "Jasmin Barbara Mairhofer",
      "Céline Peruzzo",
      "Bleta Jahaj",
      "Lydia Rattei",
      "Ashley Bryant",
      "Beatrice Curnew",
      "Tatiana Luter",
      "Valentina Vujović",
      "Julia Danuser",
      "Svenja Hässig",
      "Lola Tobelem",
      "Dominique Leidner",
      "Anna Marie Cseh",
      "Daniela Bolliger",
      "Aleksandra Lazarevic",
      "Felicitas Heyerick",
      "Carolina Carlsson",
      "Pascal Fleury",
      "Viktoria Mullova",
      "Sumi Jo",
      "Roly Serrano",
      "Laura De Marchi",
    ],
  },
  {
    name: "Heretic",
    year: "2024",
    directors: ["Scott Beck", "Bryan Woods"],
    writers: ["Scott Beck", "Bryan Woods"],
    actors: [
      "Hugh Grant",
      "Sophie Thatcher",
      "Chloe East",
      "Topher Grace",
      "Elle Young",
      "Julie Lynn-Mortensen",
      "Haylie Hansen",
      "Elle McKinnon",
      "Hanna Huffman",
      "Anesha Bailey",
      "Miguel Castillo",
      "Stephanie Lavigne",
      "Wendy Gorling",
      "River Codack",
      "Carolyn Adair",
    ],
  },
  {
    name: "Los domingos mueren más personas",
    year: "2024",
    directors: ["Iair Said"],
    writers: ["Iair Said"],
    actors: [
      "Iair Said",
      "Rita Cortese",
      "Juliana Gattas",
      "Antonia Zegers",
      "Lucas Besasso",
      "Nina Avruj Monteoliva",
      "Homero Alegre Billoni",
      "Mario Bodega",
      "Gerardo Naumann",
      "Francisco Bereny",
      "Ceferino Carrera",
      "Alejandro Valente",
      "Damián Zaga",
      "Gabriela Tuchszer",
      "Liliana Sofía Gurevich",
      "Ari Burzstein",
      "Diego Vovchuk",
      "Amelia Pena",
      "Andrés Rossi",
      "Santiago Casares",
      "Adriana Dominga Di Pietrantonio",
      "Linda Morselli",
      "Fabiana Martinez",
      "Mariana García Guerreiro",
      "Mariana Sanguinetti",
      "Marika Semprini",
      "Pablo Cura",
      "Ignacio Jabiu",
      "Rosario Ortega",
      "Sofía Vitola",
      "Iara Grom",
    ],
  },
  {
    name: "The Boogeyman",
    year: "2023",
    directors: ["Rob Savage"],
    writers: ["Mark Heyman", "Bryan Woods", "Scott Beck"],
    actors: [
      "Sophie Thatcher",
      "Vivien Lyra Blair",
      "Chris Messina",
      "David Dastmalchian",
      "Marin Ireland",
      "Madison Hu",
      "Maddie Nichols",
      "Mabel Tyler",
      "Leeann Ross",
      "Shauna Rappold",
      "LisaGay Hamilton",
      "Cristala Carter",
      "Shayla Bagir",
      "Han Soto",
      "Seylan Baxter",
      "Aadyn Encalarde",
      "Rio Sarah Machado",
      "Ellie Bogert",
      "Maisie Bogert",
      "Noah Brand",
    ],
  },
  {
    name: "Captain America: Brave New World",
    year: "2025",
    directors: ["Julius Onah"],
    writers: [
      "Rob Edwards",
      "Malcolm Spellman",
      "Dalan Musson",
      "Julius Onah",
      "Peter Glanz",
    ],
    actors: [
      "Anthony Mackie",
      "Harrison Ford",
      "Danny Ramirez",
      "Shira Haas",
      "Tim Blake Nelson",
      "Giancarlo Esposito",
      "Carl Lumbly",
      "Xosha Roquemore",
      "Jóhannes Haukur Jóhannesson",
      "William Mark McCullough",
      "Takehiro Hira",
      "Harsh Nayyar",
      "Rick Espaillat",
      "Todd Allen Durkin",
      "Dustin Lewis",
      "Rachael Markarian",
      "Phuong Kubacki",
      "Alan Boell",
      "Ava Hill",
      "Marissa Chanel Hampton",
      "Katerina Eichenberger",
      "Mark Pettit",
      "John Mark Bowman",
      "Katina Rankin",
      "John Cihangir",
      "Eric Mbanda",
      "Koji Nishiyama",
      "David Atkinson",
      "John Dixon",
      "Josh Robin",
      "Sharon Tazewell",
      "Pete Burris",
      "Diesel Madkins",
      "Matthew Cornwell",
      "Sandra Aparicio",
      "Ricky Robles Cruz",
      "Erika Keck",
      "Hector Banos",
      "Bill Stinchcomb",
      "Gabriela Amarchand",
      "Ariana Lugo",
      "Ben Vazquez",
      "Cris Ruiz",
      "Jacqueline Loucks",
      "Jarrett Michael Collins",
      "Yaz Takahashi",
      "Tomoko Karina",
      "Robert Tretsch",
      "Travis Powers",
      "Will Holland",
      "Chealon Miller",
      "Trevor Feinstein",
      "Liv Tyler",
      "Sebastian Stan",
    ],
  },
  {
    name: "Tesis",
    year: "1996",
    directors: ["Alejandro Amenabar"],
    writers: ["Alejandro Amenabar", "Mateo Gil"],
    actors: [
      "Ana Torrent",
      "Fele Martínez",
      "Eduardo Noriega",
      "Xabier Elorriaga",
      "Miguel Picazo",
      "Nieves Herranz",
      "Rosa Campillo",
      "Paco Hernández",
      "Rosa Ávila",
      "Teresa Castanedo",
      "José Miguel Caballero",
      "Joserra Cadiñanos",
      "Julio Vélez",
      "Pilar Ortega",
      "Olga Margallo",
      "José Luis Cuerda",
      "Emiliano Otegui",
      "Walter Prieto",
      "Florentino Sainz",
      "Helena Castañeda",
    ],
  },
  {
    name: "Wolf Man",
    year: "2025",
    directors: ["Leigh Whannell"],
    writers: ["Corbett Tuck", "Leigh Whannell"],
    actors: [
      "Christopher Abbott",
      "Julia Garner",
      "Matilda Firth",
      "Sam Jaeger",
      "Ben Prendergast",
      "Benedict Hardie",
      "Zac Chandler",
      "Milo Cawthorne",
      "Leigh Whannell",
      "Rob MacBride",
    ],
  },
  {
    name: "Blink Twice",
    year: "2024",
    directors: ["Zoe Kravitz"],
    writers: ["Et Feigenbaum", "Zoe Kravitz"],
    actors: [
      "Naomi Ackie",
      "Channing Tatum",
      "Alia Shawkat",
      "Christian Slater",
      "Simon Rex",
      "Adria Arjona",
      "Haley Joel Osment",
      "Liz Caribel Sierra",
      "Levon Hawke",
      "Trew Mullen",
      "Geena Davis",
      "Kyle MacLachlan",
      "Cris Costa",
      "María Elena Olivares",
      "Saul Williams",
      "Tiffany Persons",
      "Aaron Himelstein",
      "Ben Jacobson",
      "Caroline Forsythe",
      "Garret Levitz",
      "Regina Guerrero",
      "Kerry Ardra",
      "Julian Sedgwick",
      "Mika Kubo",
      "Carlotta Kohl",
      "Tanya Windman",
      "Nuria Bages",
      "Eduardo Lopez Morton",
      "Benjamin Jacobson",
      "Emiré Arellano",
      "Zoë Kravitz",
      "Lenny Kravitz",
    ],
  },
  {
    name: "eXistenZ",
    year: "1999",
    directors: ["David Cronenberg"],
    writers: ["David Cronenberg"],
    actors: [
      "Jennifer Jason Leigh",
      "Jude Law",
      "Ian Holm",
      "Willem Dafoe",
      "Don McKellar",
      "Callum Keith Rennie",
      "Christopher Eccleston",
      "Sarah Polley",
      "Robert A. Silverman",
      "Kris Lemche",
      "Oscar Hsu",
      "Vik Sahay",
      "Kirsten Johnson",
      "James Kirchner",
      "Balázs Koós",
      "Stephanie Belding",
      "Gerry Quigley",
    ],
  },
  {
    name: "Short Circuit",
    year: "1986",
    directors: ["John Badham"],
    writers: ["Brent Maddock", "S S Wilson"],
    actors: [
      "Ally Sheedy",
      "Steve Guttenberg",
      "Fisher Stevens",
      "Austin Pendleton",
      "G.W. Bailey",
      "Brian McNamara",
      "Tim Blaney",
      "Marvin J. McIntyre",
      "John Garber",
      "Penny Santon",
      "Vernon Weddle",
      "Barbara Tarbuck",
      "Tom Lawrence",
      "Fred Slyter",
      "Billy Ray Sharkey",
      "Robert Krantz",
      "Jan Speck",
      "Marguerite Happy",
      "Howard Krick",
      "Marjorie Card Hughes",
      "Herb Smith",
      "Jack Thompson",
      "William Striglos",
      "Mary Reckley",
      "Shay McLean",
      "Eleanor C. Heutschy",
      "Sergio Kato",
    ],
  },
  {
    name: "Rye Lane",
    year: "2023",
    directors: ["Raine Allen Miller"],
    writers: ["Tom Melia", "Nathan Bryon"],
    actors: [
      "David Jonsson",
      "Vivian Oparah",
      "Poppy Allen-Quarmby",
      "Simon Manyonda",
      "Benjamin Sarpong-Broni",
      "Karene Peter",
      "Malcolm Atobrah",
      "Alice Hewkin",
      "Levi Roots",
      "Gary Beadle",
      "Llewella Gideon",
      "Delroy Brown",
      "Omari Douglas",
      "Yasmin Al-Khudhairi",
      "Marva Alexander",
      "Munya Chawawa",
      "Andrew Francis",
      "Sandra Daley",
      "Rohan Rakhit",
      "Michael Dapaah",
      "Charlotte Melia",
      "Blue Lab Beats",
      "Alex Blake",
      "Ghetto Boy",
      "Aaron Chetty",
      "Soph Galustian",
      "Charlie Knight",
      "Paul Jordan",
      "Amir Jamal",
      "Eliah Ibazebo",
      "Anthony Mackenzie",
      "Greg Mackenzie",
      "Caroline Mabey",
      "Luke Dewulff Booth",
      "Kazuyo Enomoto",
      "Colleen Allen",
      "Beri Ann-Miller",
      "Josie Coster",
      "Sharan Hunjan",
      "Elizabeth Grunberger",
      "Peter Braddock",
      "Dipali Limbachia",
      "Renford Warmington",
      "Tashienna Bookal",
      "Robin Yu",
      "Abe Valentino",
      "Jawden Hamzie",
      "Tyler Davis",
      "Tyra-Anais Davis",
      "Serena Dhanak",
      "George Taylor",
      "Scott Hillier",
      "Troy Hewitt",
      "Fredrik Ferrier",
      "Cain Aiden",
      "Bikramjit Gurm",
      "Esme Molly",
      "Colin Firth",
      "Raine Allen-Miller",
    ],
  },
  {
    name: "Companion",
    year: "2025",
    directors: ["Drew Hancock"],
    writers: ["Drew Hancock"],
    actors: [
      "Sophie Thatcher",
      "Jack Quaid",
      "Lukas Gage",
      "Megan Suri",
      "Harvey Guillén",
      "Rupert Friend",
      "Jaboukie Young-White",
      "Matthew J. McCarthy",
      "Marc Menchaca",
      "Woody Fu",
      "Ashley Lambert",
    ],
  },
  {
    name: "The Player",
    year: "1993",
    directors: ["Robert Altman"],
    writers: ["Michael Tolkin"],
    actors: [
      "Tim Robbins",
      "Greta Scacchi",
      "Fred Ward",
      "Whoopi Goldberg",
      "Peter Gallagher",
      "Brion James",
      "Cynthia Stevenson",
      "Vincent D'Onofrio",
      "Dean Stockwell",
      "Richard E. Grant",
      "Sydney Pollack",
      "Lyle Lovett",
      "Dina Merrill",
      "Angela Hall",
      "Leah Ayres",
      "Paul Hewitt",
      "Randall Batinkoff",
      "Jeremy Piven",
      "Gina Gershon",
      "Frank Barhydt",
      "Mike Kaplan",
      "Kevin Scannell",
      "Margery Bond",
      "Susan Emshwiller",
      "Brian Brophy",
      "Michael Tolkin",
      "Stephen Tolkin",
      "Natalie Strong",
      "Peter Koch",
      "Pamela Bowen",
      "Jeff Celentano",
      "Steve Allen",
      "Richard Anderson",
      "René Auberjonois",
      "Harry Belafonte",
      "Shari Belafonte",
      "Karen Black",
      "Michael Bowen",
      "Gary Busey",
      "Robert Carradine",
      "Charles Champlin",
      "Cher",
      "James Coburn",
      "Cathy Lee Crosby",
      "John Cusack",
      "Brad Davis",
      "Paul Dooley",
      "Thereza Ellis",
      "Peter Falk",
      "Felicia Farr",
      "Katarzyna Figura",
      "Louise Fletcher",
      "Dennis Franz",
      "Teri Garr",
      "Leeza Gibbons",
      "Scott Glenn",
      "Jeff Goldblum",
      "Elliott Gould",
      "Joel Grey",
      "David Alan Grier",
      "Buck Henry",
      "Anjelica Huston",
      "Kathy Ireland",
      "Steve James",
      "Maxine John-James",
      "Sally Kellerman",
      "Sally Kirkland",
      "Jack Lemmon",
      "Marlee Matlin",
      "Andie MacDowell",
      "Malcolm McDowell",
      "Jayne Meadows",
      "Martin Mull",
      "Jennifer Nash",
      "Nick Nolte",
      "Alexandra Powers",
      "Bert Remsen",
      "Guy Remsen",
      "Patricia Resnick",
      "Burt Reynolds",
      "Jack Riley",
      "Julia Roberts",
      "Mimi Rogers",
      "Annie Ross",
      "Alan Rudolph",
      "Jill St. John",
      "Susan Sarandon",
      "Adam Simon",
      "Rod Steiger",
      "Joan Tewkesbury",
      "Brian Tochi",
      "Lily Tomlin",
      "Robert Wagner",
      "Ray Walston",
      "Bruce Willis",
      "Marvin Young",
      "Ned Bellamy",
      "Steve Fuji",
      "Althea Gibson",
      "Ted Hartley",
      "Jack Jason",
      "Jack Kney",
      "James McLindon",
      "Ritchie Montgomery",
      "Derek Raser",
      "Scott Shaw",
      "Patrick Swayze",
      "Dan Twyman",
      "Marina Zenovich",
    ],
  },
  {
    name: "The Gorge",
    year: "2025",
    directors: ["Scott Derrickson"],
    writers: ["Zach Dean"],
    actors: [
      "Miles Teller",
      "Anya Taylor-Joy",
      "Sigourney Weaver",
      "Sope Dirisu",
      "William Houston",
      "Kobna Holdbrook-Smith",
      "James Marlowe",
      "Julianna Kurokawa",
      "Ruta Gedmintas",
      "Oliver Trevena",
    ],
  },
  {
    name: "La parte del león",
    year: "1978",
    directors: ["Adolfo Aristarain"],
    writers: ["Adolfo Aristarain"],
    actors: [
      "Julio De Grazia",
      "Luisina Brando",
      "Fernanda Mistral",
      "Julio Chávez",
      "Ulises Dumont",
      "Arturo Maly",
      "Osvaldo Terranova",
      "Beba Bidart",
      "Cecilia Padilla",
      "Alejandro Patiño",
      "Miguel Guerberof",
      "Patricio Contreras",
      "Enrique Mazza",
      "Lidia Catalano",
      "Héctor Monti",
      "Aldo Pastur",
      "Tito Luca",
      "Ernesto Torcha",
      "Roberto Barrio",
      "Marcos Woinsky",
      "Javier Migelson",
    ],
  },
  {
    name: "Balnearios",
    year: "2002",
    directors: ["Mariano Llinas"],
    writers: ["Mariano Llinas"],
    actors: [
      "José Palomino",
      "Verónica Llinás",
      "Daniel Natanson",
      "Mario Mactas",
      "Eduardo Gamba",
      "Nicolás Goldbart",
      "Rafael Filippelli",
      "Ulises de la Orden",
      "Astrid Lund Petersen",
      "Sergio Saad",
      "Eduardo 'Fatiga' Serrano",
      "Wenceslao Bonelli",
      "Luis Pierucci",
      "Ricardo Mannero",
      "Liliana Cuomo",
      "Alejandro C. Zucco",
      "Francisco Miguel Fernández",
      "Roberto Edgar Ojeda",
      "Osvaldo Lucero",
      "Eugenia Varas",
      "Mariano Llinás",
      "Alejandro Zucco",
    ],
  },
  {
    name: "The Greatest Hits",
    year: "2024",
    directors: ["Ned Benson"],
    writers: ["Ned Benson"],
    actors: [
      "Lucy Boynton",
      "Justin H. Min",
      "David Corenswet",
      "Austin Crute",
      "Retta",
      "Andie Ju",
      "Nelly Furtado",
      "Clementine Creevy",
      "Tom Yi",
      "Jenne Kang",
      "Jackson Kelly",
      "Mary Eileen O'Donnell",
      "Rory Keane",
      "Shelby Cobb",
      "DJ Harvey",
      "Thomas Ochoa",
      "Evan Shafran",
    ],
  },
  {
    name: "Better Man",
    year: "2024",
    directors: ["Michael Gracey"],
    writers: ["Michael Gracey", "Simon Gleeson", "Oliver Cole"],
    actors: [
      "Robbie Williams",
      "Jonno Davies",
      "Steve Pemberton",
      "Alison Steadman",
      "Kate Mulvany",
      "Frazer Hadfield",
      "Damon Herriman",
      "Raechelle Banno",
      "Tom Budge",
      "Jake Simmance",
      "Liam Head",
      "Chase Vollenweider",
      "Jesse Hyde",
      "Anthony Hayes",
      "John Waters",
      "Leo Harvey-Elledge",
      "Chris Gun",
      "Carter J. Murphy",
      "Asmara Feik",
      "Rafferty Gleeson",
      "Leatham Blisand",
      "Jasper Hall",
      "Molly Gleeson",
      "Romley Gurr",
      "John Lloyd Fillingham",
      "Rose Flanagan",
      "Jessica Lu",
      "Patrick Harvey",
      "Dailin Gabrielle",
      "Dalip Sondhi",
      "Brigid Zengeni",
      "Milijana Cancar",
      "Karina Banno",
      "Sandra Githinji",
      "Elyssia Koulouris",
      "David Woods",
      "Nick Nicolas",
      "Michelle Brasier",
      "Jack McMinn",
      "Sophia Elliff",
      "Campbell Maccorquodale",
      "John O'May",
      "Joe Ruberto",
      "Yvonne Fix",
      "Sharon Heywood",
      "Vicky Jacobs",
      "Wil King",
      "Ned Zaina",
      "David Wood",
      "Aaron Lynch",
      "Jack Stratton-Smith",
      "Teon Haywood",
      "Laurence Boxhall",
      "Clarisse Bonello",
      "Paul Esmonde",
      "Nadya Nepomnyashaya",
      "Tami Achebe",
      "Jayden Ayodele",
      "Lewis Duffield",
      "Steven Elliot",
      "Adil Akram",
      "Hannan Ahmed",
      "Perry Warner",
      "Sanjay Batra",
      "Ellie Dickens",
      "Oliver Wheeler",
      "Mark Lee",
      "Bella Merrington",
      "Ivy Tucker",
      "Thalía Dudek",
      "Clare Chihambakwe",
      "Paul Warwick",
      "Daisy Bishop",
      "Emma Johnson",
      "Jade Carr",
      "Lizzie Kelly",
      "Jonty Reason",
      "Spencer Susser",
      "Kasia Grabowski",
      "Mia Harangozó",
      "Jordan Holtam",
      "Gaby Seow",
      "Annelise Buttress",
      "Jessica Duncan",
      "Madison Gaze",
      "Emma Monaco",
      "Ben Hall",
      "Ross Sands",
      "Oliver Gebhardt",
      "Noam Phillips",
      "Tricia Hennessy",
      "Luke Travers",
      "Liam Baptista",
      "Cully Barnacle",
      "Emily Bedford",
      "Cassius Cole",
      "Yves Cole",
      "Olivia Gurr",
      "Goldie Harris-Currie",
      "Audrey Kambouris",
      "Namitha Nair",
      "Jasper McDonald Parsons",
      "Darcy Montana Sterling-Cox",
      "Sebastian Sero",
      "Liam Smith",
      "Charlotte Anderson",
      "Oliver Andrews",
      "Tyrone Anthony",
      "Jorge Antonio",
      "Chris Arias",
      "Simon Ata",
      "Fatou Bah",
      "Chantal Bala",
      "Charlotte Bazeley",
      "Olivia Beckford",
      "Jamie Bell",
      "Darren Bennett",
      "Philip Birchall",
      "Courtenay Brady",
      "Amira Walters-Byrne",
      "Beth Cain",
      "Patrick Cain",
      "Samuel Caleb Baxter",
      "Dani Cash",
      "Cece",
      "Megan Charles",
      "Tendai Chitate",
      "Vicky Clarke",
      "Elise Clinton",
      "Brie Cohen",
      "Katie Collins",
      "Armando Cruz",
      "Yves Cueni",
      "Che Barrett-Davis",
      "Idney De'Almeida",
      "Robin Dobler",
      "Kieran Donovan",
      "Harrison Dowzell",
      "Lauren Drago",
      "Joy Duckrell",
      "Erin Dusek",
      "Jo Dyce",
      "Carly Mercedes Dyer",
      "David Eap",
      "Austyn Farrell",
      "Mike Fellows",
      "Majella Fitzgerald",
      "Jakub Franasowicz",
      "Melissa Freire",
      "Tom Fryearson",
      "Chanelle George",
      "Darron Gifty",
      "Martha Gimson",
      "Jo Goodwin",
      "Jamie Graham",
      "Jenny Griffin",
      "Lina Gurin",
      "Jared Martyn-Hageman",
      "Ian Harris",
      "Yasmin Harrison",
      "LaShay Harvey",
      "Ryan Hayes",
      "Emily Haygarth",
      "Lisa Herbert",
      "Lili Hodge",
      "India Hope",
      "Kane Horn",
      "Renae Hughes",
      "Samantha Inge",
      "Sammi Lee Jayne",
      "Mira Jebari",
      "Matt Jordan",
      "Konnie Karachaliou",
      "Kate Kelly",
      "Kane Klendjian",
      "Josh Lay",
      "Steph Lee",
      "Jake Leigh",
      "Natalie Lennie",
      "Vicky Leung",
      "Hannah Levitt-Collins",
      "Ashley Lloyd",
      "Lamaar Manning",
      "Christie Lee Manning",
      "Fiona McDonald",
      "Lianne Lee May",
      "Molly McGibbon",
      "Mari Macleod",
      "Hena Memishi",
      "Victoria Mudima",
      "James Mulford",
      "Connor Murray",
      "Carella Mutagubya",
      "Mina Neighbour",
      "Anders Neilsen",
      "Ken Nguyen",
      "Shaun Niles",
      "Josh Nkemdilim",
      "Kelechi Nwanokwu",
      "Lucifer O'Shea",
      "Tom Partridge",
      "Steven Pascau",
      "Elise Pinel",
      "Neal Piron",
      "Josie Pocock",
      "Kyah Purling",
      "Luca Rainbow",
      "Nimmz Riaz",
      "Elliot Richardson",
      "Kailum Richardson",
      "Ben Ritter",
      "Alana Rixon",
      "Harry Robinson",
      "Shani Ross",
      "Carmelle Rudder",
      "Bradley Salter",
      "Hannah Sandilands",
      "Billy Sawyer",
      "Ben Scarmozzino",
      "Marty Sedgefield",
      "Brett Sewell",
      "Aaliyah Sharnell",
      "Kane Silver",
      "Fi Silverthorn",
      "Darcey Simmons",
      "Shaun Smith",
      "Oliver Smithson",
      "Emma-Louise Stansall",
      "Erica Stubbs",
      "Charlie Tatman",
      "Kim Taylor",
      "Thanh Jason Nguyen",
      "Nicky Treleaven",
      "Sophia Turner",
      "Summer Villiers",
      "Kane Walcott",
      "Nakai Warikandwa",
      "Kieran Daley Ward",
      "Randall Watson",
      "Megan Westpfel",
      "Angel Wharmby",
      "Josh Wharmby",
      "Johnny White",
      "Charlotte Wildrianne",
      "Beth Willetts",
      "Aleshia Willilams",
      "Maisie Wilson",
      "Becky Wong",
      "Devon Young",
      "Michele Zanette",
      "Jordan Elise",
    ],
  },
  {
    name: "A Complete Unknown",
    year: "2024",
    directors: ["James Mangold"],
    writers: ["Jay Cocks", "James Mangold"],
    actors: [
      "Timothée Chalamet",
      "Edward Norton",
      "Elle Fanning",
      "Monica Barbaro",
      "Scoot McNairy",
      "Dan Fogler",
      "Boyd Holbrook",
      "Will Harrison",
      "Joe Tippett",
      "Eriko Hatsune",
      "Peter Gray Lewis",
      "Peter Gerety",
      "Lenny Grossman",
      "David Wenzel",
      "Riley Hashimoto",
      "Eloise Peyrot",
      "Maya Feldman",
      "Reza Salazar",
      "James Austin Johnson",
      "David Alan Basche",
      "Joshua Henry",
      "Norbert Leo Butz",
      "Alaina Surgener",
      "Martin Fisher",
      "Craig Geraghty",
      "Michael Everett Johnson",
      "Jater Webb",
      "Andy Talen",
      "Andrew Kober",
      "Eric Berryman",
      "Molly Jobe",
      "Sophie Hart",
      "Taylor Valentine Lupini",
      "P.J. Byrne",
      "Nick Pupo",
      "Brendan Burke",
      "Laura Kariuki",
      "Zoe Zien",
      "Kevyn Morrow",
      "Andy Grotelueschen",
      "Jonathan Spivey",
      "Cilda Shaur",
      "Clark Carmichael",
      "Taylor Goodwyn",
      "Arthur Langlie",
      "Michael Chernus",
      "Jordan Goodsell",
      "Eli Brown",
      "Big Bill Morganfield",
      "Liam Craig",
      "Charlie Tahan",
      "Ian Kagey",
      "Dave Maulbeck",
      "Lorin Doctor",
      "Aidan Close",
      "Irina Chelidze",
      "Jenna Veal",
      "Joshua Flinchbaugh",
      "Cameron G. Quevedo",
      "Alexis Felix",
      "Will Price",
      "Sunny Vinsavich",
      "Kayli Carter",
      "Steve Bell",
      "Malcolm Gold",
      "Patrick Phalen",
      "Douglas Marriner",
      "Justin Levine",
      "Mark Whitfield, Jr.",
      "Joshua Crumbley",
      "Felix Lemerle",
      "Malick Koly",
      "Andre Chez Lewis",
      "Jimmy Caltrider",
      "Kyle A. Sanna",
      "Patrick M. Dennis",
      "Nick Baxter",
      "Alan Murray",
      "Mark Gross",
      "Andy Stein",
      "Jean Rohe",
      "Farley Rene",
      "Junior Cius",
      "Travis Patton",
      "Victor Sho",
      "Vincent Mp Filliatre",
      "Amos J. Machanic",
      "Sunny Jain",
      "James Archie Worley",
      "Stephen Carter Carlsen",
      "Bridget McGarry",
      "Michael Lepre",
      "Jon Gennari",
    ],
  },
  {
    name: "Silvia Prieto",
    year: "1999",
    directors: ["Martin Rejtman"],
    writers: ["Martin Rejtman"],
    actors: [
      "Rosario Bléfari",
      "Valeria Bertuccelli",
      "Vicentico",
      "Marcelo Zanelli",
      "Susana Pampín",
      "Mucio Manchini",
      "Mirta Busnelli",
      "Mario Rubinacci",
      "Gabo Correa",
      "Abián Vainstein",
      "Santiago Parra",
      "Vanessa Weinberg",
      "Ana Mignone",
      "María Fernanda Aldana",
      "Daniel Barone",
      "Cecilia Biagini",
      "Guillermina Casey",
      "Daniela Cugliandolo",
      "Pablo Córdoba",
      "Marta Espezel",
      "Bernardino R. Fernández",
      "Alejandro Hartmann",
      "Samuel Oliva",
      "Valeria Paván",
      "Marta Parga",
      "Marta Albertinazzi",
      "Daniel Valdez",
    ],
  },
  {
    name: "La mujer sin cabeza",
    year: "2008",
    directors: ["Lucrecia Martel"],
    writers: ["Lucrecia Martel"],
    actors: [
      "María Onetto",
      "Claudia Cantero",
      "César Bordón",
      "Guillermo Arengo",
      "Inés Efrón",
      "María Vaner",
      "Daniel Genoud",
      "Alicia Muxo",
      "Pía Uribelarrea",
      "Andrea Verdun",
      "Maira Juárez",
      "Liliana De La Fuente",
      "Elisabeth Lopez",
      "Andrés Siarez",
      "Carlos Sánchez",
      "Maximiliano Garros",
      "Catalino Campos",
      "Camilo Sueldo",
      "Nilda Silvia Suarez",
      "Ana Carolina Beltrán",
      "Julia Camisay",
      "María Aparicio",
      "Soledad Tovi",
      "Norberto Raúl Chunco",
      "Sebastián Montagna",
    ],
  },
  {
    name: "True Lies",
    year: "1994",
    directors: ["James Cameron"],
    writers: [
      "Simon Michael",
      "Claude Zidi",
      "Didier Kaminka",
      "James Cameron",
    ],
    actors: [
      "Arnold Schwarzenegger",
      "Jamie Lee Curtis",
      "Tom Arnold",
      "Bill Paxton",
      "Tia Carrere",
      "Art Malik",
      "Eliza Dushku",
      "Grant Heslov",
      "Charlton Heston",
      "Marshall Manesh",
      "James Allen",
      "Dieter Rauter",
      "Jane Morris",
      "Katsy Chappell",
      "Crystina Wyler",
      "Ofer Samra",
      "Paul Barselou",
      "Charles A. Tamburro",
      "Jean-Claude Parachini",
      "Uzi Gal",
      "Majed Ibrahim",
      "Armen Ksajikian",
      "Mike Akrawi",
      "Mike Cameron",
      "Charles Cragin",
      "Louai Mardini",
      "Gino Salvano",
      "Scott Dotson",
      "Tom Isbell",
      "John Bruno",
      "Sergio Kato",
      "Sayed Badreya",
      "Ray Buffer",
      "Max Daniels",
      "Joan Quinn Eastman",
      "Richard Givens",
      "Loren Janes",
      "Lane Leavitt",
      "Jody Millard",
      "Erik Parillo",
      "Manny Perry",
      "Charlie Picerni",
      "Dale Resteghini",
      "William Shipman",
      "Matt Sigloch",
      "Ryken Zane",
      "Al Conti",
      "Janet Dey",
    ],
  },
  {
    name: "Música en espera",
    year: "2009",
    directors: ["Hernan Goldfrid"],
    writers: ["Julieta Steinberg", "Patricio Vega"],
    actors: [
      "Natalia Oreiro",
      "Diego Peretti",
      "Norma Aleandro",
      "Carlos Bermejo",
      "Rafael Spregelburd",
      "Pilar Gamboa",
      "Atilio Pozzobón",
      "María Ucedo",
      "Elvira Villarino",
      "Rafael Ferro",
      "Marina Cohen",
    ],
  },
  {
    name: "Vaquero",
    year: "2011",
    directors: ["Juan Minujin"],
    writers: ["Juan Minujin", "Facundo Agrelo"],
    actors: [
      "Juan Minujín",
      "Guillermo Arengo",
      "Esmeralda Mitre",
      "Marcos Odasso",
      "Ana Caruso",
      "Daniel Fanego",
      "Alberto Suárez",
      "Leonardo Sbaraglia",
      "Pilar Gamboa",
      "Karina Frattini",
      "Sergio Pángaro",
      "Tobias Siri",
      "Marcelo Melingo",
      "Julieta Vallina",
      "Milena Ponce",
      "Manuel Ponce",
      "Franco Salvatori",
      "Amanda Minujín",
      "Carmela Minujín",
      "Laura de la Vega",
      "Sofía Reinal",
      "Miguel Ángel Porro",
      "Mikola Dykyy",
      "Carlos Casella",
      "Oxiura Malman Malman",
      "Moyra Agrelo",
      "Federico Liss",
      "Sol Titiunik",
      "Miguel Ángel Olivera",
      "Pablo Cura",
      "Esteban Lamothe",
      "Gustavo Roza",
      "Hilario Quinteros",
      "Federico Eibuszyc",
      "María Dondero",
      "Daniela Rico Artigas",
      "Brad Krupsaw",
      "Wolfram Hecht",
      "Joseph Spencer",
    ],
  },
  {
    name: "Abigail",
    year: "2024",
    directors: ["Matt Bettinelli Olpin", "Tyler Gillett"],
    writers: ["Stephen Shields", "Guy Busick"],
    actors: [
      "Melissa Barrera",
      "Dan Stevens",
      "Alisha Weir",
      "William Catlett",
      "Kathryn Newton",
      "Kevin Durand",
      "Angus Cloud",
      "Giancarlo Esposito",
      "Matthew Goode",
    ],
  },
  {
    name: "Alpha Dog",
    year: "2006",
    directors: ["Nick Cassavetes"],
    writers: ["Nick Cassavetes"],
    actors: [
      "Emile Hirsch",
      "Bruce Willis",
      "Amanda Seyfried",
      "Justin Timberlake",
      "Shawn Hatosy",
      "Ben Foster",
      "Harry Dean Stanton",
      "Matthew Barry",
      "Fernando Vargas",
      "Vincent Kartheiser",
      "Alex Solowitz",
      "Alec Vigil",
      "Frank Cassavetes",
      "Nicole Dubos",
      "Regina Rice",
      "Laura Nativo",
      "Amber Heard",
      "Anton Yelchin",
      "David Thornton",
      "Sharon Stone",
      "Olivia Wilde",
      "Heather Wahlquist",
      "Shera Danese",
      "Nancy De Mayo",
      "Xan Cassavetes",
      "Dominique Swain",
      "Charity Shea",
      "Lukas Haas",
      "Heather Elizabeth Parkhurst",
      "Jesse Erwin",
      "Paul Johansson",
      "Danny A. Abeckaser",
      "James Molina",
      "Chuck Pacheco",
      "Frank Peluso",
      "Joshua Alba",
      "Chris Kinkade",
      "Christopher Rodriguez Marquette",
      "Alex Kingston",
      "Bobby Cooper",
      "Janet Jones",
      "Alan Thicke",
      "Rick Salomon",
      "Adrianna Belan",
      "Holt McCallany",
      "Shirley Kurata",
      "Mario Ardila, Jr.",
      "Matt Borlenghi",
      "Curt Clendenin",
      "Angela Meryl",
      "Bernadette Pérez",
      "Emilio Roso",
      "Kristen Williams",
      "Greg Williams",
      "Devin Kamin",
      "Patrick Nguyen",
      "Natasha Elliott",
      "Stephanie A. Fowler",
      "Sadie",
    ],
  },
  {
    name: "Spring",
    year: "2014",
    directors: ["Justin Benson", "Aaron Moorhead"],
    writers: ["Justin Benson"],
    actors: [
      "Lou Taylor Pucci",
      "Nadia Hilker",
      "Nick Nevern",
      "Augie Duke",
      "Jeremy Gardner",
      "Vinny Curran",
      "Holly Hawkins",
      "Vanessa Bednar",
      "Shane Brady",
      "Kenzo Lee",
      "Francesco Carnelutti",
      "Chris Palko",
      "Jonathan Silvestri",
    ],
  },
  {
    name: "The Electric State",
    year: "2025",
    directors: ["Joe Russo, Anthony Russo"],
    writers: ["Christopher Markus", "Stephen Mcfeely"],
    actors: [
      "Millie Bobby Brown",
      "Chris Pratt",
      "Anthony Mackie",
      "Alan Tudyk",
      "Giancarlo Esposito",
      "Stanley Tucci",
      "Woody Harrelson",
      "Ke Huy Quan",
      "Jenny Slate",
      "Brian Cox",
      "Woody Norman",
      "Jason Alexander",
      "Holly Hunter",
      "Colman Domingo",
      "Hank Azaria",
      "Ann Russo",
      "Greg Cromer",
      "Vince Pisani",
      "Camrus Johnson",
      "Juan Uribe Brandi",
      "Roshni Edwards",
      "Will Lyman",
      "Camille Marquez",
      "Tuc Watkins",
      "Billy Gardell",
      "Merle Dandridge",
      "Ian McShay",
      "Anthony J. Vorhies",
      "Walter Strickland",
      "Joe Avena",
      "Necar Zadegan",
      "Lia Mariella Russo",
      "Marin Hinkle",
      "Brooklynn",
      "Antoinette LaVecchia",
      "Rahul Kohli",
      "Michael Trucco",
      "Gozie Agbo",
      "Rob Gronkowski",
      "Susan Leslie",
      "Jordan Black",
      "Andy Watts",
      "Jeffrey Ford",
      "Patrick Newall",
      "Terence Lee",
      "Alan Boell",
      "Myles Alexander Evans",
      "Patti Harrison",
      "Chris Castaldi",
      "Christopher Brearton",
      "Augie Rosalina",
      "Terry Notary",
      "Adam Croasdell",
      "Christopher Silvestri",
      "Devyn Dalton",
      "Phoenix Notary",
      "Gabrielle Maiden",
      "Martin Klebba",
      "Kurt Loder",
      "Katelin Chesna",
      "Sebastian Soler",
      "Joe Russo",
      "Bill Clinton",
      "Nancy Pelosi",
      "Aubrey Brockwell",
      "Billy Bob Thornton",
    ],
  },
  {
    name: "True History of the Kelly Gang",
    year: "2019",
    directors: ["Justin Kurzel"],
    writers: ["Shaun Grant"],
    actors: [
      "George MacKay",
      "Nicholas Hoult",
      "Essie Davis",
      "Russell Crowe",
      "Charlie Hunnam",
      "Orlando Schwerdt",
      "Earl Cave",
      "Sean Keenan",
      "Thomasin McKenzie",
      "Rory Collins",
      "Jacob Collins-Levy",
      "Marlon Williams",
      "Gentle Ben Corbett",
      "Claudia Karvan",
      "Harry Greenwood",
      "Josephine Blazier",
      "Louis Hewison",
      "Jillian Nguyen",
      "Jack Charles",
      "Will McNeill",
      "Paul Capsis",
      "Danzal Baker",
      "Claerwen Brown",
      "Asmara Feik",
      "Mo Scott",
      "Winona Keegan",
      "Chase Oosterweghel",
      "Daniel P. Jones",
      "Tilly Lawless",
      "Rian Goodge",
      "Ross Knight",
      "Lola Hewison",
      "Markella Kavenagh",
      "Paul Rochford",
      "Steve Bradshaw",
      "Andrew Wright",
      "Fox Curry",
      "Anni Finsterer",
      "Kane Swain",
      "Paul Hallett",
      "Louis Vogel",
      "Saiyif Canaan",
      "Charlie Chrimes",
      "Marlo Cobham",
      "Luca Concilia",
      "Will Cornish",
      "Mitchell Crow",
      "Malik Furlong",
      "Couper Gross",
      "Michael Hastie",
      "Malakai Hersburgh",
      "Jack Keenan",
      "Zach Kennedy",
      "Khan James-Parker",
      "Maya Lineham",
      "Flynn Martin",
      "Benjamin Macdonald",
      "Harry McClements",
      "Will McIntyre",
      "Felix McLeod",
      "Mitchell McMaster",
      "Laughlin Moeller",
      "Harry Musgove",
      "Bailey Smith",
      "Charlie Stock",
      "Daniel Sultana",
      "Jan Wilmar",
      "Chelsie Witnish",
      "Amy Christian",
    ],
  },
  {
    name: "Fruitvale Station",
    year: "2013",
    directors: ["Ryan Coogler"],
    writers: ["Ryan Coogler"],
    actors: [
      "Michael B. Jordan",
      "Melonie Diaz",
      "Octavia Spencer",
      "Kevin Durand",
      "Chad Michael Murray",
      "Ahna O'Reilly",
      "Ariana Neal",
      "Keenan Coogler",
      "Trestin George",
      "Joey Oglesby",
      "Michael James",
      "Marjorie Crump-Shears",
      "Destiny Ekwueme",
      "Bianca Rodriguez III",
      "Julian Keyes",
      "Kenny Grimm",
      "Tommy Wright",
      "Jemal McNeil",
      "Steven C. Johnson",
      "Alejandra Nolasco",
      "Alessandro Garcia",
      "Marvin Greene",
      "Laurel Moglen",
      "Victor Toman",
      "Herman Tsui",
      "Liisa Cohen",
      "Darren Bridgett",
      "Caroline Lesley",
      "Lucena Herrera",
      "Brian Richardson",
      "Razon Alicia Tramble",
      "Maya Tapia",
      "Nassir Zughayer",
      "Patrick Sieler",
      "Thomas Cokenias",
      "Wanda Johnson",
      "Christina Elmore",
      "Tamera Tomakili",
      "Chris Riedell",
      "Denzel Worthington",
      "Alan C. Foster",
      "Saul Ramirez",
      "Charmaine Davis",
      "Jonez Cain",
      "Jasmin Bristow",
      "Chris Morocco",
      "Robert Ajlouny",
      "Noah Staggs",
      "Kurt Cotton",
      "Nicholas Crispen",
      "Dustin Miller",
      "Sergio Alejandro",
      "William T. Bayley",
      "Jennifer Nicole",
      "Lola Preza",
      "Levi Zavala",
      "Jason Garcia",
      "William Armando",
      "Tristan Gray",
      "Ruben Rivera",
      "Kassandra Cesar",
      "Israel Cesar",
      "Tatiyana Gomez",
      "Noah Zavala",
      "Maleah Nipay-Padilla",
      "Nicole Maxali",
      "Jessica Clark",
      "John Burke",
      "Montgomery Paulsen",
      "Matthew Thomas Ward",
      "Spencer Kalin-Mulder",
      "Della Hamlin",
      "James Mastel",
      "Guzman Leonel",
      "Buddy Rahming",
    ],
  },
  {
    name: "Shade",
    year: "2003",
    directors: ["Damian Nieman"],
    writers: ["Damian Nieman"],
    actors: [
      "Stuart Townsend",
      "Sylvester Stallone",
      "Jamie Foxx",
      "Gabriel Byrne",
      "Thandiwe Newton",
      "Melanie Griffith",
      "Hal Holbrook",
      "Roger Guenveur Smith",
      "Bo Hopkins",
      "Dina Merrill",
      "Patrick Bauchau",
      "B-Real",
      "Mark Boone Junior",
      "Joe Nicolo",
      "Carl Mazzocone Sr.",
      "George Tovar",
      "Frank Medrano",
      "Jason Cerbone",
      "Mark De Alessandro",
      "Doc Duhame",
      "Shane T. Anderson",
      "Glenn Plummer",
      "Mick Rossi",
      "Sean Stanek",
      "Holly Cat",
      "Carl Mazzocone",
      "Talbert Morton",
      "Stacie Randall",
      "Rodney Rowland",
      "Michael Harney",
      "Jenifer Neme",
      "Shawn Frances Lee",
      "Tom Reynolds",
      "Greg Suddeth",
      "Erika Nann",
      "Kevin Centazzo",
      "Bret Anthony",
      "Shaun Jones",
      "Tony Amendola",
      "J. Katherine Novy",
      "Ted Hartley",
      "Kevin Burchett",
      "Chris Rommelmann",
      "Adam Grace",
      "Earl Nelson",
      "Brian Gillis",
      "Jason England",
      "David Purdham",
      "Tony Burton",
      "Steve Heinze",
      "Charles Rocket",
      "Michael Dorn",
      "Michael Zurich",
      "Jack Conley",
      "Jessica Woods",
      "Tabitha Stevens",
      "Tawny Roberts",
      "Andrea C. Robinson",
    ],
  },
  {
    name: "The Final Cut",
    year: "2004",
    directors: ["Omar Naim"],
    writers: ["Omar Naim"],
    actors: [
      "Robin Williams",
      "Mira Sorvino",
      "Jim Caviezel",
      "Mimi Kuzyk",
      "Stephanie Romanov",
      "Genevieve Buechner",
      "Brendan Fletcher",
      "Vincent Gale",
      "Tarek Bishara",
      "Casey Dubois",
      "Liam Ranger",
      "Joely Collins",
      "Michael St. John Smith",
      "Chris Britton",
      "Wanda Cannon",
      "Chaka White",
      "Don Ackerman",
      "Sarah Deakins",
      "George Gordon",
      "Spencer Achtymichuk",
      "Erin Wright",
      "Mig Macario",
      "Emy Aneke",
      "Stephen Dimopoulos",
      "Wendy Noel",
      "Kwesi Ameyaw",
      "Leanne Adachi",
      "Peter Hall",
      "Johnna Wright",
      "Bart Anderson",
      "Stefan Arngrim",
      "Darren Shahlavi",
      "Blu Mankuma",
      "Richard Hendery",
      "Jim Francis",
      "Jason Diablo",
      "Lisa Bunting",
      "Doreen Eby",
      "Andrew Bramley",
      "David James",
      "Elizabeth Urrea",
      "Barbara Krebesova",
      "Kolja Liquette",
      "Elliot Mandelcorn",
      "Ryan Gates",
      "Ian Gschwind",
      "Ellen Kennedy",
      "Mike Jocelyn",
      "Kevin Mundy",
      "Katina Robillard",
      "Lee Walker",
      "Anne Whitmore",
      "Darren Hird",
      "Bill Waters",
    ],
  },
  {
    name: "Mulholland Drive",
    year: "2001",
    directors: ["David Lynch"],
    writers: ["David Lynch"],
    actors: [
      "Naomi Watts",
      "Laura Harring",
      "Justin Theroux",
      "Ann Miller",
      "Mark Pellegrino",
      "Robert Forster",
      "Dan Hedaya",
      "Angelo Badalamenti",
      "Patrick Fischler",
      "Brent Briscoe",
      "Michael Cooke",
      "Monty Montgomery",
      "Lee Grant",
      "James Karen",
      "Chad Everett",
      "Melissa George",
      "Scott Coffey",
      "Richard Green",
      "Rebekah Del Rio",
      "Jeanne Bates",
      "Dan Birnbaum",
      "Lori Heuring",
      "Marcus Graham",
      "Bonnie Aarons",
      "Michael J. Anderson",
      "Geno Silva",
      "Billy Ray Cyrus",
      "Vincent Castellanos",
      "Wayne Grace",
      "Rita Taggart",
      "Michele Hicks",
      "Lisa Lackey",
      "Tad Horino",
      "Missy Crider",
      "Kate Forster",
      "Tony Longo",
      "Michael Fairman",
      "Rena Riffel",
      "Katharine Towne",
      "Michael Des Barres",
      "Robert Katims",
      "Randall Wulff",
      "Maya Bond",
      "Joseph Kearney",
      "Enrique Buelna",
      "Richard Mead",
      "Daniel Rey",
      "David Schroeder",
      "Tom Morris",
      "Mo Gallini",
      "Diane Nelson",
      "Charles Croughwell",
      "Michael D. Weatherred",
      "Lisa K. Ferguson",
      "William Ostrander",
      "Brian Beacock",
      "Blake Lindsley",
      "Adrien Curry",
      "Tyrah M. Lindsey",
      "Johanna Stein",
      "Conte Candoli",
      "Cori Glazer",
      "Lyssie Powell",
      "Sean Everett",
      "Kimberly Clever",
      "Joshua Collazo",
      "David Frutos",
      "Peter Loggins",
      "Theresa Salazar",
      "Thea Samuels",
      "Christian Thompson",
      "Elina Madison",
    ],
  },
  {
    name: "Big George Foreman",
    year: "2023",
    directors: ["George Tillman Jr"],
    writers: ["Frank Baldwin", "George Tillman Jr"],
    actors: [
      "Khris Davis",
      "Forest Whitaker",
      "Sullivan Jones",
      "Deion Smith",
      "Matthew Glave",
      "John Magaro",
      "Sonja Sohn",
      "Sam Trammell",
      "Lawrence Gilliard Jr.",
      "Jasmine Mathews",
      "Shein Mompremier",
      "Robert Cicchini",
      "Erica Tazel",
      "Dwayne L. Barnes",
      "K. Steele",
      "Austin David Jones",
      "Jordan Yarborough",
      "Philip Fornah",
      "Al Sapienza",
      "Brian Ibsen",
      "Kei",
      "Judd Lormand",
      "Don Tieri",
      "Robert Larriviere",
      "Ayden Gavin",
      "Azaria Carter",
      "Tom Virtue",
      "Anthony Marble",
      "Jordan Bates",
      "Dinetia Dean",
      "Russell Mora",
      "Deneen Tyler",
      "Madison Dirks",
      "April Dupré",
      "Nile Memmezzwattay",
      "T.C. Matherne",
      "Julia Lashae",
      "Ray King Sr.",
      "Slim Danger Barkowska",
      "Martin Bats Bradford",
      "Greg Wattkis",
      "Samantha Beaulieu",
      "Eric Hanson",
      "Kenneth Martin Jr.",
      "Selase Botchway",
      "Makario Glenn",
      "Tom Gregory",
      "Michael Papajohn",
      "Matthew Rimmer",
      "Tre Styles",
      "Billy Slaughter",
      "Chukwuma Onwuchekwa",
      "Lara Grice",
      "Keith Hughes",
      "Michael Harrity",
      "Chance C Morris",
      "Bill Martin Williams",
      "Desiree Edwards",
      "Jimbo Stevenson",
      "Jonathan Mercedes",
      "Jason Elwood Hanna",
      "John Palmeri",
      "Michael Thomas",
      "Raion Hill",
      "José José Reinaldo Flora",
      "Cedric Boswell",
      "Charles Brewer Jr.",
      "DJ Walton",
      "David Jite",
      "Carlos Takam",
      "Barry Hanley",
      "Zephaniah Terry",
      "Philip Craddock",
      "Matt Frost",
      "Bob Pelletier",
      "Michael Ricca",
      "David Proctor Jr.",
      "Joshua Wade",
      "Adnan Virk",
      "Brian Kenny",
      "Robert Flores",
      "Al Bernstein",
      "Tommy Wright",
      "Kasie LaFleur",
    ],
  },
  {
    name: "Dead Ringers",
    year: "1988",
    directors: ["David Cronenberg"],
    writers: ["Norman Snider", "David Cronenberg"],
    actors: [
      "Jeremy Irons",
      "Geneviève Bujold",
      "Heidi von Palleske",
      "Barbara Gordon",
      "Shirley Douglas",
      "Stephen Lack",
      "Nick Nichols",
      "Lynne Cormack",
      "Damir Andrei",
      "Miriam Newhouse",
      "David Hughes",
      "Richard W. Farrell",
      "Warren Davis",
      "Marsha Moreau",
      "Denis Akiyama",
      "Dee McCafferty",
      "Jane Luk",
      "Jill Hennessy",
      "David Cronenberg",
      "Bob Bainborough",
      "Jacqueline Hennessy",
      "Jonathan Haley",
      "Nicholas Haley",
      "Susan Markle",
      "Murray Cruchley",
      "Tita Trevisan",
      "David Walden",
      "Liliane Stillwell",
      "Denise McLeod",
      "Nicholas Rice",
      "Joe Matheson",
      "Hadley Kay",
      "Cynthia Eastman",
      "Nora Colpman",
      "Rena Polley",
      "Madeleine Atkinson",
      "John Bayliss",
      "Graham Evans",
      "Alan Gough",
      "Jordan-Patrick Marcantonio",
      "Julian-Peter Marcantonio",
      "Greg Van Riel",
    ],
  },
  {
    name: "Neon Genesis Evangelion: The End of Evangelion",
    year: "1997",
    directors: ["Hideaki Anno", "Kazuya Tsurumaki"],
    writers: ["Hideaki Anno"],
    actors: [
      "Megumi Ogata",
      "Megumi Hayashibara",
      "Kotono Mitsuishi",
      "Yuko Miyamura",
      "Fumihiko Tachiki",
      "Miki Nagasawa",
      "Takehito Koyasu",
      "Hiro Yuuki",
      "Yuriko Yamaguchi",
      "Motomu Kiyokawa",
      "Akira Ishida",
      "Mugihito",
      "Koichi Yamadera",
    ],
  },
  {
    name: "Iluminados por el fuego",
    year: "2005",
    directors: ["Tristan Bauer"],
    writers: ["Edgardo Esteban", "Tristan Bauer", "Gustavo Romero Borri"],
    actors: [
      "Gastón Pauls",
      "Virginia Innocenti",
      "Pablo Ribba",
      "César Albarracín",
      "Víctor Hugo Carrizo",
      "Arturo Bonín",
      "Marcelo Chaparro",
      "Juan Leyrado",
      "Lautaro Delgado Tymruk",
      "Gabriel Fernández",
    ],
  },
  {
    name: "Cohen vs. Rosi",
    year: "1998",
    directors: ["Daniel Barone"],
    writers: ["Jacobo Langsner"],
    actors: [
      "Alfredo Alcón",
      "Adrián Suar",
      "Laura Novoa",
      "Pepe Soriano",
      "Norman Erlich",
      "Roberto Carnaghi",
      "Virginia Innocenti",
      "Rita Cortese",
      "Favio Posca",
      "Gabriela Acher",
      "Diego Peretti",
      "Roly Serrano",
      "Claudio Giúdice",
      "Edda Díaz",
      "Julio López",
      "Florencia de la V",
      "Víctor Anakarato",
      "Cecilia Cambiaso",
      "Álvaro Pozzolo",
      "Pía Uribelarrea",
      "Tito Haas",
      "Aníbal Tamburri",
      "Ararat Tovmasian",
      "Gabriela Catap",
      "Claudia Schijman",
      "Mucio Manchini",
      "Jorge Noya",
      "Vicente Acosta",
      "Eduardo Medina",
      "Horacio Guerrico",
      "Juan Vera",
    ],
  },
  {
    name: "Cherry",
    year: "2021",
    directors: ["Joe Russo", "Anthony Russo"],
    writers: ["Jessica Goldberg", "Angela Russo Otstot"],
    actors: [
      "Tom Holland",
      "Ciara Bravo",
      "Jack Reynor",
      "Michael Rispoli",
      "Jeffrey Wahlberg",
      "Forrest Goodluck",
      "Michael Gandolfini",
      "Suhail Dabbach",
      "Daniel R. Hill",
      "Fionn O'Shea",
      "Edward Kagutuzi",
      "Ola Orebiyi",
      "Sam Clemmett",
      "Kaine Zajaz",
      "Kyle Harvey",
      "Ann Russo",
      "Thomas Lennon",
      "Theo Barklem-Biggs",
      "Pooch Hall",
      "Leo Woodall",
      "Nicholas Christopher McNeil",
      "Jose Pablo Cantillo",
      "Zac Zedalis",
      "Damon Wayans Jr.",
      "Kristopher Wente",
      "Adam Long",
      "Liam Garrigan",
      "Frank Blake",
      "Nick Nespoli",
      "Niko Bogucki",
      "Patrick Elue",
      "Lisa Louise Langford",
      "Kellye Howard",
      "Kelli Berglund",
      "Ryan Czerwonko",
      "Joe Russo",
      "Tamara Austin",
      "Joslyn Jones",
      "Leslie Stager",
      "Shawn Knox",
      "Alison Lani",
      "Davis Aguila",
      "Ricky Wayne",
      "Melissa DuPrey",
      "Craig Hurley",
      "John Newsom",
      "Marty Rudin",
      "Brian Wlodarczyk",
      "Rawa Bousabir",
      "Hatim Abdelghafour",
      "Adbdessalam El Khaldi",
      "Kianna Rose",
      "Jamie Brewer",
      "Toney Goins",
      "Dante Rosalina",
      "Vince Russo",
      "Rinska Carrasco",
      "Augie Rosalina",
      "Ron Haynes",
      "Jacinte Blankenship",
      "Bobby Schofield",
      "Harry Holland",
      "Jearell Williams",
      "Drake Tobias",
      "Chris Castaldi",
      "Paul Abell",
      "Scott Nifong",
      "Jim Wilkins",
      "Andrew Repp",
      "John Ziska",
      "Matthew King",
      "Presciliana Esparolini",
      "Nelson Bonilla",
      "Robbie Cox",
      "Aaron Lemieux",
      "Yvonne Quiachon",
      "Andrei Vintileanu",
      "Will Edgerton",
      "Bernie Kosar",
      "Siena Bella",
      "Maurice Boozer",
      "Krista Harmon",
      "Brian Andrus",
      "Chezaray Booker",
      "Ethan Deemer",
      "Stefan Johnson",
      "Lawrence Wilson",
      "Nicole Forester",
      "Sean Patterson",
      "Ern Gerardo",
      "Brian McCue",
      "Eanna O'Dowd",
      "Anna Colwell",
      "Chris Richards",
      "David Goebel",
      "Mark J Clifford",
      "Michael Cipiti",
      "Kara Kimmer",
      "Brett Justin Koppel",
      "Sherry Hudak",
      "Sofia Plass",
      "Brandon (B.Rice) Rice",
      "Keith Otto",
      "Louie Kurtzman",
      "Luca De Massis",
      "Samantha Seawolf",
    ],
  },
  {
    name: "Resolution",
    year: "2012",
    directors: ["Justin Benson", "Aaron Moorhead"],
    writers: ["Justin Benson"],
    actors: [
      "Peter Cilella",
      "Vinny Curran",
      "Zahn McClarnon",
      "Bill Oberst Jr.",
      "Emily Montague",
      "Kurt David Anderson",
      "Skyler Meacham",
      "Josh Higgins",
      "Carmel Benson",
      "Justin Benson",
      "Aaron Moorhead",
      "David Lawson Jr.",
      "Glen Roberts",
      "Bob Low",
      "Michael Felker",
      "Thor Wixom",
      "Melissa Lyon",
      "Shiblon Wixom",
      "Michael Loschiavo",
      "Sarah Oliver",
      "Jimmy Brayl",
      "Mila Rivera",
      "Tabitha Brown",
      "Catherine Burns",
    ],
  },
  {
    name: "The Negotiator",
    year: "1998",
    directors: ["F Gary Gray"],
    writers: ["Kevin Fox", "James Demonaco"],
    actors: [
      "Samuel L. Jackson",
      "Kevin Spacey",
      "David Morse",
      "Ron Rifkin",
      "John Spencer",
      "J. T. Walsh",
      "Siobhan Fallon Hogan",
      "Paul Giamatti",
      "Regina Taylor",
      "Bruce Beatty",
      "Michael Cudlitz",
      "Carlos Gómez",
      "Tim Kelleher",
      "Dean Norris",
      "Nestor Serrano",
      "Doug Spinuzza",
      "Leonard L. Thomas",
      "Stephen Lee",
      "Lily Gibson",
      "Lauri Johnson",
      "Sabi Dorr",
      "Gene Wolande",
      "Rhonda Dotson",
      "John Lordan",
      "Jack Shearer",
      "Donna Ponterotto",
      "Michael Shamus Wiles",
      "Mik Scriba",
      "Joey Perillo",
      "Mary Page Keller",
      "Kelsey Mulrooney",
      "Brad Blaisdell",
      "Bruce Wright",
      "Robert David Hall",
      "Bernard Hocke",
      "Tony Mockus Jr.",
      "Rick Scarry",
      "McNally Sagal",
      "Mary Major",
      "Edwina Moore",
      "James Blackburn",
      "Tom Bower",
      "David Michael Fordham",
      "Paul Guilfoyle",
      "Jack Rooney",
      "Rick Touhy",
      "Spitfire Brown",
      "Maureen Mendoza",
      "S. Lamar Wilson",
      "Diann Burns",
      "Mary Ann Childers",
      "Robert Jordan",
    ],
  },
  {
    name: "The Immigrant",
    year: "2013",
    directors: ["James Gray"],
    writers: ["James Gray", "Ric Menello"],
    actors: [
      "Marion Cotillard",
      "Joaquin Phoenix",
      "Jeremy Renner",
      "Dagmara Dominczyk",
      "Yelena Solovey",
      "Jicky Schnee",
      "Maja Wampuszyc",
      "Ilia Volok",
      "Angela Sarafyan",
      "Antoni Corone",
      "Patrick Husted",
      "Patrick Holden O'Neill",
      "Sam Tsoutsouvas",
      "Robert Clohessy",
      "Adam Rothenberg",
      "Matthew Humphreys",
      "James Colby",
      "Margaret Benczak",
      "Peter McRobbie",
      "Tony Ward",
      "Sofia Black-D'Elia",
      "Al Linea",
      "Josh Grisetti",
      "Christopher Burns",
      "Susan Gardner",
      "Francine Daveta",
      "Kendra Lansing",
      "Ruby Valentine",
      "Deedee Luxe",
      "Legs Malone",
      "Tansy",
      "Omar Felix",
      "Dylan Hartigan",
      "Glenn Fleshler",
      "Kayla Molina",
      "Christopher Spelman",
      "Joseph Calleja",
      "Gabriel Rush",
      "Daniella Alma",
      "George Aloi",
      "Ross Brodar",
      "Mark Byrne",
      "Emily Chapman",
      "Victor Competiello",
      "Matt DeCoster",
      "John Farrer",
      "Liam Ferguson",
      "Drew Gregory",
      "Steven R Kaufman",
      "Anna Kuchma",
      "John Mitchell",
      "Michael Morana",
      "Dean Morris",
      "Francesca Murdoch",
      "Julian Murdoch",
      "Gil O'Brien",
      "Loukas Papas",
      "Francesco Plazza",
      "Tom Stratford",
      "Sarah Sugrue",
      "Steven Vigil",
      "John Weigand",
    ],
  },
  {
    name: "Here",
    year: "2024",
    directors: ["Robert Zemeckis"],
    writers: ["Eric Roth", "Robert Zemeckis"],
    actors: [
      "Tom Hanks",
      "Robin Wright",
      "Paul Bettany",
      "Kelly Reilly",
      "Ellis Grunsell",
      "Teddy Russell",
      "Finn Guegan",
      "Callum Macreadie",
      "Lauren McQueen",
      "Grace Lyra",
      "Jemima Macintyre",
      "Billie Gadsdon",
      "Beau Gadsdon",
      "Harry Marcus",
      "Diego Scott",
      "Logan Challis",
      "Albie Salter",
      "Zsa Zsa Zemeckis",
      "Albie Mander",
      "Eloísa Ferreira",
      "Eliza Daley",
      "Elodie Crapper",
      "Faith Delaney",
      "Michelle Dockery",
      "Gwilym Lee",
      "Delilah O’Riordan",
      "David Fynn",
      "Ophelia Lovibond",
      "Nicholas Pinnock",
      "Nikki Amuka-Bird",
      "Cache Vanderpuye",
      "Anya Marco-Harris",
      "Tony Way",
      "Jemima Rooper",
      "Joel Oulette",
      "Dannie McCallum",
      "Keith Bartlett",
      "Daniel Betts",
      "Leslie Zemeckis",
      "Alfie Todd",
      "Mohammed George",
      "Logan Matthews",
      "Denise Faye",
      "Jenna Boyd",
      "David Charles",
      "Lilly Aspell",
      "Jonathan Aris",
      "Louis Suc",
      "Eloise Webb",
      "Angus Wright",
      "Stuart Bowman",
      "Alasdair Craig",
      "Martin Bassindale",
      "Louis Sparks",
      "Hope Delaney",
      "Dexter Sol Ansell",
      "Phil Aizlewood",
      "Steven Dykes",
      "Mitchell Mullen",
      "James Eeles",
      "Jack Bennett",
      "Chris Rogers",
      "Frances Barry",
      "Makenzie Carmichael",
      "Louis Philpott",
      "Stephanie Siadatan",
      "Matt Ledray",
      "Giovanni Tria",
    ],
  },
  {
    name: "Alguien te está mirando",
    year: "1988",
    directors: ["Horacio Maldonado", "Gustavo Cova"],
    writers: ["Horacio Maldonado", "Gustavo Cova"],
    actors: [
      "Marisa Ferrari",
      "Horacio Erman",
      "Ana María Pittaluga",
      "Daniela Pal",
      "Fernando Bonfante",
      "James Murray",
      "Hugo Halbrich",
      "Lucy Green",
      "Andrea Fusero",
      "Gustavo Stuka Fossá",
      "Michel Peyronel",
      "Osvaldo Santoro",
      "Jorge Abel Martín",
    ],
  },
  {
    name: "Mickey 17",
    year: "2025",
    directors: ["Bong Joon Ho"],
    writers: ["Bong Joon Ho"],
    actors: [
      "Robert Pattinson",
      "Naomi Ackie",
      "Steven Yeun",
      "Mark Ruffalo",
      "Toni Collette",
      "Anamaria Vartolomei",
      "Daniel Henshall",
      "Patsy Ferran",
      "Steve Park",
      "Tim Key",
      "Holliday Grainger",
      "Michael Monroe",
      "Cameron Britton",
      "Edward Davis",
      "Ian Hanmore",
      "Lloyd Hutchinson",
      "Christian Patterson",
      "Samuel Blenkin",
      "Sabet Choudhury",
      "Rose Shalloo",
      "Bronwyn James",
      "Milo James",
      "Jude Mack",
      "Thomas Turgoose",
      "Adam Colborne",
      "Tom Cawte",
      "Ellen Robertson",
      "Sam Woodhams",
      "Kayla Meikle",
      "Haydn Gwynne",
      "Theo Ogundipe",
      "Jamila Wingett",
      "Spike White",
      "Angus Imrie",
      "Afolabi Alli",
      "Anna Mouglalis",
    ],
  },
  {
    type: "MINISERIES",
    tvName: "Black Mirror",
    season: 7,
    name: "Black Mirror: USS Callister – Into Infinity",
    year: "2025",
    directors: ["Toby Haynes"],
    writers: ["Bisha K Ali", "Charlie Brooker", "William Bridges"],
    actors: [
      "Cristin Milioti",
      "Jimmi Simpson",
      "Billy Magnussen",
      "Milanka Brooks",
      "Osy Ikhile",
      "Paul G. Raymond",
      "Jesse Plemons",
      "Gwion Glyn",
      "Hélder Fernandes",
      "Ebenezer Gyau",
      "Bilal Hasna",
      "Iolanthe",
      "Rita Estevanovich",
      "Daniel Middleton",
      "Thomas Simons",
    ],
  },
  {
    type: "MINISERIES",
    tvName: "Black Mirror",
    season: 7,
    name: "Black Mirror: Common People",
    year: "2025",
    directors: ["Ally Pankiw"],
    writers: ["Charlie Brooker"],
    actors: [
      "Chris O'Dowd",
      "Rashida Jones",
      "Tracee Ellis Ross",
      "Nicholas Cirillo",
      "Donald Sales",
      "Lucy Turnbull",
      "Milana Wan",
      "Sofia Hodsoni",
      "Sabrina Jalees",
    ],
  },
  {
    name: "A Guide to Recognizing Your Saints",
    year: "2006",
    directors: ["Dito Montiel"],
    writers: ["Dito Montiel"],
    actors: [
      "Shia LaBeouf",
      "Channing Tatum",
      "Robert Downey Jr.",
      "Rosario Dawson",
      "Melonie Díaz",
      "Chazz Palminteri",
      "Dianne Wiest",
      "Martin Compston",
      "Olga Merediz",
      "Laila Liliana Garro",
      "Eléonore Hendricks",
      "Adam Scarimbolo",
      "Federico Castelluccio",
      "Chance Kelly",
      "Gilbert Cruz",
      "Scott Michael Campbell",
      "Eric Roberts",
      "Peter Anthony Tambakis",
      "Jermel Wilson",
    ],
  },
  {
    type: "MINISERIES",
    tvName: "Black Mirror",
    season: 7,
    name: "Black Mirror: Bête Noire",
    year: "2025",
    directors: ["Toby Haynes"],
    writers: ["Charlie Brooker"],
    actors: [
      "Siena Kelly",
      "Rosy McEwen",
      "Michael Workeye",
      "Ben Bailey Smith",
      "Amber Grappy",
      "Ravi Aujla",
      "Elena Sanz",
      "Hannah Griffiths",
      "Ben Ashenden",
      "Alice brittain",
    ],
  },
  {
    type: "MINISERIES",
    tvName: "Black Mirror",
    season: 7,
    name: "Black Mirror: Hotel Reverie",
    year: "2025",
    directors: ["Haolu Wang"],
    writers: ["Charlie Brooker"],
    actors: [
      "Emma Corrin",
      "Issa Rae",
      "Awkwafina",
      "Harriet Walter",
      "Enzo Cilenti",
      "Elliot Barnes-Worrell",
      "Natalia Kostrzewa",
      "Rebecca Ozer",
      "Stanley Weber",
      "Farid Larbi",
      "Waleed Hammad",
      "Charlie Hiscock",
      "Tessa Wong",
      "Magnus Bruun",
      "Danielle Vitalis",
      "Elaine Claxton",
      "Amro Mahmoud",
      "Asheq Akhtar",
    ],
  },
  {
    name: "Black Mirror: Plaything",
    year: "2025",
    directors: ["David Slade"],
    writers: ["Charlie Brooker"],
    actors: [
      "Peter Capaldi",
      "Lewis Gribben",
      "James Nelson-Joyce",
      "Michele Austin",
      "Will Poulter",
      "Asim Chaudhry",
    ],
  },
  {
    name: "Black Mirror: Eulogy",
    year: "2025",
    directors: ["Luke Taylor", "Christopher Barrett"],
    writers: ["Charlie Brooker", "Ella Road"],
    actors: [
      "Paul Giamatti",
      "Patsy Ferran",
      "Ramesh Nair",
      "Declan Mason",
      "Hazel Monaghan",
      "Ava Galindez",
      "Paul Kissaun",
      "Dominic Bruce-Radcliffe",
      "Michael Sotillo",
      "Sophie Dragon",
      "Rebecca Ozer",
    ],
  },
  {
    name: "Conclave",
    year: "2024",
    directors: ["Edward Berger"],
    writers: ["Peter Straughan"],
    actors: [
      "Ralph Fiennes",
      "Stanley Tucci",
      "John Lithgow",
      "Isabella Rossellini",
      "Lucian Msamati",
      "Carlos Diehz",
      "Sergio Castellitto",
      "Brían F. O'Byrne",
      "Merab Ninidze",
      "Thomas Loibl",
      "Jacek Koman",
      "Bruno Novelli",
      "Rony Kramer",
      "Valerio Da Silva",
      "Joseph Mydell",
      "Vincenzo Failla",
      "Garrick Hagon",
      "Madhav Sharma",
      "Loris Loddi",
      "Roberto Citran",
      "Antonio Toma",
      "Balkissa Souley Maiga",
      "Romuald Kłos",
      "Willie Jonah",
    ],
  },
  {
    name: "The Naked Gun 2½: The Smell of Fear",
    year: "1991",
    directors: ["David Zucker"],
    writers: ["David Zucker", "Pat Proft"],
    actors: [
      "Leslie Nielsen",
      "Priscilla Presley",
      "George Kennedy",
      "O. J. Simpson",
      "Robert Goulet",
      "Richard Griffiths",
      "Jacqueline Brookes",
      "Anthony James",
      "Lloyd Bochner",
      "Tim O'Connor",
      "Peter Mark Richman",
      "Ed Williams",
      "John Roarke",
      "Margery Jane Ross",
      "Peter Van Norden",
      "Gail Neely",
      "Colleen Fitzpatrick",
      "Sally Rosenblatt",
      "Alexander Folk",
      "Jose Gonzales-Gonzales",
      "Larry McCormick",
      "Cliff Bemis",
      "D.D. Howard",
      "William Woodson",
      "Mel Tormé",
      "Zsa Zsa Gabor",
      "Bill Chemerka",
      "Christopher J. Keene",
      "Ken Kerman",
      "Al Fann",
      "Tom McGreevey",
      "James Gilstrap",
      "'Weird Al' Yankovic",
      "Gina Mastrogiacomo",
      "Jeff Wright",
      "C. Lindsay Workman",
      "John Stevens",
      "Gokul",
      "Charlotte Zucker",
      "Don Pugsley",
      "Carlos Betancourt",
      "Bernardo Márquez",
      "Margarito Mendoza",
      "Lee Terri",
      "Claude Jay McLin",
      "Manny Perry",
      "Alex Zimmerman",
      "Raynor Scheine",
      "John Fleck",
      "Susan Breslau",
      "Leslie Maier",
      "Ron Rosenblatt",
      "Jennifer Kretchmer",
      "Ryan Harrison",
      "David Zucker",
      "Robert K. Weiss",
      "Robert LoCash",
      "Burton Zucker",
      "Lewis Friedman",
      "Bob Reitman",
      "Gene Mueller",
      "Gino Salomone",
      "Robert J. Elisberg",
      "Mindy Newborn",
      "Jan Campbell",
      "Wendy Hogan",
    ],
  },
  {
    name: "End of Watch",
    year: "2012",
    directors: ["David Ayer"],
    writers: ["David Ayer"],
    actors: [
      "Jake Gyllenhaal",
      "Michael Peña",
      "Natalie Martinez",
      "Anna Kendrick",
      "David Harbour",
      "Frank Grillo",
      "America Ferrera",
      "Cody H. Carolin",
      "Shondrella Avery",
      "Hugh Daly",
      "Gene Hong",
      "Cle Sloan",
      "Jaime FitzSimons",
      "Everton Lawrence",
      "Zone",
      "Alvin Norman",
      "Richard Cabral",
      "Diamonique",
      "Maurice Compte",
      "Flakiss",
      "Manny Jimenez Jr.",
      "Nikki Nicholle Barreras",
      "Kristy Wu",
      "Candace Smith",
      "Corina Calderon",
      "David Fernandez Jr.",
      "McKinley Freeman",
      "Kevin Vance",
      "David Castañeda",
      "John A. Russo",
      "Michael Monks",
      "Serene Branson",
      "Ramon Camacho",
      "Eric Garcetti",
      "Nelly Castillo",
      "Judy Echavez",
      "Ruben Roberto Gomez",
      "Robert Gatewood",
      "Diana Noris",
      "Ron Roggé",
    ],
  },
  {
    name: "Thunderbolts*",
    year: "2025",
    directors: ["Jake Schreier"],
    writers: ["Joanna Calo", "Eric Pearson"],
    actors: [
      "Florence Pugh",
      "Sebastian Stan",
      "Julia Louis-Dreyfus",
      "Lewis Pullman",
      "David Harbour",
      "Wyatt Russell",
      "Hannah John-Kamen",
      "Olga Kurylenko",
      "Geraldine Viswanathan",
      "Wendell Pierce",
      "Chris Bauer",
      "Violet McGraw",
      "Alexa Swinton",
      "Eric Lange",
      "Chiara Stella",
      "Stefano Carannante",
      "Gianfranco Terrin",
      "Georgui Kasaev",
      "Charlotte Ann Tucker",
      "Gabrielle Byndloss",
      "Regina Ting Chen",
      "Mallory Hoff",
      "Jennifer Chung",
      "Julia Aku",
      "Clayton Cooper",
      "Joshua Mikel",
      "Molly Carden",
      "Harrison Russell",
      "Robert Germar",
      "Matt Einhorn",
      "Kelvin Witherspoon",
      "Anny Jules",
      "Chad Gall",
      "Danielle DeBrock",
      "Phong Giang",
      "Mackensi Emory",
      "Alexander Roberts",
      "Chris Heeder",
      "Matthew Patrick",
    ],
  },
  {
    name: "The Conversation",
    year: "1974",
    directors: ["Francis Ford Coppola"],
    writers: ["Francis Ford Coppola"],
    actors: [
      "Gene Hackman",
      "John Cazale",
      "Allen Garfield",
      "Frederic Forrest",
      "Cindy Williams",
      "Michael Higgins",
      "Elizabeth MacRae",
      "Teri Garr",
      "Harrison Ford",
      "Mark Wheeler",
      "Robert Shields",
      "Phoebe Alexander",
      "Ramon Bieri",
      "Gian-Carlo Coppola",
      "Robert Duvall",
      "Richard Hackman",
      "Billy Dee Williams",
    ],
  },
  {
    name: "Drop",
    year: "2025",
    directors: ["Christopher Landon"],
    writers: ["Jillian Jacobs", "Christopher Roach"],
    actors: [
      "Meghann Fahy",
      "Brandon Sklenar",
      "Violett Beane",
      "Jacob Robinson",
      "Reed Diamond",
      "Gabrielle Ryan",
      "Jeffery Self",
      "Ed Weeks",
      "Travis Nelson",
      "Fiona Browne",
      "Tara Mae",
      "Stephanie Karam",
      "Saoirse Hayden",
      "Jordon-Dion Scanlon",
      "Ellen Reidy",
      "Benjamin Pelletier",
      "Niamh McHenry",
      "Michael Shea",
    ],
  },
];
export default Vol9;
