let Vol9 = [
  {
    name: "ヤクザと家族 The Family",
    year: "2020",
    directors: ["Michihito Fujii"],
    writers: ["Michihito Fujii"],
    actors: [
      "Go Ayano",
      "Hiroshi Tachi",
      "Machiko Ono",
      "Yukiya Kitamura",
      "Hayato Ichihara",
      "Hayato Isomura",
      "Shinobu Terajima",
      "Ryutaro Ninomiya",
      "Taro Suruga",
      "Ryo Iwamatsu",
      "Shun Sugata",
      "Suon Kan",
      "Kosuke Toyohara",
      "Rina Komiyama",
      "Goki Maeda",
      "Akito Fujii",
    ],
  },
  {
    name: "1408",
    year: "2007",
    directors: ["Mikael Hafstrom"],
    writers: ["Scott Alexander", "Matt Greenberg", "Larry Karaszewski"],
    actors: [
      "John Cusack",
      "Samuel L. Jackson",
      "Mary McCormack",
      "Jasmine Jessica Anthony",
      "Tony Shalhoub",
      "Alexandra Silber",
      "Noah Lee Margetts",
      "William Armstrong",
      "Paul Birchard",
      "Margot Leicester",
      "Angel Oquendo",
      "Walter Lewis",
      "Eric Meyers",
      "Holly Hayes",
      "Johann Urb",
      "Andrew-Lee Potts",
      "Kim Thomson",
      "Drew Powell",
      "Isiah Whitlock Jr.",
      "Benny Urquidez",
      "Len Cariou",
      "Ray Nicholas",
      "Paul Kasey",
      "George Cottle",
      "William Willoughby",
      "Thomas A. McMahon",
      "Kevin Dobson",
      "Peter Conboy",
      "Georgie Lee-Robinson",
      "Bernadette Lords",
      "Rob McGillivray",
      "Kate Walsh",
    ],
  },
  {
    name: "Museo",
    year: "2018",
    directors: ["Alonso Ruizpalacios"],
    writers: ["Manuel Alcala", "Alonso Ruizpalacios"],
    actors: [
      "Gael García Bernal",
      "Leonardo Ortizgris",
      "Alfredo Castro",
      "Bernardo Velasco",
      "Leticia Brédice",
      "Ilse Salas",
      "Lisa Owen",
      "Simon Russell Beale",
      "Maite Suárez Diez",
    ],
  },
  {
    name: "The Good, the Bad and the Ugly",
    year: "1966",
    directors: ["Sergio Leone"],
    writers: [
      "Luciano Vincenzoni",
      "Furio Scarpelli",
      "Mickey Knox",
      "Sergio Leone",
      "Agenore Incrocci",
    ],
    actors: [
      "Clint Eastwood",
      "Eli Wallach",
      "Lee Van Cleef",
      "Aldo Giuffrè",
      "Luigi Pistilli",
      "Rada Rassimov",
      "Enzo Petito",
      "Claudio Scarchilli",
      "Antonio Casale",
      "Livio Lorenzon",
      "Sandro Scarchilli",
      "Benito Stefanelli",
      "Angelo Novi",
      "Antonio Casas",
      "Aldo Sambrell",
      "Al Mulock",
      "Sergio Mendizábal",
      "Antonio Molino Rojo",
      "Lorenzo Robledo",
      "Mario Brega",
      "Chelo Alonso",
      "Fortunato Arena",
      "Román Ariznavarreta",
      "Silvana Bacci",
      "Joseph Bradley",
      "Frank Braña",
      "Amerigo Castrighella",
      "Saturno Cerra",
      "William Conroy",
      "Axel Darna",
      "Tony Di Mitri",
      "Gianni Di Segni",
      "Alberigo Donadeo",
      "Attilio Dottesio",
      "Luis Fernández de Eribe",
      "Veriano Ginesi",
      "Jesús Guzmán",
      "Víctor Israel",
      "Nazzareno Natale",
      "Ricardo Palacios",
      "Antonio Palombi",
      "Romano Puppo",
      "Antoñito Ruiz",
      "Aysanoa Runachagua",
      "Enrique Santiago",
      "José Terrón",
      "Franco Tocci",
      "Antonio Montoya",
    ],
  },
  {
    name: "The Last Suit",
    year: "2017",
    directors: ["Pablo Solarz"],
    writers: ["Pablo Solarz"],
    actors: [
      "Miguel Ángel Solá",
      "Ángela Molina",
      "Olga Bołądź",
      "Julia Beerhold",
      "Martín Piroyansky",
      "Jan Mayzel",
      "Maciej Grubich",
      "Michał Sikorski",
      "Mora Starosta",
      "Leticia Gurfinkiel",
      "José Luciano González",
      "Norma Argentina",
      "Cristóbal Pinto",
      "Natalia Verbeke",
      "Noemí Frenkel",
      "Nora Zinsky",
      "Nicolás Strok",
      "Pilar Alonso",
      "Yanina Frankel",
      "Miel Bargman",
      "Mariel Rosciano",
      "Arlén Germade López de las Hazas",
      "Max Berliner",
      "Richard García",
      "Julia Martinetto",
      "Natalie Pinot",
      "Pedro Vasallo",
      "Tobías Rasse",
      "Paula Lussi",
      "Mateo Flossdorf",
      "Luciano Varela",
      "Jacek Lenartowicz",
      "Karolina Porcari",
      "Markus Oberhauser",
      "Francisco de Palma",
      "Pablo Solarz",
      "Maarten Dannenberg",
      "Roksana Nievadis",
      "Blanca Rodríguez",
      "Blanca Rodríguez Rosciano",
      "Micaela Eppeilboim",
      "Valentín Sasson",
      "Iair Kemeny",
      "Ethan Kemeny",
      "Alejandro Goldberg",
      "Diego Vainer",
      "Enrique Franov",
      "Jorge Goldberg",
      "Andrés Hojman",
      "Marina Svartzman",
      "Melina Peregal",
      "Andrea Cohan",
      "Ana Ceruti",
      "Paula Etchebehere",
      "Matías Peccia",
      "Josi Jamui",
      "Javier Cerpavicius",
      "Ariel Blickstein",
      "Martín Godlberg",
    ],
  },
  {
    name: "Flow",
    year: "2023",
    directors: ["Gints Zilbalodis"],
    writers: ["Gints Zilbalodis", "Matiss Kaza"],
    actors: [],
  },
  {
    name: "Nosferatu",
    year: "2024",
    directors: ["Robert Eggers"],
    writers: ["Robert Eggers"],
    actors: [
      "Lily-Rose Depp",
      "Nicholas Hoult",
      "Bill Skarsgård",
      "Aaron Taylor-Johnson",
      "Willem Dafoe",
      "Emma Corrin",
      "Ralph Ineson",
      "Simon McBurney",
      "Adéla Hesová",
      "Milena Konstantinova",
      "Stacy Thunes",
      "Gregory Gudgeon",
      "Robert Russell",
      "Curtis Matthew",
      "Claudiu Trandafir",
      "Georgina Bereghianu",
      "Jordan Haj",
      "Kateřina Bílá",
      "Maria Ion",
      "Tereza Dušková",
      "Liana Navrot",
      "Mihai Verbintschi",
      "Karel Dobrý",
      "Andrei Sergeev",
      "Matěj Beneš",
      "Marek Pospíchal",
      "Jan Filipenský",
      "Alex East",
      "Christian Dunckley Clark",
      "Andrea Miltner",
      "Robin Finesilver",
      "Paul Maynard",
      "Charles Horne",
      "Ella Bernstein",
      "Meredith Digings",
    ],
  },
];

export default Vol9;
