let Vol9 = [
  {
    name: "ヤクザと家族 The Family",
    year: "2020",
    directors: ["Michihito Fujii"],
    writers: ["Michihito Fujii"],
    actors: [
      "Go Ayano",
      "Hiroshi Tachi",
      "Machiko Ono",
      "Yukiya Kitamura",
      "Hayato Ichihara",
      "Hayato Isomura",
      "Shinobu Terajima",
      "Ryutaro Ninomiya",
      "Taro Suruga",
      "Ryo Iwamatsu",
      "Shun Sugata",
      "Suon Kan",
      "Kosuke Toyohara",
      "Rina Komiyama",
      "Goki Maeda",
      "Akito Fujii",
    ],
  },
  {
    name: "1408",
    year: "2007",
    directors: ["Mikael Hafstrom"],
    writers: ["Scott Alexander", "Matt Greenberg", "Larry Karaszewski"],
    actors: [
      "John Cusack",
      "Samuel L. Jackson",
      "Mary McCormack",
      "Jasmine Jessica Anthony",
      "Tony Shalhoub",
      "Alexandra Silber",
      "Noah Lee Margetts",
      "William Armstrong",
      "Paul Birchard",
      "Margot Leicester",
      "Angel Oquendo",
      "Walter Lewis",
      "Eric Meyers",
      "Holly Hayes",
      "Johann Urb",
      "Andrew-Lee Potts",
      "Kim Thomson",
      "Drew Powell",
      "Isiah Whitlock Jr.",
      "Benny Urquidez",
      "Len Cariou",
      "Ray Nicholas",
      "Paul Kasey",
      "George Cottle",
      "William Willoughby",
      "Thomas A. McMahon",
      "Kevin Dobson",
      "Peter Conboy",
      "Georgie Lee-Robinson",
      "Bernadette Lords",
      "Rob McGillivray",
      "Kate Walsh",
    ],
  },
  {
    name: "Museo",
    year: "2018",
    directors: ["Alonso Ruizpalacios"],
    writers: ["Manuel Alcala", "Alonso Ruizpalacios"],
    actors: [
      "Gael García Bernal",
      "Leonardo Ortizgris",
      "Alfredo Castro",
      "Bernardo Velasco",
      "Leticia Brédice",
      "Ilse Salas",
      "Lisa Owen",
      "Simon Russell Beale",
      "Maite Suárez Diez",
    ],
  },
  {
    name: "The Good, the Bad and the Ugly",
    year: "1966",
    directors: ["Sergio Leone"],
    writers: [
      "Luciano Vincenzoni",
      "Furio Scarpelli",
      "Mickey Knox",
      "Sergio Leone",
      "Agenore Incrocci",
    ],
    actors: [
      "Clint Eastwood",
      "Eli Wallach",
      "Lee Van Cleef",
      "Aldo Giuffrè",
      "Luigi Pistilli",
      "Rada Rassimov",
      "Enzo Petito",
      "Claudio Scarchilli",
      "Antonio Casale",
      "Livio Lorenzon",
      "Sandro Scarchilli",
      "Benito Stefanelli",
      "Angelo Novi",
      "Antonio Casas",
      "Aldo Sambrell",
      "Al Mulock",
      "Sergio Mendizábal",
      "Antonio Molino Rojo",
      "Lorenzo Robledo",
      "Mario Brega",
      "Chelo Alonso",
      "Fortunato Arena",
      "Román Ariznavarreta",
      "Silvana Bacci",
      "Joseph Bradley",
      "Frank Braña",
      "Amerigo Castrighella",
      "Saturno Cerra",
      "William Conroy",
      "Axel Darna",
      "Tony Di Mitri",
      "Gianni Di Segni",
      "Alberigo Donadeo",
      "Attilio Dottesio",
      "Luis Fernández de Eribe",
      "Veriano Ginesi",
      "Jesús Guzmán",
      "Víctor Israel",
      "Nazzareno Natale",
      "Ricardo Palacios",
      "Antonio Palombi",
      "Romano Puppo",
      "Antoñito Ruiz",
      "Aysanoa Runachagua",
      "Enrique Santiago",
      "José Terrón",
      "Franco Tocci",
      "Antonio Montoya",
    ],
  },
  {
    name: "The Last Suit",
    year: "2017",
    directors: ["Pablo Solarz"],
    writers: ["Pablo Solarz"],
    actors: [
      "Miguel Ángel Solá",
      "Ángela Molina",
      "Olga Bołądź",
      "Julia Beerhold",
      "Martín Piroyansky",
      "Jan Mayzel",
      "Maciej Grubich",
      "Michał Sikorski",
      "Mora Starosta",
      "Leticia Gurfinkiel",
      "José Luciano González",
      "Norma Argentina",
      "Cristóbal Pinto",
      "Natalia Verbeke",
      "Noemí Frenkel",
      "Nora Zinsky",
      "Nicolás Strok",
      "Pilar Alonso",
      "Yanina Frankel",
      "Miel Bargman",
      "Mariel Rosciano",
      "Arlén Germade López de las Hazas",
      "Max Berliner",
      "Richard García",
      "Julia Martinetto",
      "Natalie Pinot",
      "Pedro Vasallo",
      "Tobías Rasse",
      "Paula Lussi",
      "Mateo Flossdorf",
      "Luciano Varela",
      "Jacek Lenartowicz",
      "Karolina Porcari",
      "Markus Oberhauser",
      "Francisco de Palma",
      "Pablo Solarz",
      "Maarten Dannenberg",
      "Roksana Nievadis",
      "Blanca Rodríguez",
      "Blanca Rodríguez Rosciano",
      "Micaela Eppeilboim",
      "Valentín Sasson",
      "Iair Kemeny",
      "Ethan Kemeny",
      "Alejandro Goldberg",
      "Diego Vainer",
      "Enrique Franov",
      "Jorge Goldberg",
      "Andrés Hojman",
      "Marina Svartzman",
      "Melina Peregal",
      "Andrea Cohan",
      "Ana Ceruti",
      "Paula Etchebehere",
      "Matías Peccia",
      "Josi Jamui",
      "Javier Cerpavicius",
      "Ariel Blickstein",
      "Martín Godlberg",
    ],
  },
  {
    name: "Flow",
    year: "2023",
    directors: ["Gints Zilbalodis"],
    writers: ["Gints Zilbalodis", "Matiss Kaza"],
    actors: [],
  },
  {
    name: "Nosferatu",
    year: "2024",
    directors: ["Robert Eggers"],
    writers: ["Robert Eggers"],
    actors: [
      "Lily-Rose Depp",
      "Nicholas Hoult",
      "Bill Skarsgård",
      "Aaron Taylor-Johnson",
      "Willem Dafoe",
      "Emma Corrin",
      "Ralph Ineson",
      "Simon McBurney",
      "Adéla Hesová",
      "Milena Konstantinova",
      "Stacy Thunes",
      "Gregory Gudgeon",
      "Robert Russell",
      "Curtis Matthew",
      "Claudiu Trandafir",
      "Georgina Bereghianu",
      "Jordan Haj",
      "Kateřina Bílá",
      "Maria Ion",
      "Tereza Dušková",
      "Liana Navrot",
      "Mihai Verbintschi",
      "Karel Dobrý",
      "Andrei Sergeev",
      "Matěj Beneš",
      "Marek Pospíchal",
      "Jan Filipenský",
      "Alex East",
      "Christian Dunckley Clark",
      "Andrea Miltner",
      "Robin Finesilver",
      "Paul Maynard",
      "Charles Horne",
      "Ella Bernstein",
      "Meredith Digings",
    ],
  },
  {
    name: "Pusher",
    year: "1996",
    directors: ["Nicolas Winding Refn"],
    writers: ["Jens Dahl", "Nicolas Winding Refn"],
    actors: [
      "Kim Bodnia",
      "Mads Mikkelsen",
      "Laura Drasbæk",
      "Zlatko Burić",
      "Slavko Labović",
      "Peter Andersson",
      "Vanja Bajicic",
      "Lisbeth Rasmussen",
      "Levino Jensen",
      "Nicolas Winding Refn",
      "Thomas Bo Larsen",
      "Lars Bom",
      "Michael Hasselflug",
      "Jesper Lohmann",
      "Steen Fridberg",
      "Gordon Kennedy",
      "Gyda Hansen",
      "Kenneth Schultz",
      "Coco C.P. Dalbert",
      "Karsten Schrøder",
      "Keith C. Stanley",
      "Lisa Lach Nielsen",
      "Thomas Aagren",
      "Eva Nauman",
      "Thomas Herschel",
      "Kenneth Herschel",
      "Gunner Clemann",
      "Alex Nielsen",
      "Laust Balskov",
      "Kim Maali",
      "Morten Pay",
      "Liv Corfixen",
      "Per Leth",
      "John Kalmar",
      "Thor Nielsen",
      "Evald",
      "Jesper Staal",
    ],
  },
  {
    name: "Changing Lanes",
    year: "2002",
    directors: ["Roger Michell"],
    writers: ["Michael Tolkin", "Chap Taylor"],
    actors: [
      "Ben Affleck",
      "Samuel L. Jackson",
      "Toni Collette",
      "Sydney Pollack",
      "William Hurt",
      "Amanda Peet",
      "Richard Jenkins",
      "Dylan Baker",
      "Kim Staunton",
      "John Benjamin Hickey",
      "Michael McGrath",
      "Bruce Altman",
      "Jennifer Dundas",
      "Joe Grifasi",
      "Tina Sloan",
      "Akil Walker",
      "Matt Malloy",
      "Cole Hawkins",
      "Ileen Getz",
      "Myra Lucretia Taylor",
      "Lisa LeGuillou",
      "Angela Goethals",
      "Kevin Sussman",
      "Susan Varon",
      "Noel Wilson",
      "Angel Caban",
      "Jim Lovelett",
      "Julia Gibson",
      "Ray Bokhour",
      "Suzanne Hevner",
      "Caleb Archer",
      "Jordan Gelber",
      "Olga Merediz",
      "Jayne Houdyshell",
      "Shabazz Ray",
      "Raymond Anthony Thomas",
      "Michael Pitt",
      "Genevieve Elam",
      "Juan Lara",
      "Anastasia Rojas",
      "Nicole Wright",
      "Clive Oliver Greenberg",
      "Gilbert S. Williams",
      "Sophia Guaspari",
      "Ruben Jared Seraballs",
      "Father Bonneau",
      "Jewel Brimage",
      "Katarina Kianna",
      "Vanessa Quel",
      "Howard I. Laniado",
      "Tony Machine",
      "Carolyn Feldschuh",
      "Maria Alaina Mason",
      "Harvey Waldman",
      "Pamela Hart",
      "Neal Jones",
      "Susan Blackwell",
      "Alyson Renaldo",
      "James Soviero",
      "Mary A. Kelly",
      "Anthony DiGiacomo",
      "Richard Velasco",
      "Leonard L. Thomas",
      "Richard Kelly",
      "Selena Blake",
      "Harriet Rosenthal",
      "John Kohl",
      "Lisa Vogel",
      "Bob Heffernan",
      "Michael Arthur",
      "Myriam Blanckaert",
      "Lloyd Booker",
      "Salvatore Cavaliere",
      "Israel Chaplin",
      "Monet Cunningham",
      "Jason Diamond",
      "Philip M. Gardiner",
      "Sean T. Krishnan",
      "Michael Lanuto",
      "Pete Macnamara",
      "Joseph Oliveira",
      "David C. Roehm Sr.",
      "Sam Rovin",
      "John H. Tobin",
      "Jarred Treiber",
      "David Von Roehm",
      "Ray Wineteer",
      "Waneeki Yokomee-Fung",
    ],
  },
  {
    name: "Kraven the Hunter",
    year: "2024",
    directors: ["Jc Chandor"],
    writers: ["Richard Wenk", "Matt Holloway", "Art Marcum"],
    actors: [
      "Aaron Taylor-Johnson",
      "Ariana DeBose",
      "Fred Hechinger",
      "Alessandro Nivola",
      "Christopher Abbott",
      "Russell Crowe",
      "Yuri Kolokolnikov",
      "Levi Miller",
      "Tom Reed",
      "Billy Barratt",
      "Diaana Babnicova",
      "Murat Seven",
      "Greg Kolpakchi",
      "Mark Arden",
      "Jack Brady",
      "Alex Batareanu",
      "Will Bowden",
      "Damola Adelaja",
      "Guillaume Delaunay",
      "Duran Fulton Brown",
      "Tanaka Mandimika",
      "Robert Hladik",
      "Thor Kjartansson",
      "Christos Dante",
      "Adam Bowman",
      "Bradley Farmer",
      "Paul Bailey",
      "Dritan Kastrati",
      "Anita-Joy Uwajeh",
      "Alex Skarbek",
      "Ivan Ignatenko",
      "Susan Aderin",
      "Preslav Shipkaliev",
      "Al Nedjari",
      "Elizabeth Appleby",
      "Marie Hogle",
      "Jon Xue Zhang",
      "Elander Moore",
      "Bailey Patrick",
      "Christopher Whitlow",
      "Waleed Hammad",
      "Toto Bruin",
      "Maxine Whittaker",
      "Jonny James",
      "Rashid Phoenix",
      "George Surry",
      "Yusuf Chaudhri",
      "Andrei Nazarenko",
      "Doren John Farmer",
      "Douglas Robson",
      "Michael Shaeffer",
      "Roderick Hill",
      "Camilla Aiko",
      "Neil Bishop",
      "Rachel Handshaw",
      "Odimegwu Okoye",
    ],
  },
  {
    name: "Güeros",
    year: "2014",
    directors: ["Alonso Ruizpalacios"],
    writers: ["Alonso Ruizpalacios", "Gibran Portela"],
    actors: [
      "Sebastián Aguirre",
      "Tenoch Huerta Mejía",
      "Leonardo Ortizgris",
      "Ilse Salas",
      "Raúl Briones",
      "Sophie Alexander-Katz",
      "Laura Almela",
      "Camila Lora",
      "Marcelo Tobar",
      "Alfonso Charpener",
      "Adrián Ladrón",
      "Bernardo Velasco",
      "Alonso Ruizpalacios",
      "Yojath Okamoto",
    ],
  },

  {
    name: "Brick",
    year: "2005",
    directors: ["Rian Johnson"],
    writers: ["Rian Johnson"],
    actors: [
      "Joseph Gordon-Levitt",
      "Emilie de Ravin",
      "Nora Zehetner",
      "Lukas Haas",
      "Noah Fleiss",
      "Matt O'Leary",
      "Noah Segan",
      "Meagan Good",
      "Brian J. White",
      "Richard Roundtree",
      "Jonathan Cauff",
      "Reedy Gibbs",
      "Lucas Babin",
      "Ari Welkom",
      "Tracy Bitterolf",
      "Cody Lightning",
      "McJoel Hamilton",
      "Lauren Johnson",
      "Dylan Lujano",
    ],
  },
  {
    name: "Wolfs",
    year: "2024",
    directors: ["Jon Watts"],
    writers: ["Jon Watts"],
    actors: [
      "George Clooney",
      "Brad Pitt",
      "Austin Abrams",
      "Amy Ryan",
      "Poorna Jagannathan",
      "Zlatko Burić",
      "Richard Kind",
      "Frances McDormand",
      "Sergio Cota Jr.",
      "Alfred Chou",
      "Robert Timothy Smith",
      "Amanda Aday",
      "Kymbali Craig",
      "Linda Carola",
      "Vladimir Sizov",
      "Abby Mohaddes",
      "Sasha Biktagir",
      "Samuel Evan Horowitz",
      "Frank Trigg",
      "Duffy Gaver",
      "Edwin Taylor",
      "Anthony N.",
      "Irina Dubova",
    ],
  },
  {
    name: "The Outfit",
    year: "2022",
    directors: ["Graham Moore"],
    writers: ["Johnathan Mcclain", "Graham Moore"],
    actors: [
      "Mark Rylance",
      "Zoey Deutch",
      "Johnny Flynn",
      "Dylan O'Brien",
      "Simon Russell Beale",
      "Nikki Amuka-Bird",
      "Alan Mehdizadeh",
      "Johnathan McClain",
      "Scoop Wasserstein",
      "Chiedu Agborh",
      "Michael Addo",
      "Michal Forejtek",
      "Bmcabana Sf",
      "John Gumley-Mason",
      "Stephen Knox",
      "Lauris Karklins",
      "Steve Chatfield",
      "William Keetch",
      "Ryan Hall",
    ],
  },
  {
    name: "Caddo Lake",
    year: "2024",
    directors: ["Logan George", "Celine Held"],
    writers: ["Logan George", "Celine Held"],
    actors: [
      "Dylan O'Brien",
      "Eliza Scanlen",
      "Lauren Ambrose",
      "Sam Hennings",
      "Diana Hopper",
      "Eric Lange",
      "Lance E. Nichols",
      "Nina Leon",
      "David Maldonado",
      "Kim Baptiste",
      "Jules Hilillo Fernandez",
      "Jody Sellers",
      "Caroline Falk",
      "Greysen Conley",
      "Larry S. White",
      "Zedrick Tinsley",
      "A.C. Cooper",
      "Jennifer Sellers",
      "Jeff Hartgrove",
    ],
  },
  {
    name: "The Watchers",
    year: "2024",
    directors: ["Ishana Night Shyamalan"],
    writers: ["Ishana Night Shyamalan"],
    actors: [
      "Dakota Fanning",
      "Georgina Campbell",
      "Olwen Fouéré",
      "Oliver Finnegan",
      "Alistair Brammer",
      "John Lynch",
      "Siobhan Hewlett",
      "Hannah Dargan",
      "Emily Dargan",
      "Joel Figueroa",
      "Thabile Michelle Hlongwane",
      "Anthony Morris",
      "Shane O'Regan",
      "Jim Tighe",
      "Zarima McDermott",
      "Morgan Bailey-Rocks",
      "Christian Bailey-Rocks",
      "Éabha Connolly",
      "Hannah Howland",
      "Kya Brame",
      "Ffion Haf",
      "Shannon Antonia",
      "Kofi De Graft Jordan",
      "Charles Camrose",
      "Charlie Mann",
      "Jacob Greenway",
      "Andrea Bechis",
      "Cara Steele",
      "Seán T. Ó Meallaigh",
      "Diarmuid de Faoite",
      "Ann Marie Horan",
    ],
  },
  {
    name: "Sonic the Hedgehog 3",
    year: "2024",
    directors: ["Jeff Fowler"],
    writers: ["Patrick Casey", "Josh Miller", "John Whittington"],
    actors: [
      "Jim Carrey",
      "Ben Schwartz",
      "Keanu Reeves",
      "Idris Elba",
      "Colleen O'Shaughnessey",
      "James Marsden",
      "Tika Sumpter",
      "Lee Majdoub",
      "Krysten Ritter",
      "Adam Pally",
      "Natasha Rothwell",
      "Shemar Moore",
      "Alyla Browne",
      "Tom Butler",
      "Jorma Taccone",
      "Sofia Pernas",
      "Cristo Fernández",
      "James Wolk",
      "Brett Tutor",
      "Richard Sutton",
      "Will Austin",
      "Bola Okun",
      "Reggie Banigo",
      "Barry Calvert",
      "Brendan Murphy",
      "Toru Nakahara",
    ],
  },
  {
    name: "Only God Forgives",
    year: "2013",
    directors: ["Nicolas Winding Refn"],
    writers: ["Nicolas Winding Refn"],
    actors: [
      "Ryan Gosling",
      "Kristin Scott Thomas",
      "Vithaya Pansringarm",
      "Rhatha Phongam",
      "Gordon Brown",
      "Tom Burke",
      "Byron Gibson",
      "Sahajak Boonthanakit",
      "Charlie Ruedpokanon",
      "Wannisa Peungpa",
      "Narucha Chaimareung",
      "Danai Thiengdham",
      "Kowit Wattanakul",
      "Wittchuta Watjanarat",
      "Pitchawat Petchayahon",
      "Nophand Boonyai",
      "Teerawat Mulvilai",
      "Aratchaporn Sathet",
      "Dujdao Vadhanapakorn",
      "Matthew Ryder",
      "Oak Keerati",
      "Sasapin Siriwanij",
      "Nuntiya Thongnoo",
      "Saicheer Wongwirot",
      "Alisa Wongvisut",
      "Byron Bishop",
      "Joe Cummings",
      "Ron Smoorenburg",
    ],
  },
];

export default Vol9;
